### ISSUE TITLE
anyleaf __init__.py has no reference to EcSensor

### ISSUE THREAD

**Issue by keefer223** [kizniche/Mycodo#1027]
### Versions:

 - Mycodo Version: [8.11.0]
 - Raspberry Pi Version: [4]
 - Raspbian OS Version: [Raspberry OS, latest and updated]

### Reproducibility

**Mycodo > mycodo > inputs > anyleaf_ec.py**

line 73 tries to import EcSensor from anyleaf, which is not referenced in the __init__ file.

58    class InputModule(AbstractInput):
59     """A sensor support class that monitors AnyLeaf sensor conductivity (EC)"""
60
61     def __init__(self, input_dev, testing=False):
62          super(InputModule, self).__init__(input_dev, testing=testing, name=__name__)
63
64        self.sensor = None
65        self.constant_k = None
66
67       if not testing:
68             self.setup_custom_options(
69                INPUT_INFORMATION['custom_options'], input_dev)
70            self.initialize_input()
71
72     def initialize_input(self):
73           from anyleaf import EcSensor
74
75        self.sensor = EcSensor(K=self.constant_k)

**Mycodo > env > lib > python3.7 > site-packages > anyleaf > __init_**  

it appears that the whole EcSensor section has been removed from this _init__py version

# Driver for the Anyleaf pH module

from dataclasses import dataclass
from enum import Enum, auto
from typing import Optional, List, Union

import adafruit_ads1x15.ads1115 as ADS
from adafruit_ads1x15.analog_in import AnalogIn
from adafruit_max31865 import MAX31865

from filterpy.kalman import KalmanFilter
from filterpy.common import Q_discrete_white_noise

from . import filter

I found on github the __ini__.py file that does reference EcSensor.
**github > AnyLeaf >anyleaf-python > anyleaf > __init__.py** 

This __init__ has the EcSensor starting on line 387

# Driver for the Anyleaf pH module

from dataclasses import dataclass
from enum import Enum, auto
from typing import Optional, List, Union
import struct

import adafruit_ads1x15.ads1115 as ADS
from adafruit_ads1x15.analog_in import AnalogIn
from adafruit_max31865 import MAX31865

from filterpy.kalman import KalmanFilter
from filterpy.common import Q_discrete_white_noise
import serial
from serial.tools import list_ports

from . import filter
…

386   @dataclass
387   class EcSensor:
388         """An interface for our EC module, which communicates a serial message over UART."""
389         ser: serial.Serial
390	   K: CellConstant
391         cal: Optional[CalPtEc]
392         excitation_mode: ExcMode
393
394    def __init__(self, K: float=1.0, cal: Optional[CalPtEc]=None, 395 exc_mode=ExcMode.READING_ONLY,
395                uart_location='/dev/serial0'):
396         # Same baud as set in firmware: 9,600.
397          self.ser = serial.Serial(uart_location, 9_600, timeout=10)
398          # self.ser = serial.Serial('/dev/ttyS0', 9_600, timeout=10)
399          # self.ser = serial.Serial('/dev/ttyAMA0', 9_600, timeout=10)

### Additional context

It appears that the anyleaf > __init__.py from github just needs to be uploaded to Mycodo.

**Comment by kizniche** [comment]
The anyleaf modules were just updated to the latest Python library. Try [upgrading to master](https://github.com/kizniche/Mycodo/wiki/Updating-to-Github-Master-Branch) and see if that fixes your issue.
