### ISSUE TITLE
Disable option for "Enable Pin optional" (L298N Output) not working

### ISSUE THREAD

**Issue by jcastro** [kizniche/Mycodo#1029]
### Describe the problem/bug
"Use Enable Pin" is not possible to disable it

### Versions:
 - Mycodo Version: 8.11.0
 - Raspberry Pi Version: 4 B 4GB
 - Raspbian OS Version: Raspbian

### Reproducibility
1. Edit output
2. Click on "Use Enable Pin" to disable it
3. This should keep it disabled but once you refresh the page it's still enabled

### Expected behavior

Should keep disabled

### Screenshots

<img width="937" alt="Screenshot 2021-06-19 at 16 20 55" src="https://user-images.githubusercontent.com/190036/122645333-62b02d00-d11a-11eb-80f6-a4d31ce415e9.png">

**Comment by kizniche** [comment]
Are you clicking Save?

**Comment by jcastro** [comment]
> Are you clicking Save?

Yes, after clicking save the page refreshes and I force refresh as well just to make sure it's not cache or something, but the option stays enabled

**Comment by kizniche** [comment]
Are there any error messages at the top of the page or in the Web Log?

**Comment by jcastro** [comment]
I've recorded a video to show it more in detail. I've checked the web log as well but no related errors there


https://user-images.githubusercontent.com/190036/122652824-32c85000-d141-11eb-87f1-7565a36179ac.mp4

Web log
```
-- Logs begin at Sat 2021-06-19 20:35:02 CEST, end at Sat 2021-06-19 20:58:17 CEST. --
jun 19 20:49:31 hydropi systemd[1]: Started gunicorn daemon for Mycodo flask web user interface.
jun 19 20:49:33 hydropi gunicorn[605]: [2021-06-19 20:49:33 +0200] [605] [INFO] Starting gunicorn 20.1.0
jun 19 20:49:33 hydropi gunicorn[605]: [2021-06-19 20:49:33 +0200] [605] [INFO] Listening at: unix:/var/run/mycodoflask.sock (605)
jun 19 20:49:33 hydropi gunicorn[605]: [2021-06-19 20:49:33 +0200] [605] [INFO] Using worker: gthread
jun 19 20:49:33 hydropi gunicorn[605]: [2021-06-19 20:49:33 +0200] [626] [INFO] Booting worker with pid: 626
jun 19 20:54:52 hydropi gunicorn[605]: 2021-06-19 20:54:52,664 Setting camera options
jun 19 20:54:52 hydropi gunicorn[605]: 2021-06-19 20:54:52,678 [7f08dbbb-c493-4f6e-928c-8516f20a0eff] Starting camera thread
jun 19 20:54:52 hydropi gunicorn[605]: mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
jun 19 20:54:52 hydropi gunicorn[605]: mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)```

**Comment by kizniche** [comment]
No need for a video. I just reproduced the issue and am working to figure out a fix. Thanks.

**Comment by kizniche** [comment]
I just pushed a fix. [upgrade to master](https://github.com/kizniche/Mycodo/wiki/Updating-to-Github-Master-Branch) and see if the issue persists.

**Comment by jcastro** [comment]
Seems like it's fixed, thanks!
