### ISSUE TITLE
Widgets on Dashboards not showing any information

### ISSUE THREAD

**Issue by jcastro** [kizniche/Mycodo#1031]
### Describe the problem/bug

Dashboard widget show up empty in the dashboard

### Versions:

 - Mycodo Version: Master branch from Github repo
 - Raspberry Pi Version: 4
 - Raspbian OS Version: Buster lite

### Reproducibility

1. Add a new test dashboard
2. Add a new widget
3. Widget shows empty

### Expected behavior

Dashboard widgets should show the selected information

### Screenshots
<img width="1380" alt="Screenshot 2021-06-19 at 23 02 41" src="https://user-images.githubusercontent.com/190036/122655779-6ca35180-d155-11eb-8d85-dc207c862f27.png">

<img width="1434" alt="Screenshot 2021-06-19 at 23 35 49" src="https://user-images.githubusercontent.com/190036/122655983-20591100-d157-11eb-9f59-6e5abdff1429.png">
<img width="1427" alt="Screenshot 2021-06-19 at 23 35 29" src="https://user-images.githubusercontent.com/190036/122655985-23540180-d157-11eb-8d63-3d2752864962.png">

### Additional context
- I've tried to create a new dashboard and add a new widget, it still shows empty
- I've tried to hard-refresh the browser in case there was some old cache from previous version but the problem seems to persist
- I've tried to completely reboot the system
- Couldn't find anything on the logs that shows any related errors

**Comment by jcastro** [comment]
Looks like Dashboard is back to normal,  might be related with the testing/version changing I'm doing. I will keep it open until we finish the other bugs just in case something comes up

**Comment by kizniche** [comment]
Strange. Not sure what could cause this.
