### ISSUE TITLE
Camera stream issue

### ISSUE THREAD

**Issue by joaozorro** [kizniche/Mycodo#1041]
### Describe the problem/bug

Streaming from the pi camera freezes the whole system 

### Versions:

 - Mycodo Version: [8.11.0]
 - Raspberry Pi Version: [4]
 - Raspbian OS Version: [Raspian]

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. Setup pi camera for streaming 
2. start streaming
3. try to navigate somewhere 
4. Nothing happens and at some point the web seems to lose the communication with the daemon
5. the system becomes completely irresponsive

### Expected behavior

being able to navigate.

### Screenshots

![image](https://user-images.githubusercontent.com/26481026/123552255-3ffec380-d76d-11eb-8199-5f39c3df4074.png)
![image](https://user-images.githubusercontent.com/26481026/123552304-763c4300-d76d-11eb-993e-2c62e893b110.png)

### Additional context

Is there anything that should be added to make it easier to address this issue?

**Comment by kizniche** [comment]
Try reducing the frame rate to 1 FPS

**Comment by joaozorro** [comment]
same issue. any other ideas?

**Comment by kizniche** [comment]
Which camera and how long is your camera ribbon cable?

**Comment by joaozorro** [comment]
Pi Camera, not very long. see the image attached 
![IMG_3559](https://user-images.githubusercontent.com/26481026/123557170-50239c80-d787-11eb-96f1-6560ee814878.jpg)

**Comment by kizniche** [comment]
try streaming with the opencv library instead of picamera
