### ISSUE TITLE
Unable to access Mycodo live URL

### ISSUE THREAD

**Issue by Irfan995** [kizniche/Mycodo#1048]
I have  install mycodo on my linux instance (linux mint). While instaalling it showed, mycodo was installed successfully. When i tried my_ip/live url, the page is giving Not found error. But when i visit my ip, the page is returning that my nginx server was installed successfully. 
I am unable to find the problem
![Screenshot from 2021-06-29 12-37-24](https://user-images.githubusercontent.com/32894315/124651475-ca0d0180-debc-11eb-90b1-eeac20007930.png)
![Screenshot from 2021-06-29 12-38-20](https://user-images.githubusercontent.com/32894315/124651489-cd07f200-debc-11eb-97eb-064d6edd1b04.png)
![Screenshot from 2021-07-07 00-37-31](https://user-images.githubusercontent.com/32894315/124651497-d09b7900-debc-11eb-84b5-c7cee0ab8daf.png)

**Comment by kizniche** [comment]
Only the Raspberry Pi OS is supported. Anything else and you're on your own.
