### ISSUE TITLE
Generic Analog pH/EC Actions broken on AJAX-enabled interface

### ISSUE THREAD

**Issue by dookaloosy** [kizniche/Mycodo#1058]
### Describe the problem/bug

AJAX-enabled interface doesn't allow Actions to be executed. Clicking on the "Calibrate Slot" buttons don't appear to do anything.

### Versions:

 - Mycodo Version: 8.11.0 + master branch commit [8d46745](https://github.com/kizniche/Mycodo/commit/8d46745b8439abad903f49eb9da0e27756e8fdca)
 - Raspberry Pi Version: 3B
 - Raspbian OS Version: Linux raspberrypi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. Upgrade to master branch commit [8d46745](https://github.com/kizniche/Mycodo/commit/8d46745b8439abad903f49eb9da0e27756e8fdca)
2. Browse to Generic Analog pH/EC input.
3. Insert pH or EC probe in calibration solution and click on Calibrate Slot. An incomplete message pops up on the right:
`Success: Custom Button: Traceback (most recent call last): File "/home/pi/Mycodo/mycodo/mycodo_client.py", line 291, in custom_button controller_type, unique_id, button_id, args_dict, thread) File "/home/pi/Mycodo/env/lib/python3.7/site-packages/Pyro5/client.py", line 476, in call return self.send(self.name, args, kwargs) File "/home/pi/Mycodo/env/lib/python3.7/site-packages/Pyro5/client.py", line 211, in _pyroInvoke data = serializer.dumpsCall(objectId, methodname, vargs, kwargs) File "/home/pi/Mycodo/env/lib/python3.7/site-packages/Pyro5/serializers.py", line 276, in dumpsCall return serpent.dumps((obj, method, vargs, kwargs), module_in_classname=True) File "/home/pi/Mycodo/env/lib/python3.7/site-packages/serpent.py", line 69, in dumps return Serializer(indent, module_in_classname, bytes_repr).serialize(obj) File "/home/pi/Mycodo/env/lib/python3.7/site-packages/serpent.py", line 229, in serialize self._serialize(obj, out, 0) File "/home/pi/Mycodo/env/lib/python3.7/site-packages/serpent.py", line 255, in _serialize return self.dispatch[t](self, obj, out, level) File "/home/pi/Mycodo/env/lib/python3.7/site-packages/serpent.py", line 319, in ser_builtins_tuple serialize(elt, out, level + 1) File "/home/pi/Mycodo/env/lib/python3.7/site-packages/serpent.py", line 255, in _serialize return self.dispatch[t](self`
4. Notice that the setting doesn't "take" in the targeted calibration slot, as the previous calibration setting still remains even after a browser refresh.

### Expected behavior

The Calibrate Slot button should work as on non-AJAX interface.

### Screenshots

N/A

### Additional context

N/A

**Comment by kizniche** [comment]
That should fix custom actions for Inputs, Outputs, and Functions.
