### ISSUE TITLE
support MQTT publish ?

### ISSUE THREAD

**Issue by haidv1992** [kizniche/Mycodo#1066]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by haidv1992** [comment]
Currently I don't see mqtt publish support
, can I add it myself ? hope you can support the source material to add this feature

**Comment by kizniche** [comment]
Search "MQTT" at https://kizniche.github.io/Mycodo/

**Comment by haidv1992** [comment]
Thank you very much
