### ISSUE TITLE
Can i run this project on my macos use pycharm ide to custom widgets or alerts etc ? 

### ISSUE THREAD

**Issue by haidv1992** [kizniche/Mycodo#1069]
On raspberry some ide not smart to custom this project , can you help me some advice?
Thank master

**Comment by kizniche** [comment]
Are you asking if you can use Pycharm on Mac? I believe mac is a supported OS.

**Comment by haidv1992** [comment]
I mean can I run this project on masos to customize it directly instead of using raspi ?

**Comment by haidv1992** [comment]
https://github.com/kizniche/Mycodo/wiki/Mycodo-and-Docker
this tutorial

**Comment by haidv1992** [comment]
![image](https://user-images.githubusercontent.com/86423592/129465692-e34eb09f-1d0c-49b2-97bf-f38511318598.png)

**Comment by kizniche** [comment]
That wiki needs to be updated, since docker is now on the master branch. Notice the docker directory in the root of the repo.

**Comment by kizniche** [comment]
There's a readme in the docker directory with information
