### ISSUE TITLE
Widget back colour and size pb

### ISSUE THREAD

**Issue by pe2269** [kizniche/Mycodo#1080]
### Describe the problem/bug

Hi Kyle,

I upgrade my system to the V8.12.2 in order to fix the displayed widgets problems (it's works :))
But now i have some new issues :
 
                 1°) The back colour of the Solid and Angular Gauge widget remains white in the darkly theme i use.
                 2°) When I add in the same dashboard that the gauges widget, a graph widget, the back colour problem is fixed
                 3°) i must to save the widget after change in the size of the widget (maybe it's not a bug)                 

### Versions:

 - Mycodo Version: *v8.12.2
 - Raspberry Pi Version: 4 B 
 - Raspbian OS Version: 10 Buster

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. *[Go to...]*
2. *[Click on...]*
3. *[Scroll down to...]*
4. *[See error...]*
5. *[replace this list with your own text]*

### Expected behavior

*[A clear and concise description of what you expected to happen - replace this with your own text]*

### Screenshots

![Widget_Size_Colour_Pb](https://user-images.githubusercontent.com/85128895/131468935-7cd3ff26-33bc-4a16-b4a2-9366623012cb.PNG)

### Additional context

*[Anything that should be added to make it easier to address this issue - replace this with your own text]*

**Comment by pe2269** [comment]
Great it's working !!

**Comment by kizniche** [comment]
You can leave this open until the fix is released, otherwise it's likely someone else will open the same issue.
