### ISSUE TITLE
Jmespath Dependency Install ERROR

### ISSUE THREAD

**Issue by Muncslice** [kizniche/Mycodo#1085]
### Describe the problem/bug

*[Jmespath version cannot be found when installing the dependency for mqtt_paho_json]*

### Versions:

 - Mycodo Version: *[8.12.5]*
 - Raspberry Pi Version: *[4B]*
 - Raspbian OS Version: *[Buster Lite]*

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. *[Go to...]*
2. *[Click on...]*
3. *[Scroll down to...]*
4. *[See error...]*
5. *[replace this list with your own text]*

### Expected behavior

*[A clear and concise description of what you expected to happen - replace this with your own text]*

### Screenshots

*[
![image](https://user-images.githubusercontent.com/76022770/131896154-6bc6696c-4922-438c-a75c-dbbaae3da3c7.png)
]*

### Additional context

*[The Error as I see it is due to the requested Jmespath version being either unreleased and non existent at this present stage, the dependency install request originates from Mycodo/mycodo/inputs/mqtt_paho_json.py.

See below screenshot:

![image](https://user-images.githubusercontent.com/76022770/131897171-54bb0c9c-38b9-4aa0-bfba-dc20fb783535.png)

Changing the value from 'jmespath==0.10.1' to 'jmespath==0.10.0' which is the current latest release (correct me if i am wrong) fixes the issue and allows the dependency to install. 

See below screenshot:

![image](https://user-images.githubusercontent.com/76022770/131897528-f85895d2-78d6-4812-b0bc-f41f39d383ac.png)
]*

**Comment by kizniche** [comment]
Thanks for the bug report. I just committed a fix that will be available in the next release.
