### ISSUE TITLE
Install error  invalid user influxdb.influxdb

### ISSUE THREAD

**Issue by Chomski99** [kizniche/Mycodo#1093]

**Comment by Chomski99** [comment]
I have a clean raspberry pi os installed on virtualbox. I'm trying to install Mycodo which fails with an invalid user influxdb.influxdb 
[setup.log](https://github.com/kizniche/Mycodo/files/7217037/setup.log).

So far all I have tried it to reboot and and rerun the setup script again. I used the latest version of PI os and Mycodo. Can anyone shed some light on the failure please.

**Comment by kizniche** [comment]
Notice all the 404 errors installing packages. That's your issue.

**Comment by Chomski99** [comment]
Thanks for coming back to me. After logging the issue I upgraded the PI os in a new virtual machine and found that helped but I still got the error once I got in to Mycodo. I wan't sure if this was because it wasn't running on a real raspberry PI. Any thoughts?
