### ISSUE TITLE
Input MQTT can't accept the value 0 to disable the keep alive option

### ISSUE THREAD

**Issue by pe2269** [kizniche/Mycodo#1097]
Hi,
Input MQTT can't accept the value 0 to disable the keep alive option.
I try to do that because when my network reboot i do not receive anymore MQTT suscription via Mycodo and i search why
 (its looks like #1053 )

 - Mycodo Version: 8.12.6 
 - Raspbian OS Version: Buster

### Reproducibility

1. Input : Mycodo : MQTT Suscribe (Value\Payload)
2. put 0 in the keep alive box, in the custiom options in order to disable the keep alive

**Comment by kizniche** [comment]
I think you might be misinterpreting what the keepalive option is. Please refer to the [paho documentation](https://pypi.org/project/paho-mqtt/).
