### ISSUE TITLE
Incorrect Highstock dependency for gauge widgets

### ISSUE THREAD

**Issue by antoinechauveau** [kizniche/Mycodo#1100]
### Describe the problem/bug

Dependency installation for gauge widgets is not functional. Highstock is treated as a dependency, but only the base Highcharts package is installed.

Graph widgets on the other hand have proper support for Highstock installation. If we setup one such graph first, then gauges also work. 

### Versions:

 - Mycodo Version: 8.12.6
 - Raspberry Pi Version: N/A (amd64 virtual machine)
 - Raspbian OS Version: N/A (Ubuntu 20.04)

### Reproducibility

1. Install fresh Mycodo
2. Set up any input (ex. RAM measurement)
3. Click on "Data" -> "Default"
4. Click "Add Dashboard Widget" -> "Gauge (Solid) [Highcharts]"
5. Fill minimum details (ex. RAM input above) and click "Create"
6. Click "Install All Dependencies"
7. Wait for "Dependency install complete"
8. Repeat steps 3 to 5, "highstock-9.1.2.js" is still reported as missing dependency

### Expected behavior

At step 8, the gauge widget should be installed on the dashboard and functional.

### Additional context

Dependency installation became inconsistent with commit https://github.com/kizniche/Mycodo/commit/6013f75da908b76a8eb97f94b2c2a4d11a70ac94. Gauge widgets were made to depend on Highstock instead of Highcharts, but the dependency installation procedure for these widgets still downloads only Highcharts through "wget". Also the widgets' names still list "Highcharts".

Not sure what is the attempted design. Does Mycodo try to install minimal dependencies (in which case the Highstock dependency is superfluous for gauges), or does it try to standardize on Highstock whether using gauges or graphs?

**Comment by kizniche** [comment]
This issue has been mentioned on **DIY Automation Forum**. There might be relevant details there:

https://forum.kylegabriel.com/t/unmet-dependencies-highstock-9-1-2-js-data-9-1-2-js-exporting-9-1-2-js-export-data-9-1-2-js-offline-exporting-9-1-2-js/419/2
