### ISSUE TITLE
Your connection is not private NET::ERR_CERT_INVALID

### ISSUE THREAD

**Issue by emreakcadag** [kizniche/Mycodo#1102]
Hello,

I got an error after setup. I am trying to connect my rpi ip adress then I got this error: ERR_CERT_INVALID.

After I trust the certificate, Bad Gateway Error appear.

Also while setup script running, 
`Could not connect to http://localhost. Waiting 60 seconds then trying again (up to 10 times)...`
I got this message.

this is my error log after setup done: `Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     self.callable = self.load()
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     return self.load_wsgiapp()
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     return util.import_app(self.app_uri)
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     mod = importlib.import_module(module)
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     return _bootstrap._gcd_import(name[level:], package, level)
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/mycodo/start_flask_ui.py", line 11, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     from mycodo.mycodo_flask.app import create_app
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/mycodo/mycodo_flask/app.py", line 24, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     from mycodo.databases.models import Misc
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/mycodo/databases/__init__.py", line 7, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     from mycodo.mycodo_flask.extensions import db
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/mycodo/mycodo_flask/extensions.py", line 13, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     from flask_marshmallow import Marshmallow  # must be imported after SQLAlchemy
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_marshmallow/__init__.py", line 24, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     from . import sqla
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_marshmallow/sqla.py", line 13, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     import marshmallow_sqlalchemy as msqla
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/marshmallow_sqlalchemy/__init__.py", line 1, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     from .schema import (
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/marshmallow_sqlalchemy/schema.py", line 6, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     from .convert import ModelConverter
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/marshmallow_sqlalchemy/convert.py", line 9, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     from sqlalchemy.dialects import postgresql, mysql, mssql
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/__init__.py", line 57, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     from . import asyncmy  # noqa
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 175, in <module>
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     class AsyncAdapt_asyncmy_connection(AdaptedConnection):
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 184, in AsyncAdapt_asyncmy_connection
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     @asynccontextmanager
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/util/concurrency.py", line 63, in asynccontextmanager
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     _not_implemented()
Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/util/concurrency.py", line 38, in _not_implemented
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     "the greenlet library is required to use this function."
Oct 18 13:55:04 raspberrypi gunicorn[4360]: ValueError: the greenlet library is required to use this function.
Oct 18 13:55:04 raspberrypi gunicorn[4360]: [2021-10-18 13:55:04 +0100] [4372] [INFO] Worker exiting (pid: 4372)
Oct 18 13:55:04 raspberrypi gunicorn[4360]: [2021-10-18 13:55:04 +0100] [4360] [INFO] Shutting down: Master
Oct 18 13:55:04 raspberrypi gunicorn[4360]: [2021-10-18 13:55:04 +0100] [4360] [INFO] Reason: Worker failed to boot.
Oct 18 13:55:05 raspberrypi systemd[1]: mycodoflask.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Oct 18 13:55:05 raspberrypi systemd[1]: mycodoflask.service: Failed with result 'exit-code'.`

### key point of the error: 
`Oct 18 13:55:04 raspberrypi gunicorn[4360]:   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/util/concurrency.py", line 38, in _not_implemented
Oct 18 13:55:04 raspberrypi gunicorn[4360]:     "the greenlet library is required to use this function."
Oct 18 13:55:04 raspberrypi gunicorn[4360]: ValueError: the greenlet library is required to use this function.`

### Versions:

 - Mycodo Version: 8.12.6
 - Raspberry Pi Version: 4B - 2018
 - Raspbian OS Version: 2021.05.07 buster lite
 
 Thanks.

**Comment by Landsailor** [comment]
I have the same problem with 8.12.9. It was a completely fresh, by the book install on about Feb 2, 2022. 

Neither Chrome 97.0.4692.99 on MacOS 12.2 nor my Android phone will not load it. I have to use Safari or disable HTTPS.

![Screen Shot 2022-02-08 at 2 31 15 PM](https://user-images.githubusercontent.com/1393119/153086687-3aad1f9b-aec8-4680-bf1d-b7e84e404996.png)

**Comment by kizniche** [comment]
It's expected behavior. This is what happens with self-signed certificates and you need to read the documentation for your browser to allow the certificate. For some reason macs disable the button clearly visible to windows/Linux browsers "proceed anyway".
