### ISSUE TITLE
Cant see past 24 hours on graph chart

### ISSUE THREAD

**Issue by Time4420** [kizniche/Mycodo#111]
Hello Chris, first let me tell you i use your application for some time now installed on RasperryPi 3B (raspbian) and want to say that you are doing a great job.
I have one issue that on the graph chart i cannot go back past 24hr, i am using DHT sensors.
Also it loses connectivity after approx 5-8 hours of working and only by shutting the power off and on it connects to the wifi router.

**Comment by kizniche** [comment]
I meant to respond to this sooner, but saw you closed it. Have you been able to resolve your issues?

**Comment by Time4420** [comment]
I kinda resolved it, what i did is expanding the x-Axis, small problem is when i put more then 10k it is very slow and takes time to show and Pi gets really hot (Obviously because he pulls logs, no? i am a beginner), i would be happy if there was an option to look at history logs even a year back and compare.
Currently i have 4 temp/humidity sensors and planning to add a small motor and float/water sensor.

**Comment by Time4420** [comment]
Also the Pi looses connection to the router that i did not resolved yet, i think putting a command that auto restarts the pi.
