### ISSUE TITLE
Backup Restore, same version wrong filename?

### ISSUE THREAD

**Issue by SingularityJ** [kizniche/Mycodo#1129]
Hi, bit of a noob here, I am currently having problems loading a backup file. Both versions are 8.12.9
the error I am getting is :
Error: Import Settings: Invalid file name: Mycodo_Backup_2022-01-02_00-05-25-8.12.9_raspberrypi.zip: 2022-01-02 != Settings
Error: Import Settings: Correct format is: Mycodo_MYCODOVERSION_Settings_DBVERSION_HOST_DATETIME.zip
Error: An error occurred during the settings database import.

is this as simple as renaming? if so what would I rename to? dbversion and host I don't quite understand
the backup does not appear in the web ui if I transfer to var/mycodo-backups, and loading through the import/export gives the above error.
I did manage to backup manualy with: sudo mycodo-commands backup-restore /var/Mycodo-backups/Mycodo_Backup_2022-01-02_00-05-25-8.12.9

however there was an unspecified error and daemon is not running and no sensors are working. I did notice none of the required dependencies are installed and have manually updated some just to see if it helped, I decided pretty quick it would be easier to just start fresh (it was a pretty simple setup so far)
I would like to use the backup to clone the system once it is finished so it would be great to know where I went wrong.

**Comment by kizniche** [comment]
You are attempting to import a backup archive (Backup Page) as a settings archive (Import/Export Page). You can only import a settngs arichive that was exported on the Inport/Export page. The error you are receiving is correct .You should not rename any files to attempt to cirumvent the checks to ensure the proper files are being used.
