### ISSUE TITLE
Requirement of Pull-up or Pull-down resistor

### ISSUE THREAD

**Issue by vipul-khatana** [kizniche/Mycodo#1131]
According to your blog on building an Automated Hydroponic System, the circuit diagram shows the resistors for a float switch/sensor. However we are not using any float switch, as we want to do a simplified version of the experiment where we just automate the pH component. 

Do we still need to use pull-up or pull-down resistors somewhere? I read that each of the SDA and SCL pin of the pump need to be connected to a pull-up resistor (preferably 4.7k Ohms).

**Comment by kizniche** [comment]
Please use the forum or discord for questions unrelated to the software. This is an issue tracker for problems found with the software.

Both SDA and SCL need at least 1 pull-up resistor each. Refer to your hardware datasheets/manuals to determine if they're needed. Without providing what hardware you're using, it's impossible to provide further guidance.
