### ISSUE TITLE
Basic Temperature Regulation

### ISSUE THREAD

**Issue by sporestudy** [kizniche/Mycodo#1136]
Everything is up to date. this issue has not been covered which i assume is because its such a "noob" question.

I have been using Mycodo to track temperatures with ease and success for months. (Ds18b20's)
I not copied the box construction with relays in order to attach my heaters to the Mycodo system.

Created an output for GPIO On/Off, pin 24. 
I can manually turn the relay on and off with the output, so i know the wiring is good.

I then attempt to set the function to a simple PID.
THE PROBLEM:  The PID keeps turning the relay on and off over and over once it properly activates.
This problem eventually settles itself, but im worried the fluctuations will cause issues with my heaters.

Here are my PID Settings. and graph.
![Screenshot (59)](https://user-images.githubusercontent.com/97328094/148635116-cabcd8bf-920d-4ef5-b483-93c2a2a763db.png)
![Screenshot (60)](https://user-images.githubusercontent.com/97328094/148635126-e46d951a-d754-48fa-b60d-396b6c06e491.png)

**Comment by kizniche** [comment]
This is a software issue tracker, not a place for general questions. There is a forum and a discord server for general questions.
