### ISSUE TITLE
How to configure the reverse proxy to use other services on the same system along with mycodo?

### ISSUE THREAD

**Issue by lalebarde** [kizniche/Mycodo#1143]
Hi,

I have mycodo working on a Raspberry Pi. **I would like to add another service on the same system**. I know nginx is deployed along with mycodo in the standard installation, and that **nginx can be used as a reverse proxy**. Then I should be able to deploy other services easily.

I figure out this is certainly not a specific mycodo issue. I have three choices: use a specific port or subdomain or URI subfolder for each service. I would prefer the last.

Could you please provide some tips for it?

**Comment by kizniche** [comment]
Sorry, this isn't in my realm of expertise.
