### ISSUE TITLE
Measuring amount of water and electricity

### ISSUE THREAD

**Issue by garudaonekh** [kizniche/Mycodo#1158]
Hi,
I need to measure the amount of water when I turn on a relay(Pump). I have a flow meter(pulse counter) and a pump(output). My question is how to measure the amount of water each time of turn on/off the pump. What complicated the matter is I have 5 pump connected with the same flow meter.

Any suggestion?

**Comment by kizniche** [comment]
You can use the Generic Pump Output and calibrate them to the flow, then a volume and total volume is stored whenever the output is turned on/off.

**Comment by garudaonekh** [comment]
But we are using flow sensor, so we need to bind pump and sensor

**Comment by kizniche** [comment]
You would have to create an output to do that, however you will always run into an issue if you ever have more than one pump on at a time.

**Comment by garudaonekh** [comment]
multiple pump but they are open sequentially. How about custom function? Can we use that instead of writing a new output?

**Comment by kizniche** [comment]
no, an output is the mot appropriate.

**Comment by garudaonekh** [comment]
Ok thanks.
