### ISSUE TITLE
MH-Z19B: CO2 Sensor Error

### ISSUE THREAD

**Issue by ChrisDavidRucker** [kizniche/Mycodo#1162]
### Describe the problem/bug

*MH-Z19B CO2 sensor error. Specifically  I was successful in reading the sensor from CLI using a python script to confirm the sensor is functional.*
![image](https://user-images.githubusercontent.com/81479977/158465749-0c1dcb41-7170-4519-975a-deb17fadc99c.png)

### Versions:

 - Mycodo Version: *8.12.9*
 - Raspberry Pi Version: *4B*
 - Raspbian OS Version: *Bullseye*

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. *Connect sensor.*
2. *Configure sensor.*
3. *Activate sensor.*
4. *Check live measurements page.*
5. *Check daemon log to confirm its not working.*

### Expected behavior

*The sensor to show up in the "Live Measurements" page once correctly configured.*

### Screenshots
![image](https://user-images.githubusercontent.com/81479977/158466863-20d7438e-a77a-4fd1-8d65-8507d68e6e93.png)
*![image](https://user-images.githubusercontent.com/81479977/158464987-2260d0e3-7ba3-4878-9e45-c87ab322c4c5.png)*

### Additional context (Daemon log)

*ERROR - mycodo.controllers.controller_input_b1cf440c - initialize_variables() Exception: Write timeout
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/controllers/base_controller.py", line 74, in run
    self.initialize_variables()
  File "/var/mycodo-root/mycodo/controllers/controller_input.py", line 317, in initialize_variables
    self.measure_input = input_loaded.InputModule(self.input_dev)
  File "/home/pi/Mycodo/mycodo/inputs/mh_z19b.py", line 130, in __init__
    self.initialize_input()
  File "/home/pi/Mycodo/mycodo/inputs/mh_z19b.py", line 149, in initialize_input
    self.abcon()
  File "/home/pi/Mycodo/mycodo/inputs/mh_z19b.py", line 205, in abcon
    self.ser.write(bytearray([0xff, 0x01, 0x79, 0xa0, 0x00, 0x00, 0x00, 0x00, 0xe6]))
  File "/var/mycodo-root/env/lib/python3.9/site-packages/serial/serialposix.py", line 636, in write
    raise SerialTimeoutException('Write timeout')
serial.serialutil.SerialTimeoutException: Write timeout*

**Comment by ChrisDavidRucker** [comment]
Solution was to disable Bluetooth.

[https://www.abelectronics.co.uk/kb/article/1035/serial-port-setup-in-raspberry-pi-os](url)

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mh-z19b-reading-problem/661/11

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mh-z19b-detection-issue/1024/4
