### ISSUE TITLE
Timelapse - Not taking pictures after resuming past next capture date

### ISSUE THREAD

**Issue by jamjamjakjak** [kizniche/Mycodo#1163]
Hello,

Many thanks to the founder(s) and to everyone who has contributed to this project. It is simply a piece of art!
I have a complicated setup and it is all functioning as intended.

I'm having an issue where Im trying to pause the timelapse during the dark period and resume in the morning.
It seems to get stuck and I think it may have something to do with the next capture date.
Its configured to take a picture every 2 hours(7200 seconds) however after many hours during the night paused, it is well past its 'Next Capture Date' and maybe waiting for this timestamp in the past to come again, causing it to fail to resume. 
Example:
![pic](https://user-images.githubusercontent.com/101949527/159137257-bd5277ce-0916-4212-9658-e4d57e55f6fb.png)

Perhaps there is a way to programmically set the Next Capture Date manually?

Many thanks. hope this helps.

**Comment by kizniche** [comment]
Thanks for the big report. I'll should have a fix shortly.

**Comment by kizniche** [comment]
I don't see anything in the code that would prevent timelapses from working after a pause. Are you sure you're not out of disk space or something preventing photos form being captured? Any errors in the dameon log?

**Comment by kizniche** [comment]
Your screenshot also indicates the daemon is not running, so that's likely your issue.

**Comment by kizniche** [comment]
I was not able to replicate your issue. My time-lapse photo acquisition resumed following unpausing. You have some sort of issue separate from the time-lapse functionality.

**Comment by kizniche** [comment]
If you have any additionla information, feel free to reopen

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/timelapse-resume-not-working/1012/3

**Comment by kizniche** [comment]
With some additional information on the forum, I was able to find and fix this issue with commit https://github.com/kizniche/Mycodo/commit/ed333330322202623b60c5b3fe25ade7a628dcf1.

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mycodo-v8-14-0-release/1136/1
