### ISSUE TITLE
Unable to use a function output as an input on a PID Controller, unless i remove this piece of validation

### ISSUE THREAD

**Issue by huntj88** [kizniche/Mycodo#1165]
### Describe the problem/bug

PID controllers include functions in the drop down menu, but it errors out with "A valid Measurement is required". If i remove this piece of validation code everything works as expected

https://github.com/huntj88/Mycodo/commit/9e6317a5f41f3081fd87a1a5d1c754ef993e3f42

**Comment by kizniche** [comment]
Thanks for the bug report. I just pushed a fix.

**Comment by huntj88** [comment]
Just tested, works for me :+1:

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mycodo-v8-13-0-release/820/1
