### ISSUE TITLE
Trigger Edge timer not working

### ISSUE THREAD

**Issue by Tree61** [kizniche/Mycodo#1171]
STOP right now, and please first look to see if the issue you're about to submit is already an open or recently closed issue at https://github.com/kizniche/Mycodo/issues

Please DO NOT OPEN AN ISSUE:

 - If your Mycodo version is not the latest release version, please update your device before submitting your issue (unless your issue is related to not being able to upgrade). Your problem might already be solved.

 - If your issue has been addressed before. If you have any new information that may aid in solving the issue, post it in the issue that already exists.

If you are going to post a new issue, next read How to Write a Good Bug Report at https://forum.radicaldiy.com/t/how-to-write-a-good-bug-report/71

Please complete as many of the sections below, if applicable, to provide the most information that may help with investigating your issue. Replace the text in brackets with your own text describing the issue. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help those providing assistance by reducing the time required to help you.

### Describe the problem/bug

*[A clear and concise description of what you were trying to do and what the problem/bug is - replace this with your own text]*

Using GPIO 2 switched input via external pull up resistor arrangement
to edge trigger output GPIO 3 externally wired to an output relay
edge trigger duration tested with 0, 5 and 10sec duration
output just raises and falls when observed with a voltage meter on GPIO 3 ie no time on observed 
live data confirms GPIO 2 state change however the edge trigger input does not change state
forcing relay out also works
changed de bounce settings 50-150msec same result

### Versions:

 - Mycodo Version: *[e.g. 8.0.3]* latest
 - Raspberry Pi Version: *[e.g. 3B+]* 4
 - Raspbian OS Version: *[e.g. Buster Lite]* buster

### Reproducibility yes repeatable result many times

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. *[Go to...]* refer above
2. *[Click on...]*
3. *[Scroll down to...]*
4. *[See error...]*
5. *[replace this list with your own text]*

### Expected behavior - Should observe relay output staying high for set duration period

*[A clear and concise description of what you expected to happen - replace this with your own text]*

### Screenshots

*[If applicable, add screenshots to help explain your problem - replace this with your own text]*

### Additional context

*[Anything that should be added to make it easier to address this issue - replace this with your own text]*

**Comment by Tree61** [comment]
Also tried configuring trigger timer function no success with this either
screen shots of configuration attache
![4-9-22 GPIO input cfg](https://user-images.githubusercontent.com/102574253/162554288-357c2dc9-eb46-475a-902e-fc602ceeba42.jpeg)
![9-4-22 Edge trigger Function cfg](https://user-images.githubusercontent.com/102574253/162554297-ec1353f8-5653-400b-b4ec-81e8c74fc76d.jpeg)
![9-4-22 Function cfg](https://user-images.githubusercontent.com/102574253/162554300-3ec7cacf-659d-4ea2-9181-3f3091b08264.jpeg)
![9-4-22 GPIO Edge cfg](https://user-images.githubusercontent.com/102574253/162554304-ec635a46-603e-483b-97ba-250e40aa4f93.jpeg)
![9-4-22 GPIO output cfg 2](https://user-images.githubusercontent.com/102574253/162554311-ad6d1042-3c65-43d0-9ffc-89e8d6b0836b.jpeg)
![9-4-22 GPIO output cfg](https://user-images.githubusercontent.com/102574253/162554313-7915cf3f-c9fd-4819-afdf-e8981d9cf803.jpeg)
![9-4-22 GPIO State cfg](https://user-images.githubusercontent.com/102574253/162554316-953710c0-f53b-4353-ae90-68dc5f287a5b.jpeg)
d

**Comment by kizniche** [comment]
I found an issue with the Edge Input storing measurements which I just committed a fix for, but I didn't find an issue with the Edge Trigger. I tested as you have done it worked for me.

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mycodo-v8-13-0-release/820/12
