### ISSUE TITLE
LCD no longer works after update 8.13.0

### ISSUE THREAD

**Issue by ryar27** [kizniche/Mycodo#1174]
Why remove working LCD Controllers functionality to force them to be added as a function?  

Now:
 - ERROR - mycodo.function.display_generic_lcd_20x4_i2c_28a3f76e - LCD not set up

How to set up?  I2C address matches, LCD no longer works....  Why fix what isn't broken?  Details are not in manual.  Updating was a mistake.

**Comment by kizniche** [comment]
No one is forcing you to do anything. You have the ability to downgrade back to the prior version.
