### ISSUE TITLE
PCF8574 I/0 no longer works after update

### ISSUE THREAD

**Issue by Matteo7S** [kizniche/Mycodo#1175]
### Describe the problem/bug

PCF8574 I/0 not works after last update 8.13.7

### Versions:

 - Mycodo Version: 8.13.7
 - Raspberry Pi Version: 3B+
 - Raspbian OS Version: Linux hydroberry 5.10.17-v7+

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. Setup -> output -> [I2C] On/Off: PCF8574 8-Channel I/O Expander (smbus2)
2. Click the on button, it shows success message, the row backgroung become green but relè doesn't switch on

### Additional context

just update to last version, I tried the PCF8574 8-Channe peristaltic pumps and it works

Thanks in advice

**Comment by kizniche** [comment]
Thanks for the bug report. I just reverted the changes, which will be available in the next release.

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/possible-upgrade-issue-pcf8574-i2c-smbus-not-triggering-anymore/861/2

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mycodo-v8-13-0-release/820/12
