### ISSUE TITLE
Graph Not Loading 8.13.7

### ISSUE THREAD

**Issue by raptortalon** [kizniche/Mycodo#1179]
### Describe the problem/bug

Graph synch does not display on a dashboard.

### Versions:

- Mycodo Version: 8.13.7
- NVIDIA Jetson Nano (this basically just works).
- Python 3.6.9

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

Add a synch highstock graph with a single input on a new dashboard.   Load the graph, the graph will not display and will exist but be blank.  The graph does load as an asynch graph with the same sensor and the data is available in the live view.

Note I saw some python dependency issues for flask on install also and needed to install a number of these by hand but not sure this is relevant.  There are no console errors in the browser (beside missing map files) which is Chrome; I also tried on firefox, also the same result.   There was a separate error in SSL mode however this problem occurs in both http and https.

The graph border is displayed however the content is missing.  I reverted to 8.12.9 and the problem was not present.   

### Expected behavior

Display of data on a graph from a sensor.

**Comment by kizniche** [comment]
If it was working on the same system for a recent previous version, it's likely an issue with your upgrade. There's no way to diagnose the issue without an upgrade log, but even with that you mentioned you modified your system since then, so three likely now exist other confounding variables.

**Comment by raptortalon** [comment]
I'll see, the potential suspects are 3.6 vs 3.8 python, and something with
babel.
