### ISSUE TITLE
I2C Bus will only recognize parasitotic pumps 

### ISSUE THREAD

**Issue by mdschoff** [kizniche/Mycodo#1193]
Here is what I have. My EC and pH sensors are 30-33. They were recognized last night but stopped sometime overnight. I have restarted the system but through a hard and soft reset. How can I get these sensors recognized again?

I2C Bus 1: i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- 34 35 36 37 -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --

**Comment by kizniche** [comment]
To properly diagnose an issue, disconnect everything, then install one device at a time on the shortest wires you can.
