### ISSUE TITLE
Conditional Statement Pylint Warning

### ISSUE THREAD

**Issue by mdschoff** [kizniche/Mycodo#1194]
After editing my pH and EC variables in the conditional statement and saving them, I keep getting a warning that Pylint is returning these messages. Is this something that will affect the automation of dosage to control the pH and EC values? If so how do I go about fixing this issue?

![image](https://user-images.githubusercontent.com/105743372/169101759-e96e5b36-f389-4ee1-8425-2c5f63db6290.png)

**Comment by kizniche** [comment]
It's a warning, and the pylint return status is displayed at the top of the Conditional. Warnings are not the same as Errors, since they are of lesser severity. You need to view the pylint output to determine if the code you saved is valid or not.

**Comment by kizniche** [comment]
It sounds like you're not running the latest version of Mycodo. If you are running the latest version, please attach a screenshot of the missing Conditional Status and the entire top of the config page, following a successful save.

**Comment by kizniche** [comment]
I see both the pylint output that appears at the top of the Conditional Controller config page as well as the Conditional Status field. I'm not sure what you mean by them not being there.

**Comment by mdschoff** [comment]
Sorry, I just didn't know if there was supposed to be a value within the conditional status part and I am unsure what the pylint output is within the code.

**Comment by kizniche** [comment]
There is a default value in the Status text field, but it looks like you deleted it.
The pylint output shows the entire generated class and the pylint score/issues at the bottom.

**Comment by mdschoff** [comment]
I see. I don't remember where I got the conditional code. Is there a master code I can copy and redo my variable assignment? 

Sorry for all the questions. This conditional statement I think is the only thing between me and the completed system.

**Comment by kizniche** [comment]
This is the pH/EC Conditional setup that you should use, if you're not familiar with building your own code: https://kylegabriel.com/projects/2020/06/automated-hydroponic-system-build.html#Electrical_Conductivity_and_pH_Regulation
