### ISSUE TITLE
Improve visual separation between inputs/outputs in conditional controlers to avoid confusion

### ISSUE THREAD

**Issue by lalebarde** [kizniche/Mycodo#1204]
After a first error of mine mixing output IDs with wrong output like here in red:

![image](https://user-images.githubusercontent.com/3611049/174467593-5d6f937a-a653-4c4c-aff3-0bb172e8ffe2.png)

I still have difficulties to read correctly the outputs like I should in green, the wrong red reading is more "natural" to me.

It would be nice to improve I/O visual separation in the layout.

**Comment by Mondgans** [comment]
I can confirm this. 
For Inputs the ID is below the dropdown field. And for the Outputs the ID is above the dropdown field.
This is definitely confusing.

**Comment by kizniche** [comment]
Fixed in https://github.com/kizniche/Mycodo/commit/60fb718b78aa5a0a880a0ae21d47cd633055cc65

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mycodo-v8-14-0-release/1136/1
