### ISSUE TITLE
Generate timelapse not working with custom image path

### ISSUE THREAD

**Issue by Mondgans** [kizniche/Mycodo#1205]
I use custom image paths in camera settings.
When pressing the [Generate] the Images are expected to be in the default folder.

**Comment by kizniche** [comment]
Thanks for the bug report. I'll take a look at this.

**Comment by kizniche** [comment]
I made a fix, but it's currently untested

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mycodo-v8-14-0-release/1136/1
