### ISSUE TITLE
DHT22 not working

### ISSUE THREAD

**Issue by Tommynator062** [kizniche/Mycodo#1211]
I'm using the last version of mycodo with a raspberries 3, and I'm having issue connecting my DHT22. Ive install pigpiod and when I'm sending: <<sudo systemctl enable pigpiod>> I receive:  <<Failed to enable unit: Refusing to operate on alias name or linked unit file: pigpiod.service>> . Ive tried to enable remote GPIO pin, purge pigpiod and reinstall it. Can you help me?

**Comment by kizniche** [comment]
No response in over a month. Closing.
