### ISSUE TITLE
Does Mycodo have to be installed on a Raspberry Pi?

### ISSUE THREAD

**Issue by hefeystus** [kizniche/Mycodo#1214]
With the current shortage in Pi production and crazy markups by scalpers - could I run Mycodo on different hardware?

**Comment by kizniche** [comment]
It can be installed on any Debian-based Linux OS, not just Raspberry Pi OS for Raspberry Pis.

**Comment by garudaonekh** [comment]
At my place, cost of Raspberry pi 3 is 100$+ now. I used to try this on Pi zero but it's way to slow to run Mycodo. I have two pieces of Raspbery Pi Zero 2 but haven't tried that yet, maybe it's enough to run mycodo smoothly.
@hefeystus what kind of board do you have in mind?
