### ISSUE TITLE
Conditional function - Undefined variable 'timeout'

### ISSUE THREAD

**Issue by JulienCheny** [kizniche/Mycodo#1220]
### Description
Hi,
I can't execute any function there is an error for all of them. It say that the "timeout" variable isn't defined.
This bug happens even to the default program.

### Versions:

 - Mycodo Version: 8.14.0
 - Raspberry Pi Version: 4B
 - Raspbian OS Version: Debian GNU/Linux 11 (bullseye)

### Reproducibility

1. Go to Function
2. Add "Conditional Controller"
3. Open the Configure panel of the function just added
4. Save the default program

### Expected behavior

The timeout variable should be took from the "Timeout (seconds)" edit field
And initialized before this : 
control = DaemonControl(pyro_timeout={timeout})

### Error

Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/controllers/base_controller.py", line 72, in run
    self.initialize_variables()
  File "/var/mycodo-root/mycodo/controllers/controller_conditional.py", line 133, in initialize_variables
    spec.loader.exec_module(conditional_run)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/Mycodo/mycodo/user_python_code/conditional_861387d0-33d5-482d-ac0e-c904716674e0.py", line 6, in <module>
    control = DaemonControl(pyro_timeout={timeout})
NameError: name 'timeout' is not defined

## Generated program
  1: import os
  2: import sys
  3: sys.path.append(os.path.abspath('/var/mycodo-root'))
  4: from mycodo.controllers.base_conditional import AbstractConditional
  5: from mycodo.mycodo_client import DaemonControl
  6: control = DaemonControl(pyro_timeout={timeout})
  7: ...

**Comment by kizniche** [comment]
Fix released. Thanks for the bug report.

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mycodo-v8-14-0-release/1136/2
