### ISSUE TITLE
Turkish Language Support Add

### ISSUE THREAD

**Issue by ramazansancar** [kizniche/Mycodo#1222]
**Is your feature request related to a problem? Please describe.**
I can do the Turkish translation for you.

**Describe the solution you'd like**
[I can do the Turkish translation for you.](http://translate.kylegabriel.com:8080/projects/mycodo/)
Language can be added for translation.

**Describe alternatives you've considered**

**Additional context**

**Comment by kizniche** [comment]
Hi. That is great. You can find information on how to create a new translation file at https://github.com/kizniche/Mycodo/wiki/Translations

**Comment by ramazansancar** [comment]
#1223 added :)

**Comment by kizniche** [comment]
Thanks! I'll see about adding it.

**Comment by kizniche** [comment]
I just committed the translation file, so it now appears in [weblate](http://translate.kylegabriel.com:8080/projects/mycodo/master/), currently only 7% complete, Weblate makes it quick and easy to update translations, if you wanted to increase the coverage.

![weblate](http://translate.kylegabriel.com:8080/widgets/mycodo/-/multi-auto.svg)
