### ISSUE TITLE
Just a typo, but might break code

### ISSUE THREAD

**Issue by summa-code** [kizniche/Mycodo#1248]
Latest code, it is the sample for Conditional function code 

E1101: Instance of 'ConditionalRun' has no 'loop_count' member (no-member)

I think that it is run_loop_count

```# Example code to provide a return status for other controllers and widgets.
status_dict = {
    'string_status': f"The controller has looped {self.loop_count} times at {datetime.now()}",
    'loop_count': self.loop_count,
    'error': []
}
return status_dict```

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mycodo-v8-15-0-release/1362/1
