### ISSUE TITLE
pylint is taking way too much time in Analyzing the code

### ISSUE THREAD

**Issue by summa-code** [kizniche/Mycodo#1249]
On edge devices with low processing powers, pylint is taking way too much time. Is there a way to configure this such that I can enable/disable warnings and others ? I think that Errors are the most important thing for edge devices.

Not sure if I can contribute, but is there a specific place in the code that I can try and play around a little bit ?

**Comment by kizniche** [comment]
I agree, a status message indicating it's processing is also a good idea. I'll see if I can implement it soon.

**Comment by kizniche** [comment]
I just added the option to Analyze with Pylint to modules that use Python code (Inputs, Outputs, and Conditional Functions) in https://github.com/kizniche/Mycodo/commit/705664fe27eeb194c97d37d014da363895a1247b.

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mycodo-v8-15-0-release/1362/1
