### ISSUE TITLE
Honeywell HIH6130 temperature/humidity sensor

### ISSUE THREAD

**Issue by atlas55x** [kizniche/Mycodo#1252]
Hi Kizniche,

I have a honeywell HIH6130-based sensor from Sparkfun for both temp/relative humidity. Is there a similar i2C input that will work? I would love to be able to get it to work, but it is outside of my capabilities. If it's not something that is easy, I will purchase an already-supported sensor. I am 3 days into Mycodo and it is so cool!

Thanks!
-Atlas55x

https://www.amazon.com/Humidity-Temperature-Sensor-Breakout-HIH6130/dp/B00L8EB7YK

**Comment by kizniche** [comment]
This doesn't seem to be a product that Sparkfun still supports. I'd recommend finding something that they're still selling. There are many temperature/humidity sensors supported by Mycodo that are currently still for sale by the manufacturer or breakout board-makers.

**Comment by atlas55x** [comment]
Thanks for the fast response! Adafruit Sensiron SHT31-D is on the way. Happy Holidays.
