### ISSUE TITLE
Sensor addition: LiFePO4wered/Pi

### ISSUE THREAD

**Issue by montreuilg** [kizniche/Mycodo#127]
I'll also add this one, to be used as an UPS.

[LiFePO4wered](http://lifepo4wered.com/lifepo4wered-pi.html)

«extremely useful add-on for the Raspberry Pi single board computer: a full-featured battery power system / UPS / power manager.»

**Comment by kizniche** [comment]
Do you have one to test?

What do you propose be added for measuring? I see voltage may be the only measure.

**Comment by montreuilg** [comment]
I'm supposed to get it early week. USB charge voltage and output voltage will be enough.

**Comment by MurderLabz** [comment]
montreuilg - Did you ever get your LiFePO4wered? I  like you can use 18650 batt's. I look into getting one of these(or a clone)

**Comment by kizniche** [comment]
How long can it keep the Pi running after a power loss?

**Comment by MurderLabz** [comment]
I don't see any math penned out. But a 18650 Batt 3500mah 3.7v stepped up to 5v at 2.5 Amps (Max load) with -20% efficiency loss.... Rough guess over 1 hr? At idle I would think about 1/2 a day.

Here is the project blog https://hackaday.io/project/18041/logs

**Comment by kizniche** [comment]
Did you ever receive this and still have interest in adding it as a sensor in Mycodo?
