### ISSUE TITLE
dep libcamera-apps-lite even libcamera-apps is installed

### ISSUE THREAD

**Issue by fundix** [kizniche/Mycodo#1270]
I have the libcamera-apps library installed on my system but Mycodo requires libcamera-apps-lite. This is a problem because then the camera preview window doesn't work. So far I got around this by installing the libcamera-apps-lite depency, adding the camera and then removing libcamera-apps-lite again and installing libcamera-apps.

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/mycodo-v8-15-0-release/1362/10

**Comment by kizniche** [comment]
Thanks for the feedback. I agree it makes more sense to use the non-lite version. This change is in the latest release (v8.15.5).
