### ISSUE TITLE
arm64 Influxdb 2.x selection on install 

### ISSUE THREAD

**Issue by K1rdro** [kizniche/Mycodo#1276]
System: Rpi 3B+
OS: raspios bullseye arm64 lite

During install if you select "Install Influxdb 2.x", the install script responds with ""You have chosen not to install Influxdb." etc. The issue looks to be the [value assigned to that selection in the setup.sh file](https://github.com/kizniche/Mycodo/blob/master/install/setup.sh#L118) is being set to 0, which gives a [confusing response](https://github.com/kizniche/Mycodo/blob/master/install/setup.sh#L136) (Should this message trigger off of a selection value of 2 instead?). It looks like the correct version of [influx is still installed](https://github.com/kizniche/Mycodo/blob/master/install/setup.sh#L189). 

Thanks for putting together such a stellar project! It's a huge upgrade over the basic arduino controller I have been using!

**Comment by kizniche** [comment]
Thanks for the bug report. This is just an erroneous text response. It doesn't affect the install at all.
