### ISSUE TITLE
Sensors correction feature

### ISSUE THREAD

**Issue by wingsergey** [kizniche/Mycodo#1289]
**Is your feature request related to a problem? Please describe.**
For example:
I have sensor AHT20 and it shows temperature 15C. Also I have some more precise sensor that shows temperature 18C.
How I can add correction value for my AHT20 sensor measurements?

**Describe the solution you'd like**
In sensor settings page have extra field where I can set correction value like a number or like formula (for not constant correction), for example add 10% to measured value.

**Comment by kizniche** [comment]
Github issues is not av place for general questions. This would be more appropriate on the forum or the discord server. To answer your question, any Input can have an equation Action added to it, which allows you to apply an equation to recalculate the measurement before being stored in the database.
