### ISSUE TITLE
Py code does not saving if "Analyze Python with Pylint" is unchecked

### ISSUE THREAD

**Issue by wingsergey** [kizniche/Mycodo#1291]
### Describe the problem/bug

If uncheck 'Analyze Python with Pylint' flag during saving of Conditional Functions code under Run Python Code section is not applied in controller.

### Versions:

 - Mycodo Version: *8.15.7*
 - Raspberry Pi Version: *4B*
 - Raspbian OS Version: *Buster Lite*

### Additional context

In daemon logs I also can see old code in debug message

**Comment by kizniche** [comment]
What version? Have you upgraded to master to confirm the unreleased version hasn't fixed this?

**Comment by kizniche** [comment]
I see the issue at https://github.com/kizniche/Mycodo/blob/e76dbd7b4d65174e2ec12615943bcd2efaceca02/mycodo/mycodo_flask/utils/utils_conditional.py#L40

Thanks for the bug report. I'll commit a fix soon.

**Comment by kizniche** [comment]
Upon further inspection, it is saving the code, it's just not providing an output.
