### ISSUE TITLE
Unable to Generate Camera Timelapses

### ISSUE THREAD

**Issue by robocode-LAB** [kizniche/Mycodo#1308]
Attempting to add a time-lapse using the basic function page using a working camera. I'm unable to generate any time-lapse stills now.

1. Images of the time-lapse information with error are shown. 
2. No pictures are ever generated in the time-lapse photo. There were time-lapse photos from a different date, indicating it worked at one time
3. Still images function as expected with below criteria, both when manually generated from the Camera page and when using a widget. 
4. I've attempted re-install camera again, and using all of the different libraries with no effect. Restarting the front end/ back end/ and system have no effect.
5. Mycodo has been updated to the latest 8.15.8, but this error also occurred on the last two versions I was running
6. Camera details: Arducam Fisheye Camera, 5MP OV5647 1080P Camera Module

If there are any other logs I can provide to assist with troubleshooting I'm happy to, but I would need a bit of direction on how to do 
so.

![run_time_error_Still_working](https://github.com/kizniche/Mycodo/assets/82898491/4df0a1eb-2bc4-4306-9aa9-32b018966221)

As a side note, there is a second issue where I can no longer enter a 0 for an indefinite time-lapse. This appears to be new to 8.15.8 as this did not occur until the update.

P.S. As a note, (unable to run infinitely without entering 0 for time-lapse, which I thought was no longer possible based on other error reports, but that is an aside.

![run_time_eroor](https://github.com/kizniche/Mycodo/assets/82898491/199f542e-db38-4bca-91f5-f1e03df5431d)

**Comment by kizniche** [comment]
This was fixed in 44ac00b5f973c140d85c558e752f75ebd49832e0 on April 16 and is in the yet-to-be released code.
