### ISSUE TITLE
Influxdb wont install correctly 

### ISSUE THREAD

**Issue by Benjamar** [kizniche/Mycodo#1319]
When setting up and installing Mycodo it is never able to connect to influxdb after install. When Mycodo is running I am unable to get any measurement data.

 - Mycodo Version: 8.15.8
 - Raspberry Pi Version: Pi Zero W
 - Raspbian OS Version: Raspberry Pi Lite OS

1, Write fresh OS to sd card
2. Connect Via Putty 
3. Run sudo apt update
4. Run sudo apt upgrade
5. Run curl -L https://kizniche.github.io/Mycodo/install | bash
6. Select yes to all downland prompts including install influxdb 1.x
7. connect to mycodo and set up admin account

Influxdb wont work at all I have tried to connect to it directly through the putty terminal with no success and get the following error
![Influxerror](https://github.com/kizniche/Mycodo/assets/70705926/9c4cd80c-a4c0-43cf-b3f1-2546a33c90d0)
Also here is the section of the install where it attempted to install influxdb
![install_log_influx](https://github.com/kizniche/Mycodo/assets/70705926/5cd3d988-b63f-4a6f-94f2-1e3faabc28a6)

I did try installing Influxdb by itself before and I got it to work on its own, but I wasn't able to get Mycodo to talk with it.

let me know if there is anything else you need. Thanks for the help!

**Comment by kizniche** [comment]
See #1275
