### ISSUE TITLE
Add code UUID in the Conditional Controler code view

### ISSUE THREAD

**Issue by lalebarde** [kizniche/Mycodo#1322]
I start having a number of _Conditional Controllers_ I edit from the command line instead of from the Mycodo GUI. The _Conditional Controller_ source code are located in the `user_python_code` folder:

```
pi@raspberrypi:~ $ ls -l /home/pi/Mycodo/mycodo/user_python_code/
total 56
-rw-r--r-- 1 mycodo mycodo  9112 juin   2 10:19 conditional_045edd83-4918-4ef5-beda-fa11a3b5c52c.py
-rw-rw-r-- 1 mycodo mycodo  2630 mai   27 10:22 conditional_087ea8ca-fdfd-4e13-866a-ee71690d02e9.py
-rw-rw-r-- 1 mycodo mycodo  2707 mai   27 18:32 conditional_960d9665-a389-4a3c-8330-b8e0ca4c0ad8.py
-rw-rw-r-- 1 mycodo mycodo 14281 juil. 16 08:20 conditional_b59fcb3e-0027-4ad1-b774-6a4617d36d8c.py
-rw-rw-r-- 1 mycodo mycodo  1721 juin   4 18:05 conditional_c80725e6-c802-4d48-8a86-d2712ef1c28a.py
-rw-rw-r-- 1 mycodo mycodo  2386 mai   27 10:22 conditional_cb790a59-ba10-4cb6-89b7-973f033d0bb6.py
-rw-rw-r-- 1 mycodo mycodo  2110 mai   27 10:22 conditional_ea0ad994-2725-451e-9b45-c1814cc23c87.py
```

My process is: 1) copy the file to development environment, 2) initialize git, 3) edit, 4) copy/paste the code in the GUI sections.

At this time, there is no way to catch which file correspond to which function in the GUI. I have to consider the file date and to open it to figure out.

Solutions could be:

- Include in the file name the function name
- Display the conditional uuid used in the file name in the GUI
- Both

**Comment by kizniche** [comment]
You can find the controller UUID by hovering your mouse over the controller name.
