### ISSUE TITLE
Graph (Synchronous) [Highstock] widget not displaying past data beyond 24 h

### ISSUE THREAD

**Issue by andresn** [kizniche/Mycodo#1324]
### Versions:

 - Mycodo Version: 8.15.8
 - Raspberry Pi Version: 400 Rev 1.1
 - Raspbian OS Version: Bullseye

### Reproducibility

1. Add new Graph (Synchronous) [Highstock] Widget Configuration and any parameters to track.
2. Save graph, confirm it's rendering data correctly, and wait for more than 24 hours.
3. Clicking on the "Full" button in the top nav only shows data for 1 day (Fig. 1). Also, note not being able to click on prior days in the calendar drop-down (Fig. 2).

### Expected behavior

I would expect there to be more data available beyond 24 h since I've had the graph successfully render data every day for 5 days now.

### Screenshots
Fig. 1
![image](https://github.com/kizniche/Mycodo/assets/69597/5ab4893c-e227-442a-90be-12dd067b54bd)

Fig. 2
![image](https://github.com/kizniche/Mycodo/assets/69597/ee5e70ae-bc42-44dd-8d34-5142229baa85)

### Additional context

Probably missing something obvious in the software's config.

Free Space (Input 06a2dd8c)
Input (RPiFreeSpace), 15.0 second interval
Measurement | Timestamp
2809.61 MB (Disk) CH0 | 2023/7/26 0:09:23

**Comment by kizniche** [comment]
Change the x-axis duration in the configuration.
