### ISSUE TITLE
Sensor settings were not able to be modified: invalid literal for int() with base 10: 'RPi'

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#134]
This is the error message I get when try to rename a sensor. I'm running v4.0.22, commit '3b1a448 Colors for @zsole2 and title rearrangement'.
I have another Pi is being set up currently,  but I don't think upgrading to the up-to-date version will  not matter with this error.

**Comment by kizniche** [comment]
Commit 58e8a9e should have fixed that issue. Looks like you're 9 commits behind that one.

**Comment by kizniche** [comment]
Let me know whenever you update your system if it fixed the issue.

**Comment by zsole2** [comment]
I confirm that the upgrade fixed the issue.
