### ISSUE TITLE
1.3" Oled SSD1306 v SSH1106

### ISSUE THREAD

**Issue by Chomski99** [kizniche/Mycodo#1346]
I have a working SSD1306 Oled display working. I have bought more SSD1306 but they turn out to be using the SSH1106 chip but they don't work with Mycodo. I can see them on the I2C bus but all I get is a white screen. Reading up on this its to do with not using the correct library. How I can I fix this?

**Comment by kizniche** [comment]
You may be able to duplicate an SSD1306 module with the correct number of lines/characters and modify it to use the correct library.
