### ISSUE TITLE
ToDo - Implement Template Inheritance 

### ISSUE THREAD

**Issue by etiology** [kizniche/Mycodo#135]
[Jinja2 Template Inheritance](http://flask.pocoo.org/docs/0.11/patterns/templateinheritance/)

There is a great opportunity to DRY out the [templates](https://github.com/kizniche/Mycodo/blob/b8123afbc2840751626b474c48984884f141220a/mycodo/mycodo_flask/templates/layout.html) by using inheritance patterns.  In all of the templates we create our header, title, body, and script calls.  We don't need to do that more than once.

Template inheritance allows us to create a `base_layout.html` file with the general page setup attaching scripts, bootstrap, highcharts, etc.  We then use blocks to mark places where our subpages put their stuff.  So if we have a page that shows graphs, then that `html` should just focus on the graph context.  It doesn't need to know that some other page needs to import that neat javascript library or css module.

Using an inheritance pattern in our templates makes the code cleaner and easier to maintain.  If every page imports a bootstrap library then we need to update every page when we need to change the version.  If inheritance is used then we only update one area and all of the pages change.

**Comment by kizniche** [comment]
I tried to do this for the most part, but I suppose I wasn't as thorough as I could have been. This was my first time using Jinja2, so I guess I strayed from the original template I used.
