### ISSUE TITLE
Add notes via API

### ISSUE THREAD

**Issue by samuk** [kizniche/Mycodo#1357]
**Is your feature request related to a problem? Please describe.**

When on the farm I don't want to open a web app to add a note.

I'd like to be able to add them via an existing farm management app

**Describe the solution you'd like**
Expose the note functionality in the Rest API so that notes can be added by other apps.

**Describe alternatives you've considered**

Running https://v1.farmos.org/guide/app/ and FarmOS as separate apps and syncing the data later somehow

**Additional context**
I may be able to fund this feature request depending on the costs involved.

**Comment by kizniche** [comment]
It should be fairly easy to add a create/delete note tag and add note endpoints. I'll take a look at the code shortly.

**Comment by samuk** [comment]
Nice, thanks. 

I'm thinking I'd use the https://farmos.org/model/type/log/ taxonomy if possible

**Comment by kizniche** [comment]
Notes are text strings, so you can format the string any way you wish.

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/aquaponics-atlas-beagleboard-ai-farmos/1726/2

**Comment by kizniche** [comment]
I just added a note creation endpoint on the master branch, but I haven't extensively tested it.
