### ISSUE TITLE
fswebcam and config file

### ISSUE THREAD

**Issue by aproxxo** [kizniche/Mycodo#1379]
Hi,

My webcam (fswebcam) shows very bad pictures in Mycodo.
Now I have created a parameter file, webcam.cfg.

With the command "fswebcam -c webcam.cfg" the pictures are now perfect. How can I now integrate the parameter file into Mycodo?

Greeting

**Comment by kizniche** [comment]
THe Custom Options field inserts text into the command that's executed.
