### ISSUE TITLE
I'm Back!

### ISSUE THREAD

**Issue by kizniche** [kizniche/Mycodo#149]
Not an issue, but I just wanted to say that my lack of activity for the past few weeks (and several years of study and research) has payed off. I successfully defended my PhD dissertation this morning and became Dr. Gabriel! My presentation title slide is below.

![slide 1](https://cloud.githubusercontent.com/assets/838427/20363265/945ba768-ac0c-11e6-94f6-446bf9219d7d.png)

**Comment by etiology** [comment]
# Congratulations!!

Can you link your paper?  I'd love to read it and pay walls are annoying

**Comment by kizniche** [comment]
Thank you! I would, but there's intellectual property and a current patent application discussed in it, so I need to first check if my committee wants to put an embargo on it. If not, I'll upload it. I'll find out soon.

**Comment by etiology** [comment]
No worries.  When it's time though I'd love to read it.  A link to the published work would be fine.  That way you're in the clear

**Comment by berserktron3k** [comment]
Congrats!

Brady Hummel

**Comment by Myke974** [comment]
Congratulations ! ! Dr. Gabriel ! ! ! :D Respect !

2016-11-17 0:08 GMT+04:00 berserktron3k <notifications@github.com>:

**Comment by zsole2** [comment]
Congratulations!
Be careful what you tell us even here... Being a patent attorney,  I could tell you a few stories about accidentally disclosing an invention before filing a well written patent application. It could be a major headache later...

**Comment by kizniche** [comment]
This is our current PCT application, so I'll link this before I find out if I should link my dissertation. I'm also performing minor revisions on the dissertation, so I haven't submitted the final copy yet.

[Patent Application PCT/US2015/044807](https://www.google.com/patents/WO2016025572A1?cl=en&dq=ininventor:%22Kyle+T.+GABRIEL%22&hl=en&sa=X&ved=0ahUKEwjbz6H91bDQAhVW1WMKHdeJA3YQ6AEIHTAA)

**Comment by zsole2** [comment]
OK, if you have the PCT application already published, then you're safe. It is certainly interesting stuff, although the search opinion is not too good. It is always tough to get patents in computer implemented inventions, even in the US it is getting harder recently.

**Comment by kizniche** [comment]
My committee wants to put a 2-year embargo on my dissertation, so unfortunately I can't publicize it until that expires.
