### ISSUE TITLE
Start Stream Gives 500 Internal Server Error

### ISSUE THREAD

**Issue by berserktron3k** [kizniche/Mycodo#155]
## Mycodo Issue Report:
  - Specific Mycodo Version: 4.0.26
  - git commit hash: 2fd91bb
 
#### Problem Description
When clicking Start Stream, I receive:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by kizniche** [comment]
At the moment my camera is in use, so I can't test this right now. I'll be able to pause it soon, then I'll run some tests.

**Comment by kizniche** [comment]
I didn't anticipate taking so long to test this, but I found the issue and pushed an update.
