### ISSUE TITLE
Data tab / combined / Relay Run Time : graph is "blank"

### ISSUE THREAD

**Issue by Myke974** [kizniche/Mycodo#16]
When analysing my graph with the DATA tab, I realise that "combined" won't show the relays run time on the graph

**Comment by kizniche** [comment]
This looks like a complex bit of code to sort out. It will probably be a little while before I get this working correctly. I will most likely have to add a setting that defines the relay y-axis min/max for custom graphs.

**Comment by Myke974** [comment]
OK ! This is not a hurry though because we are abble to see up to 6 month back on the graph page ! Awesome !

**Comment by kizniche** [comment]
I have a working implementation with the latest commit, for combined temperature graphs. I'll implement it for the other graphs very soon.
