### ISSUE TITLE
Issue with multiplexer

### ISSUE THREAD

**Issue by levalencia** [kizniche/Mycodo#166]
Hello

I have the following issue with the multiplexer, all I want is to connect multiple BM180 sensors
http://stackoverflow.com/questions/41335921/how-to-read-from-multiplexer-with-python-i2c-tca9548a

To make this works, do I need to add overlays to config.txt, how?
Something am I missing?

**Comment by kizniche** [comment]
What specific circuit/breakout board are you using?

Is it detected once connected, with `sudo i2cdetect -y 1` ?

**Comment by kizniche** [comment]
Make sure you followed the install instructions (raspi-config) where I2C is enabled. Also, a reboot is necessary after changing that option.
