### ISSUE TITLE
Multiplexer tca9548a

### ISSUE THREAD

**Issue by d3ltad** [kizniche/Mycodo#168]
Hi,
Is it possible to multiplex HD44780 LCD-Displays with the TCA9548a Multiplexer or only sensors?

**Comment by kizniche** [comment]
Yes, if the LCD has an I2C backpack, you can use the multiplexer to attach multiple LCDs with the same I2C address. Keep in mind though that the I2C LCDs typically have a way to select the I2C address, so you won't necessarily need a multiplexer until you use all the addresses.
