### ISSUE TITLE
RPi CoreVoltage/clock frequency display - feature request

### ISSUE THREAD

**Issue by MurderLabz** [kizniche/Mycodo#175]
Do others think it would be useful to display core voltage or clock frequency in the WebUI?

			  S Y S T E M    V O L T A G E S  

	The Core voltage is:		1.3125V
	The sdram Core voltage is:	1.2000V
	The sdram I/O voltage is:	1.2000V
	The sdram PHY voltage is:	1.2250V

			  C L O C K    F R E Q U E N C I E S  

     	arm   frequency(45)=900000000 Hz    pwm	  frequency(25)=0 Hz
     	core  frequency(1)=250000000 Hz	    emmc  frequency(47)=250000000 Hz
     	h264  frequency(28)=250000000 Hz    pixel frequency(29)=25200000 Hz
     	isp   frequency(42)=250000000 Hz    vec	  frequency(10)=0 Hz
     	v3d   frequency(43)=250000000 Hz    hdmi  frequency(9)=163682000 Hz
     	uart  frequency(22)=47999000 Hz	    dpi	  frequency(4)=0 Hz

[rpi_cv_cf.txt](https://github.com/kizniche/Mycodo/files/721432/rpi_cv_cf.txt)

**Comment by kizniche** [comment]
I never really had a use for this information. What would one theoretically use it for?

**Comment by kizniche** [comment]
Also, what is 'bc'? I see it installed in the script but I don't see it used.

**Comment by MurderLabz** [comment]
bc(1)                                                                 General Commands Manual                                                                 bc(1)

NAME
       bc - An arbitrary precision calculator language

SYNTAX
       bc [ -hlwsqv ] [long-options] [  file ... ]

DESCRIPTION
       bc  is  a  language  that supports arbitrary precision numbers with interactive execution of statements.  There are some similarities in the syntax to the C
       programming language.  A standard math library is available by command line option.  If requested, the math library is defined before processing any  files.
       bc  starts  by  processing  code  from all the files listed on the command line in the order listed.  After all files have been processed, bc reads from the
       standard input.  All code is executed as it is read.  (If a file contains a command to halt the processor, bc will never read from the standard input.)

       This version of bc contains several extensions beyond traditional bc implementations and the POSIX draft standard.  Command line  options  can  cause  these
       extensions to print a warning or to be rejected.  This document describes the language accepted by this processor.  Extensions will be identified as such.

**Comment by kizniche** [comment]
right, but where is it used in the script? I don't see it.

**Comment by MurderLabz** [comment]
What I am really after is watching voltage usage. As sensors an Relays are added when to know you would need to start using another PS - (BC) I hacked that out of another script
[full.txt](https://github.com/kizniche/Mycodo/files/721434/full.txt)
 let me post the org script

**Comment by kizniche** [comment]
This is the line that uses it from full.txt, line 48:

```TEMPB4OVER=$(echo "${OVRTMP:-70}-${TEMPf}"|bc -l)                               # Calculate the number of degrees before over-temp condition```

Seems you took that out and bc is no longer a requirement.

**Comment by MurderLabz** [comment]
I think for 'TEMPB4OVER=$(echo "${OVRTMP:-70}-${TEMPf}"|bc -l)  '

**Comment by MurderLabz** [comment]
Sorry, I should of yanked that out

**Comment by kizniche** [comment]
Just making sure I'm not missing something

**Comment by kizniche** [comment]
Would the core voltage change? wouldn't the Pi stop operating if there were an under-voltage situation?

**Comment by MurderLabz** [comment]
Ah.. you are correct.. "The core voltage is regulated and won't go down until the battery resembles a pancake" https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=166404
I guess this would be of no use..

**Comment by MurderLabz** [comment]
Lets close and let me think this more thoroughly...

**Comment by kizniche** [comment]
Yeah, if it's a niche area that very few people are likely to use, I'm hesitant to add it when those people can just execute their own code. But, if it helps with diagnosing issues or something that's directly related to Mycodo/Pi, and it's more than a niche market, I'm all for adding. Thanks for the suggestion.
