### ISSUE TITLE
favicon for easy searching in browser tabs

### ISSUE THREAD

**Issue by boomstick8x** [kizniche/Mycodo#18]
Few times I run with my eyes more than usually to find Mycodo tab in browser. I can try to make favicon for the project. May be you have an ideas about graphics?

p.s. What Mycodo means? I think first part 'Myco' shortcut from mycology, but the last 'do' I don't understand?

test image:
![apple-touch-icon-144x144](https://cloud.githubusercontent.com/assets/9988953/9961365/cf3208ec-5e28-11e5-8063-c46a05af6d72.png)

**Comment by kizniche** [comment]
Nice idea. I've added a fav icon.

Back in 2009, when this was just a command line program, I wanted to have myco (fungus, mycology) in the the name. I just came up with Mycodo (like sudo), and I just never changed it. There's not much meaning beyond the myco part, but it's grown on me since then.

**Comment by boomstick8x** [comment]
Yep! I see favicon! Thank you!

Can I ask you a question here about graphs?
What is green line on graph named DP? Digitall Pressure?
(If so why green line generating on DHT22 sensor?)

**Comment by Myke974** [comment]
Green Line is the Dew Point ! :D
https://en.wikipedia.org/wiki/Dew_point

2015-09-18 21:21 GMT+04:00 boomstick8x <notifications@github.com>:

**Comment by boomstick8x** [comment]
Ops... Digital Pressure... What I am thinking about.. :`D
Thanks!
