### ISSUE TITLE
Egg Incubator

### ISSUE THREAD

**Issue by LuCeTeMa** [kizniche/Mycodo#180]
Thank you for your help, really great what you have programmed there.
I am currently doing the German translation.

Now to my question,
I would like to operate a chicken incubator.
The incubator should run 21 days at 37 ° C - 39 ° C.
The humidity should be 18 days to 50 to 55% and then 3 days to 65%.

I have a DHT22 and 8 relay that also works.

I am now missing only a thought on how to make it happen.
As PID or as method?

I’d really appreciate any kind of solution.

All the best,
Martin

**Comment by kizniche** [comment]
Hi Martin,
Thank you for working on a translation!

In fact, thinking about if you wanted to have both temperature and humidity regulation absolutely stop at 21 days, I don't think that's possible. You will have to manually turn it off. This is definitely a necessary feature, and could easily be coded into the methods. Until I get that new feature integrated into the code, you'll have to manually stop the controller at day 21.

As for your incubator, there are a few questions I would have about your incubation process,

  - Would the incubator need to stop operating after 21 days? (deactivate regulation)
  - Are you only looking to raise temperature and humidity? (i.e. you also don't need to reduce humidity and temperature)
  - Are your devices for modulating humidity and temperature sensitive to quick power cycling?

Without knowing these things, this is how I would do it:

### Sensor 1
 Temperature/humidity sensor

### Method 1
Name: "Humidity_52_65", Type: Duration
Entry 1: 1555200 seconds (18 days), Start Setpoint: 52.5
Entry 2: 259200 seconds, Start Setpoint: 65

### PID 1
Name: "Incubator Humidity"
Sensor ID: Sensor 1
Measure Type: Humidity
Direction: Raise
Setpoint: 65.00 (this isn't used if a method is selected, but once the method ends, it will drop back to using this setpoint, so we're setting this to the same % set in the method)
Period, Kp, Ki, Kd: You will have to experiment to find the best values
Raise Relay ID: Humidifier Relay
Raise Min Duration: Depends if you are using a device that should not be power cycled for x number of seconds
Raise Max Duration: 0
Setpoint Tracking Method: Humidity_52_65

### PID 2
Name: "Incubator Temperature"
Measure Type: Temperature
Direction: Raise
Setpoint: 38.0
Period, Kp, Ki, Kd: You will have to experiment to find the best values
Raise Relay ID: Heater Relay
Raise Min Duration: Depends if you are using a device that should not be power cycled for x number of seconds
Raise Max Duration: 0
Setpoint Tracking Method: Temperature_38

You will have to activate both PID controllers at the same time. The temperature will be regulated at a constant 38 C, and the humidity will be regulated for the first 18 days at 52%, and then for the next 3 days at 65%. Like I said previously, until I get that STOP feature implemented, you will have to appear at day 21 and stop both PID controllers from the Mycodo web interface.

If you want either the temperature or humidity regulated both directions (the above setup only uses one relay each to regulate in the up direction), then you will have to change direction to "Both" and then also select a "Lower Relay" that will be used to lower the environmental condition if it rises above your setpoint.

PID tuning can be tricky, but I've written about it a few times, in the manual (click Help at the top-right, when logged into the web interface, and find "PID Tuning" in the table of contents), and a [tuning I went through with screenshots of the graphs after each tuning](https://hackaday.io/project/11997-mycodo-environmental-regulation-system/log/45733-sous-vide-pid-tuning-and-the-unexpected-electrical-fire). The article I wrote in the link actually contains a small house fire I accidentally created during my tuning process, but don't worry, it was user error, not Mycodo's fault.
