### ISSUE TITLE
Setup error when installing wiringpi

### ISSUE THREAD

**Issue by Myke974** [kizniche/Mycodo#183]
## Mycodo Issue Report:
  - Specific Mycodo Version: 4.1.10
 
#### Problem Description
Please list:

  - what were you trying to do : install mycodo
  - specific setup details that are involved : 
New install Raspbian jessie lite.

 
### Errors
  - List any errors you encountered :
```
#### Installing wiringpi ####
./setup.sh: line 64: git: command not found

*******************************
*** ERROR: Install Aborted! ***
*******************************
```

An error occurred that prevented Mycodo from being installed!

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. Use a fresh/new install of Raspbian on Raspberry Pi (2017-01-11-raspbian-jessie-lite.img)
 2. launch mycodo setup.sh with:
```
cd Mycodo/install
sudo /bin/bash ./setup.sh
```

 
### Additional Notes
Installing Git with:
`sud apt-get install git`
resolved the problem.

**Comment by kizniche** [comment]
Thank you. I'll look into this and amend the 4.1.10 release.
