### ISSUE TITLE
Asynchronous graph shows incorrect current local time.

### ISSUE THREAD

**Issue by isoflux** [kizniche/Mycodo#185]
Mycodo Version: 4.1.15
 
#### Problem Description
  - Time in  asynchronous graph page is slower than the current local time for 7 hrs.  It seems that it didn't add my timezone (GMT+7) to the  asynchronous graph time.  By the way, general graph page shows correct current local time.

Regards,
Sujin

**Comment by kizniche** [comment]
I've been able to reproduce this issue. I'll look into it.
