### ISSUE TITLE
[suggestion] add to relays conditionals : < = >

### ISSUE THREAD

**Issue by Myke974** [kizniche/Mycodo#186]
## Where ?
![nurserypi_relays_condit_01](https://cloud.githubusercontent.com/assets/1829188/22519157/c29f2156-e8c8-11e6-8cd6-7c604a9c2fa0.jpg)

## How you suggest to implement ?
in replacement of the "for" word in the syntaxe : 
If "relay x" ON/OFF (**for** 0/x sec.) 
a menu where to choose from : 
egal =
superior >
inferior >
different ?

**Comment by kizniche** [comment]
Nice suggestion
