### ISSUE TITLE
PID values not updating in mycodo web : Live page

### ISSUE THREAD

**Issue by Myke974** [kizniche/Mycodo#189]
## Mycodo Issue Report:
  - Specific Mycodo Version: 4.1.15
 
#### Problem Description
Perhaps it is normal behavior but in case it can be ameliorated.
 
### Steps to Reproduce the issue:

 1. Keep mycodo web **Live** page open in one browser tab.
 2. Open mycodo web **PID** page in another tab and change the settings and hit **save settings**.
 3. Check the **Live** page where sensors reads are displayed live at each reads : PID old settings will stays as there were without reflecting the new changes until you refresh the page.

**Comment by kizniche** [comment]
Only sensor measurements and timestamps are rendered client-side on the Live page.

This is expected behavior.
