### ISSUE TITLE
Request for tester with an LCD

### ISSUE THREAD

**Issue by kizniche** [kizniche/Mycodo#190]
I'm looking for someone with an LCD to test something for me.

The test is very simple:

1. Be running the latest version of Mycodo (4.1.15)
2. Set one of your LCD lines to display a Relay Time.
3. Make sure the relay has been turned on and off at least once for this to work.
4. Reply here with whether it displays correctly or gives an error on the LCD. Also include which Mycodo version you are running.

The help is much appreciated. Thanks.

**Comment by jj2473** [comment]
Just sent you an email to your account, appears to work fine on 4.1.8

Thanks,
Jim

**Comment by kizniche** [comment]
Thank you, @jj2473

Quick update to the test, I believe you will need to have Mycodo be near the latest version 4.1.15, because I believe this is affected by having the latest version of influxdb (1.2.0).

**Comment by jj2473** [comment]
Ok give me a couple to power on Incubator, that is more current but was having issue with relay so I shut it down. Replacing with solid state this weekend.

**Comment by kizniche** [comment]
I actually found the issue, so I won't need any more testing. I was able to get the error to be produced on my own LCDs, so I can test on my own. Thank you for the help.
