### ISSUE TITLE
General graph showing 500 Internal Server Error

### ISSUE THREAD

**Issue by pewi81** [kizniche/Mycodo#196]
## Mycodo Issue Report:
  - Specific Mycodo Version: 4.1.16
 
#### Problem Description
Please list: 
When trying to open General Graph I get:
**500 Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**

Asynchronous Graph works flawless
 
### Errors
500 Internal Server Error 

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. Try to access General Graph 
 2. step 1
 3. etc
 
### Additional Notes
This happened after an udate but I cant remember from which version it was.
I tried a few tips from the installation page but nothing works.

**Comment by Myke974** [comment]
Can you please show your
`/var/log/mycodo/mycodoupdate.log`

**Comment by pewi81** [comment]
Sorted it out by deleting the database!

**Comment by kizniche** [comment]
Good to hear! That would have been my suggestion.
