### ISSUE TITLE
bme280?

### ISSUE THREAD

**Issue by Drakthule** [kizniche/Mycodo#197]
i was wondering i dont seem to have a humidity reading from my new bme280, is this normal?

**Comment by Myke974** [comment]
Like this ?
![bme280prb01](https://cloud.githubusercontent.com/assets/1829188/23362169/edd17636-fd0d-11e6-91ef-56aba00b147c.jpg)
check the blue line 🔵 
it seems I got the same illness !
I never saw a variation in its R.H. ! in weeks ! 😮

**Comment by Drakthule** [comment]
wow i feel really stupid, i could never find it in the live page but low and behold it is listed under graphs thanks mike974

**Comment by kizniche** [comment]
This is a known bug. I forgot to put the humidity line in the live page when I added the sensor to Mycodo. All parts of the system should recognize the measurement from the sensor, it's just not displaying on the live page. This will be fixed in the next version release.

Since you have this sensor, can you verify you are receiving normal humidity measurements?

I ask because @myke974 has a very unresponsive humidity reading.

**Comment by Myke974** [comment]
😩 yes I have !

**Comment by Drakthule** [comment]
I can verify, ive nothing to test it against for accuracy but it does seem to be working

**Comment by kizniche** [comment]
So it is at least a little more variable than @myke974's graph image? His basically shows humidity flatlining (it's actually just changing **very** slowly).

**Comment by Drakthule** [comment]
![bme280](https://cloud.githubusercontent.com/assets/25154284/23387447/731857a8-fd11-11e6-9147-6b8c14f5ffc0.jpg)
hmmmm im not so sure the humidity is always like that in my room, now im not so sure

**Comment by kizniche** [comment]
Just cupping your hand over the sensor should raise it up near 100%. Humidity should swing easily within a range of 20 to 50 % in a day.

**Comment by Drakthule** [comment]
ive been meaning to put the bme in my tank, let me crimp together a cable for it and ill stick it into the tank, ill know for sure if it works as the tank is much more humid to accomdate my drosera and nepenthes

**Comment by Drakthule** [comment]
perhaps its to soon to know for sure but after making a cable and putting the sensor in the tank right next to the dht22 the temp readings are within a degree faranheit however the humidity is off by 10 degrees, the dht 22 is fluxuating as expected and the bme280 doesnt seem to fluxuate much if at all and is reading in the 77% humidity area same as it was outside of the tank.

**Comment by kizniche** [comment]
I'm going through old issues and trying to get investigations going for things I think are fixable. Are you able to use any other code (such as from the manufacturer or online forums, preferably in Python) that give more responsive or more accurate readings? If so, and it's more accurate than the code currently in Mycodo, I can replace it with the working code.

**Comment by Theoi-Meteoroi** [comment]
I'm using the BME280 with version 5.2.5.  I'm not having any issues with the readings or presentation in graphs.  This issue has had me puzzled as I looked for problems with the data, yet found none.

**Comment by kizniche** [comment]
I believe this issue was due to a faulty sensor. Feel free to reopen or reply if there are any new developments. I don't have this sensor, so I cannot test myself.
