### ISSUE TITLE
Please provide opencv-python version in requirements.txt for 5.0-dev branch

### ISSUE THREAD

**Issue by lucasvickers** [kizniche/Mycodo#199]
## Mycodo Issue Report:
  - 5.0-dev
 
#### Problem Description
`requirements.py` [Line 19](https://github.com/kizniche/Mycodo/blob/dev-5.0/install/requirements.txt#L19) does not specify opencv-python version.

I'm assuming it's 3.2.0.6, but you should update this in the file.

Thanks

**Comment by kizniche** [comment]
Thanks. I'll fix that in the next commit.
