### ISSUE TITLE
5.0-dev install puts flask files outside of install dir

### ISSUE THREAD

**Issue by lucasvickers** [kizniche/Mycodo#206]
## Mycodo Issue Report:
  - 5.0-dev
 
#### Problem Description
I couldn't tell you exactly which install did it, but somehow the mycodo_flask winds up outside of the install dir.

```
$ cd ~
$ ls
mycodo  Mycodo
$ ls mycodo/
mycodo_flask
```

**Comment by kizniche** [comment]
lol That's a first. I did update the upgrade_commands.sh script, but not sure if that would have caused it. Don't attempt to use the  upgrade_mycodo_release.sh script, it depends on specific tags on github. I'll investigate when I install 5.0 fresh in a second.

**Comment by kizniche** [comment]
My fresh install of 5.0 didn't do this, so I'm closing it.
