### ISSUE TITLE
5.0-dev graphs not working

### ISSUE THREAD

**Issue by lucasvickers** [kizniche/Mycodo#207]
## Mycodo Issue Report:
  - 5.0-dev
 
#### Problem Description
Graphs do not generate data.  I see live data, so I know the sensors are being read properly.

I don't see any obvious errors, can look more if needed.

![screen shot 2017-03-14 at 5 22 55 pm](https://cloud.githubusercontent.com/assets/1099950/23922885/ad88c5ba-08da-11e7-93c8-52a2ad2bee5d.png)

**Comment by kizniche** [comment]
Can you add the raspberry pi temperature sensor, delete all graphs, add one graph with just that sensor and see if the same behavior exists?

**Comment by lucasvickers** [comment]
Woah, weird.

I deleted the first of my 3 graphs and the other 2 started working.

If I then add back a graph with 6 readings/sensors in it, it breaks.  Perhaps the problem is max items?

**Comment by kizniche** [comment]
It's an issue with one particular sensor measurement. Can you enable measurements until you find the offending measurement?

**Comment by kizniche** [comment]
enable them in the graph that is

**Comment by lucasvickers** [comment]
DHT22 - Dew Point

**Comment by kizniche** [comment]
Thanks. I have that sensor hooked up. I'll look into it.

**Comment by kizniche** [comment]
yep, that kills my graph, too

**Comment by kizniche** [comment]
That should do it
