### ISSUE TITLE
Timers wont trigger relays

### ISSUE THREAD

**Issue by pewi81** [kizniche/Mycodo#213]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.03
 
#### Problem Description
Please list: All my timers wont work when they are supposed to. No error messages, they just wont fire the relays.

**Comment by kizniche** [comment]
Thanks. Looking into it. Can you give me more details (an example) of a timer configuration that causes the issue?

**Comment by kizniche** [comment]
I was able to reproduce the issue. There aren't any errors in the logs. Testing...
