### ISSUE TITLE
EDGE sensor conditional error

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#214]
## Mycodo Issue Report:
v5.0.5
 
#### Problem Description

My edge sensors were working fine on v4.0.24. Putting in the new SD card with v5.0.4, errors come up. 
Both my sensors are set up to trigger on the specific state:
![edge_setup](https://cloud.githubusercontent.com/assets/11209960/24079423/e5b0c8c4-0c87-11e7-830a-455880792683.png)

### Errors

Here is the relevant section from the log:

> 2017-03-19 08:35:42,284 - mycodo.sensor_5 - INFO - Activated Conditional (1)
> 2017-03-19 08:35:42,710 - mycodo.sensor_5 - INFO - Activated in 571.3 ms
> 2017-03-19 08:35:42,737 - mycodo.sensor_5 - ERROR - Error: 1
> Traceback (most recent call last):
>   File "/var/www/mycodo/mycodo/controller_sensor.py", line 351, in run
>     self.cond_if_sensor_edge_select[each_cond_id] == 'state'):
> KeyError: 1
> 2017-03-19 08:35:43,192 - mycodo.sensor_6 - INFO - Activated Conditional (2)
> 2017-03-19 08:35:43,692 - mycodo.sensor_6 - INFO - Activated in 668.0 ms
> 2017-03-19 08:35:43,701 - mycodo - INFO - All activated sensor controllers started
> 2017-03-19 08:35:43,711 - mycodo.sensor_6 - ERROR - Error: 2
> Traceback (most recent call last):
>   File "/var/www/mycodo/mycodo/controller_sensor.py", line 351, in run
>     self.cond_if_sensor_edge_select[each_cond_id] == 'state'):
> KeyError: 2

### Steps to Reproduce the issue:
Other then setting up the edge sensor the same way, it would be hard to reproduce my system, see #107. 
 
### Additional Notes

I can confirm that v5.0.5 solved the issue of timers not triggering relays...I had v5.0.4 where it was a problem, and now timers work OK. All in all, everything else seems perfect after a few hours of testing.

**Comment by kizniche** [comment]
That should fix it. Another careless mistake on my part. Let me know if there are still any issues with it.
