### ISSUE TITLE
Live page shows incorrect HTU21D temp

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#215]
## Mycodo Issue Report:
v5.0.5
 
#### Problem Description

It appears that the temperature and dew point is switched.
 
![htu_live](https://cloud.githubusercontent.com/assets/11209960/24079697/2d48d856-0c8e-11e7-9932-f81671267722.png)

**Comment by kizniche** [comment]
It seems when I put the measurements in the database, I put dewpoint first (alphabetical), which caused it to appear first on the live page. I've rearranged that so dewpoint will be at the end. You'll have to delete and readd your sensor for this to take affect. I've also added a "DP" signifier at the end of the dew point so it can be distinguished from the temperature, and included the F conversion for dew point as well. Let me know if any of that doesn't work. Thanks for the bug report.
