### ISSUE TITLE
Timer settings are not saved.

### ISSUE THREAD

**Issue by cohe4ko** [kizniche/Mycodo#222]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.0.13
 
#### Problem Description
in Timers does not save start "Time of day" of any timer

**Comment by kizniche** [comment]
I can't reproduce this issue. start "Time of Day" saves for me, during creation and modification of timers. Can you provide exact steps to reproduce the issue?

**Comment by cohe4ko** [comment]
Now I can't reproduce too.
