### ISSUE TITLE
USB Camera defaults issue

### ISSUE THREAD

**Issue by cohe4ko** [kizniche/Mycodo#225]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.0.13
 
#### Problem Description
I use external USB logitech web camera.
It works properly with fswebcam
`fswebcam -r 1280x960 --no-banner $filename` 
But when I use opencv driver there are many settings and no way to use defaults. 
I tried maybe half an hour to find proper figures but there are so many combinations :)

**Comment by kizniche** [comment]
Try these settings:

![webcam](https://cloud.githubusercontent.com/assets/838427/24326781/c3ff3b5c-118c-11e7-8e61-5aec4854953e.png)

**Comment by cohe4ko** [comment]
Much better :) 
Thank you.

**Comment by kizniche** [comment]
I should make those the default values when a camera is added.

**Comment by cohe4ko** [comment]
It would be perfect.

**Comment by kizniche** [comment]
I'll do some testing and consider adding fswebcam to the list of cam library options.
