### ISSUE TITLE
No units (lux) to choose in conditionals of light sensors

### ISSUE THREAD

**Issue by cohe4ko** [kizniche/Mycodo#230]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.0.14
 
#### Problem Description
![2017-03-27 19 58 23](https://cloud.githubusercontent.com/assets/805783/24368079/c85df020-1327-11e7-8488-8af575298c4d.png)

**Comment by kizniche** [comment]
I meant to get to this issue sooner, but I had my development system unavailable. I just fixed this and will be releasing a new version incorporating this fix this evening.
