### ISSUE TITLE
Not proper relay stats

### ISSUE THREAD

**Issue by cohe4ko** [kizniche/Mycodo#235]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.0.21
 
#### Problem Description
Relay is on whole time but on stats it shown on only for few seconds
![2017-04-05 13 31 55](https://cloud.githubusercontent.com/assets/805783/24701772/6662f170-1a04-11e7-8c2d-de3f7ce250f6.png)

**Comment by kizniche** [comment]
Please be a little more descriptive. I don't understand the issue. Use the issue template to submit a steps to reproduce the issue and explain in detail what the issue is.

**Comment by cohe4ko** [comment]
I use sensor conditional. If the temperature is higher than 20C - turn on Relay4. Conditional works well. Relay turns on if temperature greater than 20C. but on the graphs I see that relay was on only for 2-5 seconds. It's not true.

**Comment by kizniche** [comment]
What is your sensor conditional period?

**Comment by cohe4ko** [comment]
![2017-04-05 15 44 16](https://cloud.githubusercontent.com/assets/805783/24705991/c1b04084-1a16-11e7-891a-06549f0cf0b7.png)

**Comment by kizniche** [comment]
Following your steps, I could not replicate the issue. My grapes show 60 second outputs every 60 seconds. Is relay 4 configured to be used anywhere else in the system?

**Comment by cohe4ko** [comment]
Yes, It is configured on the other sensor with same conditions and on that sensor temperature is higher too.

**Comment by kizniche** [comment]
Turn the other conditional off and test.

**Comment by cohe4ko** [comment]
Done - the graph now is ok.

**Comment by kizniche** [comment]
What is the period of your second conditional you just turned off?

**Comment by cohe4ko** [comment]
but that is wrong behavior. Or not?

**Comment by cohe4ko** [comment]
![2017-04-05 16 07 39](https://cloud.githubusercontent.com/assets/805783/24706863/0661f8dc-1a1a-11e7-99bb-929e06ca1f14.png)

**Comment by kizniche** [comment]
I've never tested more than one conditional using the same relay.

**Comment by kizniche** [comment]
You're inherently bound to have conflicts. I'll check it out and see if there's anything I can do about it. Most likely not because it all depends when the conditionals are activated, which will determine their overlap. If one conditional activates the relay, it will record whatever duration the relay has been on, and turn it on for the new duration.

**Comment by cohe4ko** [comment]
ok. thank you.

**Comment by kizniche** [comment]
I'm not sure if this will break the system, but try this... Create two relays, using the same pin, and set each one up using their own conditional. I'd make sure you're physically at the location where the devices are actuating before attempting this experimental configuration.

**Comment by kizniche** [comment]
Alternatively, create this setup to test:

Relay 4: the actual pin for relay 4
Relay 5: pin to free GPIO (unconnected)
Relay conditional: when relay 5 on for 80 sec, relay 4 on for 80 sec.
Sensor conditional 1: relay 4
Sensor conditional 2: relay 5
