### ISSUE TITLE
Issue updating from 5.0.0

### ISSUE THREAD

**Issue by Sabare3** [kizniche/Mycodo#239]
## Mycodo Issue Report:
  - 5.0.0
 
#### Problem Description
Please list:

I was trying to update the software to the current version 5.0.23. I initiated the update from the webpage under the upgrade tab.
 
### Errors

Errors occured when the Mycodo daemon and web server were started.

> #### Creating proper users, directories, and permissions
> useradd: user 'mycodo' already exists
> The user `mycodo' is already a member of `gpio'.
> The user `mycodo' is already a member of `adm'.
> The user `mycodo' is already a member of `video'.
> 
> #### Starting the Mycodo daemon and web server
> Restarting apache2 (via systemctl): apache2.service.
> 
> *******************************
> *** ERROR: Install Aborted! ***
> *******************************
> 
> An error occurred that prevented Mycodo from being installed!
> 
> Please contact the developer by submitting a bug report at
> https://github.com/kizniche/Mycodo/issues with the pertinent
> excerpts from the setup log located at Mycodo/install/setup.log
> 
> An error occurred. Exiting...

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. Install 5.0.0
 2. Update
 
### Additional Notes
This occured when I tried to update from Version 4 to Version 5.0.0

I'm very new to using raspberry pi. I know enough just to install the program.

**Comment by kizniche** [comment]
An update from 4 -> 5 is not possible. I attempted to get it working, but it's so far in the past there's no hope. Databases from 4.x cannot be used anyway, so reinstallation from scratch is the only option.
