### ISSUE TITLE
Owner individualisation of mycodo

### ISSUE THREAD

**Issue by Myke974** [kizniche/Mycodo#24]
If I have multiples Raspb.pi with mycodo on each / multiples setup / multi chambers : it'll be great to be abble to personalise a bit to know immediatly on which one you are.
Perhaps a functionnality to upload a banniere with fixed valors that'll appear in see-through the header (please find example in attached picture)
![mycodo_trough01](https://cloud.githubusercontent.com/assets/1829188/10062243/bf5c9bc4-6271-11e5-89bf-d64e504fe6e6.jpg)
I used 50% opacity.
Perhaps a small logo at right but I'm totally aware when you add sensors with logs ticked they 'll need this place !

**Comment by kizniche** [comment]
I could have a setting to header text, and I could bring back gravatar support, which would display a different image based on the email of the user logged in.

**Comment by kizniche** [comment]
Fixed with commit 3b1a448
