### ISSUE TITLE
"chown: invalid user"-error during install

### ISSUE THREAD

**Issue by rowkois** [kizniche/Mycodo#240]
## Mycodo Issue Report:
  - Specific Mycodo Version:  5.0.23
 
#### Problem Description
Please list: Error during installation

  - Fresh installation on  fresh Raspbian-jessie-lite 2017-03-02 
  - Fresh install of Raspbian, updated & dist-upgraded, installation was done as described in Readme
 
### Errors
  - List any errors you encountered.
  - Copy and pasting crash logs, or link to any specific
code lines you've isolated (please use GitHub permalinks for this)

writing RSA key
Signature ok
subject=/O=mycodo/OU=mycodo/CN=mycodo
Getting Private key
chown: invalid user: ‘mycodo.mycodo’

*******************************
*** ERROR: Install Aborted! ***
*******************************

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. install Raspbian
 2. update & dist-upgrade
 3. follow installation procedure
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
I just committed the fix for this and released 5.0.24. Let me know if you still experience issues.
