### ISSUE TITLE
Can't increase display period for graph

### ISSUE THREAD

**Issue by cohe4ko** [kizniche/Mycodo#243]
#### Problem Description
Can't find any way to increase period of stats on live graphs. Maximum period is set for 86400 sec. Is there some way to increase this? Or there some issues with this?

**Comment by kizniche** [comment]
I'm not understanding the issue. What specifically are you referring to? is it  ```x-Axis (minutes)``` or ```Refresh (seconds)```?

**Comment by cohe4ko** [comment]
x-Axis (minutes)

**Comment by kizniche** [comment]
There is no limitation I'm aware of. Is there an error you're receiving?

**Comment by cohe4ko** [comment]
I can see only 86400 last seconds. Where can I change this range?
![2017-04-24 19 35 05](https://cloud.githubusercontent.com/assets/805783/25347943/377a4d4c-2925-11e7-9d0c-572feb2bf09d.png)

**Comment by kizniche** [comment]
Second or minutes? Didn't you say you were talking about the x-axis?

**Comment by kizniche** [comment]
Expand the graph options so I can see everything.

**Comment by cohe4ko** [comment]
In stats on /graph page, I see only last 24hours. 
![2017-04-24 19 40 02](https://cloud.githubusercontent.com/assets/805783/25348121/de864e9c-2925-11e7-89a7-785aeb088be0.png)

**Comment by kizniche** [comment]
You have x-axis set to 1440 minutes

**Comment by cohe4ko** [comment]
oops :) sorry for disturbing

**Comment by kizniche** [comment]
No problem. I like issues that I don't have to change the code to fix ;)

**Comment by cohe4ko** [comment]
I didn't understand that "min" means "minutes" (I thought "minimum") - maybe you can change title to "x-Axis (minutes)"

**Comment by kizniche** [comment]
Yeah, I was thinking that. I'll change it later when I get home.
