### ISSUE TITLE
Daemon periodically stop

### ISSUE THREAD

**Issue by molexuse** [kizniche/Mycodo#244]
## Mycodo Issue Report:
Mycodo Version: 5.0.27
 
#### Problem Description
Daemon periodically stop
Relay stay is in last state.
This happened sometimes on a previous versions, stopping the demon 1-3 times a month.
Last sensor log - 10:45 

### Errors
Daemon log - not errors
2017-04-22 09:36:34,866 - mycodo - INFO - 48.112 MB ram in use
2017-04-23 09:36:34,993 - mycodo - INFO - 48.6 MB ram in use
2017-04-24 09:36:35,005 - mycodo - INFO - 48.804 MB ram in use
2017-04-25 09:36:35,210 - mycodo - INFO - 49.488 MB ram in use

Http log:
[Tue Apr 25 06:25:08.298127 2017] [ssl:warn] [pid 2406:tid 1995661312] AH01906: 127.0.1.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Apr 25 06:25:08.298384 2017] [ssl:warn] [pid 2406:tid 1995661312] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 25 06:25:08.299717 2017] [wsgi:warn] [pid 2406:tid 1995661312] mod_wsgi: Compiled for Python/2.7.8.
[Tue Apr 25 06:25:08.299773 2017] [wsgi:warn] [pid 2406:tid 1995661312] mod_wsgi: Runtime using Python/2.7.9.
[Tue Apr 25 06:25:08.301806 2017] [mpm_event:notice] [pid 2406:tid 1995661312] AH00489: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t mod_wsgi/4.3.0 Python/2.7.9 configured -- resuming normal operations
[Tue Apr 25 06:25:08.301949 2017] [core:notice] [pid 2406:tid 1995661312] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 25 12:33:53.677432 2017] [wsgi:error] [pid 26586:tid 1929221168] 2017-04-25 12:33:53,676 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:34:33.751935 2017] [wsgi:error] [pid 26586:tid 1945998384] 2017-04-25 12:34:33,751 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:34:36.358403 2017] [wsgi:error] [pid 26586:tid 1937609776] 2017-04-25 12:34:36,357 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:34:55.943442 2017] [wsgi:error] [pid 26586:tid 1945998384] 2017-04-25 12:34:55,943 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:35:31.145725 2017] [wsgi:error] [pid 26586:tid 1937609776] 2017-04-25 12:35:31,145 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:35:34.858251 2017] [wsgi:error] [pid 26586:tid 1945998384] 2017-04-25 12:35:34,857 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:35:55.283775 2017] [wsgi:error] [pid 26586:tid 1937609776] 2017-04-25 12:35:55,283 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:36:04.271546 2017] [wsgi:error] [pid 26586:tid 1945998384] 2017-04-25 12:36:04,271 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:36:06.274913 2017] [wsgi:error] [pid 26586:tid 1937609776] 2017-04-25 12:36:06,274 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:36:13.091850 2017] [wsgi:error] [pid 26586:tid 1945998384] 2017-04-25 12:36:13,091 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:36:32.792729 2017] [wsgi:error] [pid 26586:tid 1937609776] 2017-04-25 12:36:32,792 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:36:36.434598 2017] [wsgi:error] [pid 26586:tid 1945998384] 2017-04-25 12:36:36,434 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:36:55.485176 2017] [wsgi:error] [pid 26586:tid 1937609776] 2017-04-25 12:36:55,484 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:36:57.224881 2017] [wsgi:error] [pid 26586:tid 1945998384] 2017-04-25 12:36:57,224 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:38:01.366964 2017] [wsgi:error] [pid 26586:tid 1937609776] 2017-04-25 12:38:01,366 URL for 'daemon_active' raised and error: Connection refused. Is the daemon running?
[Tue Apr 25 12:38:57.655667 2017] [wsgi:error] [pid 26586:tid 1945998384] 2017-04-25 12:38:57,655 URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?

### Sensors
3 sensors in system
![sens](https://cloud.githubusercontent.com/assets/26825704/25379223/03313bdc-29b5-11e7-8474-95bc16845987.png)

**Comment by kizniche** [comment]
```URL for 'inject_mycodo_version' raised and error: Connection refused. Is the daemon running?``` is an expected error if the daemon isn't running or responding if the web UI is attempting to query it to display the proper color indicator at the top left (red/green).

I have several development systems, with the same sensors, that have multi-month uptimes and the daemons haven't spontaneously stopped. This is most likely something specific to your particular setup and not Mycodo. See [Mycodo 4.1.16 daemon crashes after a few days and does not automatically restart](https://github.com/kizniche/Mycodo/issues/198), as this appears to be a duplicate issue. Please comment in that thread with any new information.
