### ISSUE TITLE
different width of relay and temperature parts in sensor tab

### ISSUE THREAD

**Issue by boomstick8x** [kizniche/Mycodo#26]
Relay and temperature blocks in sensor tab in case of css .sensor-parent{float: left and width: auto} are different width, and if I`m not wrong, removing float will solve this situation.
And if it so, then in css table.relays{display: table; margin-right: auto; margin-left: auto; width: 100%;} will solve the last part of positioning.

**Comment by kizniche** [comment]
Thanks! I made some adjustments and it looks better. Pushed in commit https://github.com/kizniche/Mycodo/commit/7bf536891894b76540b1fb34a769ef7141c58603
