### ISSUE TITLE
Can save pid change 

### ISSUE THREAD

**Issue by jeffyboz** [kizniche/Mycodo#272]
## Mycodo Issue Report:
  - Specific Mycodo Version:
5.0.46
 
#### Problem Description
Please list:
Can't save max on max off for PID ID 1

 
### Errors
<img width="1238" alt="pid_error" src="https://user-images.githubusercontent.com/966487/28030078-3c0567de-6570-11e7-8700-59079e14cba6.png">

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. step 1
PID - change rise min on or max on or min off, then save.

 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
I wasn't able to reproduce this. This may be a lingering effect of an install gone wrong. Try this command to make your database writable again:

```
sudo /bin/bash ~/Mycodo/mycodo/scripts/upgrade_commands.sh initialize
```

**Comment by kizniche** [comment]
I believe this issue was fixed by the command in the previous comment. Please open if the issue persists.
