### ISSUE TITLE
DS18B20 in schematic manual

### ISSUE THREAD

**Issue by wangine** [kizniche/Mycodo#285]
Is not a issue but can be a problem if someones (without to much knowledge) will try to connect an ds18B20 sensor like in schematic manual. 
The ds18B20 pinout should be  , 1 = GND 2 = DQ 3 = Vcc and in that picture is inversed.
https://github.com/kizniche/Mycodo/blob/master/manual_images/Schematic-Pi-4-relays.png
Thanks

**Comment by kizniche** [comment]
I made a few edits. I'll upload it soon. Thanks.

![schematic-pi-4-relays](https://user-images.githubusercontent.com/838427/31721163-a4fd57e6-b3e6-11e7-9504-d4e320c2bd95.png)
