### ISSUE TITLE
AM2315 negatives values in graph view

### ISSUE THREAD

**Issue by Ericktz** [kizniche/Mycodo#287]
![captura de pantalla 2017-08-16 a las 23 16 47](https://user-images.githubusercontent.com/2304258/29393331-79d74646-82d9-11e7-8985-5e55380c4534.png)
version 5.1.6

in live graph page, the values of measurements apparently seem wrong, in some cases two or more consecutively values are high values of relative humidity(1000-2000%), and in temperature shows negative values (-3000º).... 

in live stats, all apparently seems ok.... 

![captura de pantalla 2017-08-16 a las 23 09 02](https://user-images.githubusercontent.com/2304258/29393314-7153a028-82d9-11e7-8629-b0c450c97ead.png)
![captura de pantalla 2017-08-16 a las 23 16 32](https://user-images.githubusercontent.com/2304258/29393315-7158765c-82d9-11e7-94ba-54fe3a7b686b.png)

**Comment by kizniche** [comment]
My AM2315 sensor with Mycodo 5.1.6 isn't displaying this behavior. Try deleting the sensor and adding it again and see if the issue persists.

**Comment by kizniche** [comment]
Additionally, try rebooting your Pi.

**Comment by kizniche** [comment]
This may be a sensor issue. Do you have a second sensor that you can use to verify the behavior? Have you ran other code (non-Mycodo) and does it display the same results?
