### ISSUE TITLE
I cant upgrade 5.0.49 for latest 5.1.6

### ISSUE THREAD

**Issue by molexuse** [kizniche/Mycodo#288]
## Mycodo Issue Report:
  - Specific Mycodo Version:
 5.0.49
#### Problem Description
Try to Upgrade to Latest version: 5.1.6
Message - Success: The upgrade has started. The daemon will be stopped during the upgrade.
But not upgrade. I deleted file  ~/Mycodo/.upgrade but nothing happens, try it again.
Upgrade log is old
Trying to upgrade system files and run upgrade but nothing happens.

**Comment by kizniche** [comment]
Please attach the excerpt from the last upgrade attempt from the upgrade log.

**Comment by molexuse** [comment]
[mycodoupgrade.log.txt](https://github.com/kizniche/Mycodo/files/1232461/mycodoupgrade.log.txt)

**Comment by kizniche** [comment]
How long did you give the upgrade before doing anything to the Pi?

**Comment by molexuse** [comment]
5-15 min.
Shutdown and restart command in web interface also don`t work.
In console work. 
Maybe me start upgrade  from the console?

**Comment by kizniche** [comment]
I understand there is an issue. If you please answer the questions I ask, I can better understand what happened and potentially fix the issue.

**Comment by kizniche** [comment]
Try this from the command line:

```sudo /bin/bash ~/Mycodo/mycodo/scripts/upgrade_post.sh```

**Comment by molexuse** [comment]
sudo /bin/bash ~/Mycodo/mycodo/scripts/upgrade_mycodo_release.sh
with this command upgrade is successful!

**Comment by kizniche** [comment]
Good to hear.
Not sure what happened during your upgrade, but the upgrade log was corrupt at the end, so I assume it was abnormal.
