### ISSUE TITLE
Adding Async Graphs Do Nothing

### ISSUE THREAD

**Issue by pukkita** [kizniche/Mycodo#296]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.2.4 (2017-10-05)

 
#### Problem Description

Adding Live Graphs works fine, added a DHT22 and RPi sensors.

However when trying to add an Async Graph however, nothing happens; the browser sends the request and loads the page back, but no graphs are added.

### Errors
- Nothing on any logs. Neither mycodo's, nor apache's.

### Steps to Reproduce the issue:

 1. Install Raspberry (NOOBS Lite 2.4) and apt-update, upgrade etc.
 2. Follow Mycodo's install procedure
 3. Add sensors
 4. Try to add Async Graphs.

#### Additional Details:
- Tried Firefox, Safari and Chrome. 
- Spanish Locale.

**Comment by kizniche** [comment]
Can you please post a screenshot of this "add async graph" option?

**Comment by pukkita** [comment]
Sure:

![screenshot](https://user-images.githubusercontent.com/32773513/31562306-32df25ba-b05b-11e7-9008-a18cd287678e.png)

**Comment by kizniche** [comment]
Thanks. I'll look into it when I can access my development Pi later today.

**Comment by pukkita** [comment]
Impressive job BTW. Loved your blog, and of course mycodo, was going to do it manually myself, but did a search anb when I found your Mycodo project felt like Santa's paid me a visit!! thanks for sharing this project!

**Comment by kizniche** [comment]
Thanks. It's been a fun project. I wish I could put as much time into it as I used to. I do enjoy hearing that other people find it useful.

This issue should now be fixed in the latest release (v5.2.5). Let me know if the issue persists after you upgrade.
