### ISSUE TITLE
Documentation: "Diagnosing Issues" section minor typo

### ISSUE THREAD

**Issue by pukkita** [kizniche/Mycodo#298]
### Where

https://github.com/kizniche/Mycodo/wiki/Diagnosing-Issues

### Start the daemon in debug mode:

```sudo ~/Mycodo/env/python ~/Mycodo/mycodo/mycodo_daemon.py --debug```

Should be 

```sudo ~/Mycodo/env/bin/python ~/Mycodo/mycodo/mycodo_daemon.py --debug```

Similarly, to terminate the daemon:

```~/Mycodo/env/python ~/Mycodo/mycodo/mycodo_client.py --terminate```

Should be

```~/Mycodo/env/bin/python ~/Mycodo/mycodo/mycodo_client.py --terminate```

(Missing `bin`in the python path)

**Comment by kizniche** [comment]
Thanks! Fixed.
