### ISSUE TITLE
Allow PID to use both Relay and PWM Outputs

### ISSUE THREAD

**Issue by kizniche** [kizniche/Mycodo#303]
Currently, a single PID can use only Relay Outputs or only PWM Outputs. I would like to allow a PID to be able to use both, for such applications as temperature regulation using an air conditioner actuated by a relay turning on for durations of time and a heater controlled by a PWM signal.

**Comment by pukkita** [comment]
That would be awesome!

**Comment by kizniche** [comment]
Okay, I had some time after work while waiting to go home that I knocked out what I believe to be all that's needed for PIDs to be able to use any type of output. I'll test when I get home, but be advised if you're pulling from the latest commit form master that it's untested and may not work.

**Comment by kizniche** [comment]
There were definitely issues with the latest commit. I'm slowly fixing the issues. Here's one that made me chuckle:

![screenshot-192 168 0 5-2017-10-26-20-21-25](https://user-images.githubusercontent.com/838427/32082705-6bfe37c0-ba8b-11e7-96cc-22fe9858ab05.png)

**Comment by kizniche** [comment]
Alright, I think I have it at a working state. I'm going to call it a night.
