### ISSUE TITLE
Sql Alchemy Error after upgrade

### ISSUE THREAD

**Issue by RynFlutsch** [kizniche/Mycodo#312]
Hello Kyle

## Mycodo Issue Report:
  - Specific Mycodo Version:
upgrade from 5.3.3 to 5.3.5

Is it possible fix this without the need of a fresh install?

Thank You

![ee82c45c-8d11-4207-8d83-4b2beca6d9a7](https://user-images.githubusercontent.com/29811876/32692516-7b00b03c-c719-11e7-9540-11b06076308c.png)

**Comment by kizniche** [comment]
It looks like your database wasn't upgraded. Use the following command and then reboot.

cd ~/Mycodo/database && sudo ~/Mycodo/env/bin/alembic upgrade head

**Comment by RynFlutsch** [comment]
Great fix, thank you!

**Comment by kizniche** [comment]
You're welcome. Glad it was an easy fix.

Could you attach the end of your upgrade log (from when the last upgrade started to the end) so I may inspect it for what went wrong and find any potential issues with the Mycodo upgrade process?

**Comment by RynFlutsch** [comment]
I think its not possible, but i can watch monday.

It startet with the missing python-fasteners.
After i added that, the sql error occurred.

**Comment by kizniche** [comment]
You can access the log in the Mycodo menu: Config -> Mycodo Logs -> Upgrade Log
