### ISSUE TITLE
Edit Timer dont works

### ISSUE THREAD

**Issue by Ericktz** [kizniche/Mycodo#318]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.3.4
 
#### Problem Description
for example a Daily Time Point timer, for switch ON one relay for X sec. I created one, with start at 12:00 and 1000 sec.. the timer does as scheduled.. but when I trying modified the seconds that are a turn on... no change occurred and no status green/red feedback on top of page

**Comment by kizniche** [comment]
Thanks. I'll look into this.

**Comment by kizniche** [comment]
dea8332 is the actual commit with the fix, fyi

I haven't tested this, but as soon as I do I'll make a new release for all to upgrade to.
