### ISSUE TITLE
Error changing theme for current user

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#326]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.4.4
 
#### Problem Description
On fresh install, set the new theme, then click save.
 
### Errors
Error: Modify User admin: Cannot change currently-logged in user's role from Admin
 
### Additional Notes
Since everything was humming along nicely, I did not bother to upgrade (still on 5.0.17 on production system). Checked the issue on that system, I could change the theme for the current user without error.

BTW,  your constant improvement of this project  is amazing! Although I did not actively participate, regularly follow the issues coming up. Can't wait to test the new LCD features...

**Comment by kizniche** [comment]
Thanks for the bug report. I just released v5.4.6 with this fix and some LCD updates.

I should have made these updates sooner. The LCDs got a lot more useful. And now the Max Age option will cause them to show ```NO DATA``` if the measurement is older than what's set, so you can immediately tell if it's not working without having to read the timestamp and calculate in your head how long ago the measurement was.
