### ISSUE TITLE
Pi Zero Install Error / High CPU Usage

### ISSUE THREAD

**Issue by jacopienaar** [kizniche/Mycodo#329]
## Mycodo Issue Report:
  - Specific Mycodo Version: Latest
 
#### Problem Description
Install aborted during installation of latest version of Mycodo on Pi Zero W - see info below.  I found a workaround to it . . . .

I swopped the SD card to my Pi3 (currently have Mycodo running on it) and did the successfully completed the install on it. After placing the SD back in the Zero, the CPU is now constantly running at 30-40% when idle (vanilla Raspbian install with only Mycodo and VNC running) and when I try to do anything else (like opening a browser) it maxes out at 100% usage - rendering the Pi Zero useless. This was not the case before installing Mycodo. Note that Mycodo is not even running yet as I haven't logged in. Does Mycodo have anything running in the background that will use resources?

I also inserted the Pi3 SD card (with Mycodo running perfectly) in the Pi Zero W and same thing - can't do anything on it due to 100% CPU usage. Can this be Mycodo causing it?

After managing to log in I saw that the Daemon is not running -  ran the debug script which fixed it. So eventually I got everything running as it should with all interlocks working - problem is - even when idle - CPU usage is between 45%-90% with Chrome closed and no other programs (except VNC) running.

### Errors

#Start of error . . . . 
```
  Running setup.py install for pi-switch: started
    Running setup.py install for pi-switch: still running...
    Running setup.py install for pi-switch: finished with status 'error'
    Complete output from command /home/pi/Mycodo/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-uHk2CM/pi-switch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8uWhn_-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/Mycodo/env/include/site/python2.7/pi-switch:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv6l-2.7
    creating build/lib.linux-armv6l-2.7/pi_switch
    copying pi_switch/__init__.py -> build/lib.linux-armv6l-2.7/pi_switch
    running build_ext
    building '_pi_switch' extension
    creating build/temp.linux-armv6l-2.7
    creating build/temp.linux-armv6l-2.7/pi_switch
    creating build/temp.linux-armv6l-2.7/pi_switch/wrapper
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c pi_switch/wrapper/pi_switch.cpp -o build/temp.linux-armv6l-2.7/pi_switch/wrapper/pi_switch.o -Wno-write-strings
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    arm-linux-gnueabihf-gcc: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 4
    
    ----------------------------------------
Command "/home/pi/Mycodo/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-uHk2CM/pi-switch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8uWhn_-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/Mycodo/env/include/site/python2.7/pi-switch" failed with error code 1 in /tmp/pip-build-uHk2CM/pi-switch/

*******************************
*** ERROR: Install Aborted! ***
*******************************

An error occurred that prevented Mycodo from being installed!

Please contact the developer by submitting a bug report at
https://github.com/kizniche/Mycodo/issues with the pertinent
excerpts from the setup log located at Mycodo/install/setup.log

An error occurred. Exiting...
```

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. Tried to install it twice - same issue occurred 
 
### Additional Notes
Thanks for developing this amazing little program! I grow oyster mushrooms at home and this has enabled me to control my environmentals and resulted in better and bigger flushes!

**Comment by kizniche** [comment]
Have you tried using a new SD card? Not just swapping with one Raspbian/Mycodo is already installed on, but a new card and a fresh install of Raspbian. I suspect your SD card may be damaged, causing file corruption.

Oysters are delicious. Do you have any photos you can share?

**Comment by kizniche** [comment]
Mycodo is comprised of a backend (daemon) and frontend (web user interface). The daemon is always running in the background, however if no controllers (inputs/outputs/PIDs/etc.) have been added, it's virtually doing nothing.

Use the ```top``` command to see what process(es) are utilizing your CPU.

**Comment by kizniche** [comment]
Also, I don't have a Pi Zero to test/optimize Mycodo, so I can't do my own testing with this to discover an issue.

**Comment by kizniche** [comment]
Have you had a chance to run ```top``` to determine what the CPU hogs are? I'd be interested to see the output.

**Comment by jacopienaar** [comment]
The SD card used is brand new but I have read that people with similar CPU usage issues on Pi Zero have had it resolved by using a different card. I will only be able to try this in January as I am about to leave for the holidays. Then I will see if I can install Mycodo directly onto the Zero and also if this resolves the CPU usage issue

The top two commands sucking CPU life is both Mycodo - I'll attach a screenshot in the next post. 

There is unfortunately not much to show at the moment as my cakes are all spent and I am packing all away until I get back. I've attached some pics of a few weeks back - species is Pleurotus Pulmonarius
![img_5334](https://user-images.githubusercontent.com/33920783/33717043-e7ff5398-db71-11e7-9baa-7c0bf44617e8.JPG)
![img_5145](https://user-images.githubusercontent.com/33920783/33717047-ec8f7fc8-db71-11e7-8f3b-380138776712.JPG)

**Comment by jacopienaar** [comment]
![2017-12-07-165940_1280x720_scrot](https://user-images.githubusercontent.com/33920783/33719949-da9aa360-db7b-11e7-8d21-4ca3c66f5457.png)

**Comment by kizniche** [comment]
Those are some nice mushrooms!

Your screenshot has the first line of ```top``` cut off that has the CPU load, but from the CPU usage, it appears normal... Only a little over 50% CPU usage.

**Comment by kizniche** [comment]
Using a GUI will have a considerable load on the OS, though. For a Pi Zero, I would suggest turning the GUI off and running it headless. All but one of my 4 Pis run headless (Pi 1, 2, and 3), with the other Pi 3 onlt running X because it has a 7-inch touchscreen attached to the front of the [electrical box](https://hackaday.io/project/11997-mycodo-environmental-regulation-system/log/42201-power-output-and-mounting-options) all the components are stored in.

**Comment by fry42** [comment]
Hi!
I recently installed on a zero w and thought I'd share my findings, maybe it helps:
- Installed raspbian stretch lite Nov17 (=no GUI)
- updated to the most recent packages (apt-get update/upgrade)
- installed Mycodo
The install script returned a success after 1min30, but not much was installed. Investigating the logs showed that one of the sources servers had a hickup and reported a internal server error.
Running the script a second time resulted in a working installation, after about 30min.

So the only bug would be that the install script didn't catch the failed installation attempt.
The CPU load was around 50% and the Interface felt a little slow & sluggish.
My conclusion was that the 1GHz single core CPU wasn't quite up to the task. Switching to a quad-core 1,2GHz Pi3 improved things :)

**Comment by kizniche** [comment]
Thanks for the feedback. What part did the install fail on? Could you paste the relevant part of the setup.log?

**Comment by fry42** [comment]
Sorry, I don't have the logs anymore...
It was right at the beginning, when your setup script calls for updating the sources lists.

If it helps I could try the same setup again, my zero is currently not in use...

**Comment by kizniche** [comment]
Don't worry about it. Install issues related to internet connectivity are rare. Most of the time the issue can be solved by rerunning the setup command. I put a good effort into making the setup.sh able to be executed multiple times without issue (where before this would be problematic). If I see more github issues appear, I'll investigate it.

**Comment by kizniche** [comment]
BTW, there's a log generated when the setup.sh is ran, located in ~/Mycodo/install/setup.log

**Comment by zsole2** [comment]
With the new minimal install, my Pi Zeros run quite great, the idle time is up to 80-90% before adding anything. Then as the functionality increases, the load and CPU usage increases proportionally. My latest hunch is that the most strain is coming from data presentation (Dashboard), rather than the effector functionality (Inputs/Outputs/PIDs), but will need to test this hypothesis more systematically. If it's true, a push for the CLI interface (#17) would be in order.
