### ISSUE TITLE
Edit Timer Error

### ISSUE THREAD

**Issue by RynFlutsch** [kizniche/Mycodo#334]
## Mycodo Issue Report:
  - Specific Mycodo Version:
 5.4.8 & 5.4.9
#### Problem Description
Please list:
Edit TimeSpan Timer result in error.
 
### Errors

![28158902-2ca3-47f7-b0c3-87ef905c67da](https://user-images.githubusercontent.com/29811876/33340211-cb0a1694-d47b-11e7-95b5-e564a94c1c77.jpeg)

### Steps to Reproduce the issue:
Create TimeSpan Timer and than try to edit.

**Comment by kizniche** [comment]
Thanks. I'll make a new release with a fix by the end of the night.
