### ISSUE TITLE
Humidity/Temperature sensors : Presets buttons "Save" & "New" Bug

### ISSUE THREAD

**Issue by Myke974** [kizniche/Mycodo#34]
when either of thoses 2 buttons are clicked the result is a white page

**Comment by kizniche** [comment]
Did you put in a name?

**Comment by kizniche** [comment]
Oh,  a white page. I'll try to reproduce this. What type of sensor?

**Comment by kizniche** [comment]
Sounds like an SQL or PHP error.

**Comment by kizniche** [comment]
[Wed Sep 30 17:08:42 2015] [error] [client 66.87.3.198] PHP Warning:  SQLite3::prepare(): Unable to prepare statement: 1, 49 values for 51 columns in /home/eville/Mycodo/3.5/includes/restricted.php on line 1218
[Wed Sep 30 17:08:42 2015] [error] [client 66.87.3.198] PHP Fatal error:  Call to a member function bindValue() on a non-object in /home/eville/Mycodo/3.5/includes/restricted.php on line 1219

**Comment by kizniche** [comment]
Fixed https://github.com/kizniche/Mycodo/commit/f8127c22234256025baf87aa0dd8ba31f619aba0
