### ISSUE TITLE
Gauge Change / Math

### ISSUE THREAD

**Issue by RynFlutsch** [kizniche/Mycodo#342]
## Mycodo Issue Report:
  - Specific Mycodo Version:
 5.4.15
#### Problem Description
Please list:
Created Solid Gauge und tried to change to angular Gauge resulted in "Modify Graph 'low' error"
 
Could you implement Math for Gauges please?

**Comment by kizniche** [comment]
Thanks. I'll look into this.

**Comment by kizniche** [comment]
All done. I'll try to get this release out by this weekend. I almost tested everything and have all the issues with the new Math controllers ironed out.

**Comment by RynFlutsch** [comment]
Great
