### ISSUE TITLE
BME280 missing in 5.5

### ISSUE THREAD

**Issue by Theoi-Meteoroi** [kizniche/Mycodo#358]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.5.0
 
#### Problem Description
Please list:  

BME / BMP 280 missing from installed sensors.  Compile lines missing in setup.log
 
### Errors
  
Error: Could not activate Input controller with ID 3: No module named 'Adafruit_BME280'

### Steps to Reproduce the issue:

1. Add sensor BME 280
2. Attempt to activate sensor

 
### Additional Notes

[setup.log](https://github.com/kizniche/Mycodo/files/1586335/setup.log)

Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
Whoops. Sorry about that. I missed them when developing the python 3 requirements.txt. I'll make a 5.0.1 release before I go to sleep that includes the BME280  and the TSL2591 (which I also accidentally left out)
