### ISSUE TITLE
DHT11 doesn't show result on web

### ISSUE THREAD

**Issue by r1rider01** [kizniche/Mycodo#370]
## Mycodo Issue Report:
  - Specific Mycodo Version:  5.5.4
 
#### Problem Description
Please list:  DHT11 doesn't display anything, deamon log shows error

  - what were you trying to do
  - specific setup details that are involved
 
### Errors
  - List any errors you encountered.
  - Copy and pasting crash logs, or link to any specific
code lines you've isolated (please use GitHub permalinks for this)

ERROR: 2018-01-04 09:02:06,949 - mycodo.inputs.dht11_4 - ERROR - Could not initialize sensor. Check if gpiod is running. Error: 'NoneType' object has no attribute 'send'

 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

Running the manual test 
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ sudo python test_gpio_DHTx.py -g 3 DHT11

works

pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ sudo python test_gpio_DHTx.py -g 3 DHT11
Temperature: 17.0
Humidity: 48.0
Temperature: 17.0
Humidity: 46.0
Temperature: 17.0
Humidity: 53.0
Temperature: 17.0
Humidity: 53.0
Temperature: 17.0
Humidity: 53.0
Temperature: 17.0
Humidity: 53.0
Temperature: 17.0
Humidity: 53.0
Temperature: 17.0
Humidity: 53.0
Temperature: 17.0
Humidity: 53.0
Temperature: 17.0
Humidity: 53.0

**Comment by kizniche** [comment]
Can you verify if gpiod is running? execute ```ps aux | grep gpiod```

**Comment by r1rider01** [comment]
I know its running, because the test works just fine.  Here is output:


pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ ps aux | grep gpiod
pi        2462  0.0  0.0   4372   556 pts/0    S+   09:16   0:00 grep --color=auto gpiod

**Comment by kizniche** [comment]
The test script is much older than the current DHT sensor module in Mycodo, and does not use gpiod. Your ```ps``` command output indicates gpiod is not running.

What is returned when you execute ```sudo pigpiod```?

This is what you should see if gpiod is running:

```
pi@delta:~ $ ps aux|grep gpiod
root       477 21.6  0.1  20440  1524 ?        SLsl Jan03 170:17 /usr/local/bin/pigpiod -s 1
pi       26022  0.0  0.0   4380   560 pts/1    S+   10:16   0:00 grep --color=auto gpiod
```

**Comment by r1rider01** [comment]
sudo pigpiod, returned nothing, but then when running
grep gpiod i now get

pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ ps aux | grep gpiod
root      2561  6.5  0.1   9896  1508 ?        SLsl 09:28   0:03 pigpiod
pi        2588  0.0  0.0   4372   528 pts/0    S+   09:28   0:00 grep --color=auto gpiod

**Comment by r1rider01** [comment]
Ok now getting this error:

2018-01-04 09:31:46,234 - mycodo.input_4 - ERROR - StopIteration raised. Possibly could not read input. Ensure it's connected properly and detected.

**Comment by kizniche** [comment]
can you open your cron file and paste the contents? Open it with ```sudo crontab -e```

**Comment by r1rider01** [comment]
# cmID:mycodo #
@reboot /usr/local/bin/pigpiod -s 1 &
# cm~mycodo #
# cmID:restart_daemon #
@reboot /var/mycodo-root/env/bin/python /var/mycodo-root/mycodo/scripts/restart_daemon.py --continuouscheck &
# cm~restart_daemon #

**Comment by r1rider01** [comment]
`# cmID:mycodo #
@reboot /usr/local/bin/pigpiod -s 1 &
# cm~mycodo #
# cmID:restart_daemon #
@reboot /var/mycodo-root/env/bin/python /var/mycodo-root/mycodo/scripts/restart_daemon.py --continuouscheck &
# cm~restart_daemon #
`

**Comment by kizniche** [comment]
Can you download this file: https://github.com/joan2937/pigpio/blob/master/EXAMPLES/Python/DHT11_SENSOR/dht11.py

Then edit line 157 so it is your DHT11 data pin, instead of "4", then run it and let me know if it works?

**Comment by r1rider01** [comment]
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ python dht11.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/pigpio.py", line 1134, in run
    cb.func(cb.gpio, newLevel, tick)
  File "dht11.py", line 69, in either_edge_callback
    handler(tick, diff)
  File "dht11.py", line 91, in _edge_RISE
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

temperature: 17
humidity: 57
temperature: 17
humidity: 57
temperature: 17
humidity: 57
temperature: 17
humidity: 57

**Comment by kizniche** [comment]
Is that what happened? It threw an exception, but then output temp/humidity data? That's weird.

**Comment by r1rider01** [comment]
correct, that is copy/paste

**Comment by kizniche** [comment]
Can you run it with python 3 from the Mycodo virtualenv to test if it works with python 3?

```
sudo ~/Mycodo/env/bin/python dht11.py
```

**Comment by r1rider01** [comment]
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ sudo ~/Mycodo/env/bin/python dht11.py
Traceback (most recent call last):
  File "dht11.py", line 158, in <module>
    for d in sensor:
TypeError: iter() returned non-iterator of type 'DHT11'
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $

**Comment by kizniche** [comment]
Let me see if I can get it working with python 3 (what Mycodo now runs with as of v5.5.0).

**Comment by r1rider01** [comment]
Can i downgrade mycodo?  or just wait?

**Comment by kizniche** [comment]
To what version?

**Comment by r1rider01** [comment]
i can wait, not a rush really.   eta on update?

**Comment by kizniche** [comment]
I'll try to get something for you to test in the next hour.

**Comment by r1rider01** [comment]
Kyle i appreciate your dedication and quick responses!

**Comment by kizniche** [comment]
Are you able and willing to give me SSH access to your Pi to perform tests? It will be much quicker for me to just upload a test script and perform tweaks until I can get it working, than to go back-and-forth here with test scripts. Though, I understand if it's a difficulty or a security risk to let a stranger have access to your Pi.

**Comment by kizniche** [comment]
I think I got rid of that exception. Change "next(self)" on line 143 to "__next__(self)"

This is the same code I used in Mycodo, so I'm looking for what can be causing the issue.

**Comment by kizniche** [comment]
Before we get deep into changing code, try deactivating your sensor, then activating it again, in Mycodo.

**Comment by r1rider01** [comment]
I would allow SSH but my firewall doesn't allow me to open ports.  sorry.

Ive deactivated and re activated non stop even rebooted, changed GPIO ports, etc..

**Comment by r1rider01** [comment]
your line 143 change is the same thing....  next(self)   what am i changing?

**Comment by kizniche** [comment]
The line 143 change is for the test script I mentioned, at https://github.com/joan2937/pigpio/blob/master/EXAMPLES/Python/DHT11_SENSOR/dht11.py

**Comment by kizniche** [comment]
Just to confirm, since we started pigpiod and confirmed it was running, you have deactivated the DHT11 sensor and activated it again, in Mycodo?

**Comment by r1rider01** [comment]
correct

**Comment by r1rider01** [comment]
i see line 143   but it already says  next(self)    what does it need to change to?

**Comment by kizniche** [comment]
Change the next() in the test script to include the underscores, as it is [here](https://github.com/kizniche/Mycodo/issues/370#issuecomment-355329919)

**Comment by r1rider01** [comment]
Kyle i must be missing something this is what i see in your comment:


I think I got rid of that exception. Change "next(self)" on line 143 to "next(self)"


I don't see any _ underscores

**Comment by kizniche** [comment]
Refresh your browser. You are seeing an old comment.

**Comment by r1rider01** [comment]
DOH

**Comment by r1rider01** [comment]
ok even after that change:


pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ sudo ~/Mycodo/env/bin/python dht11.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/pigpio.py", line 1134, in run
    cb.func(cb.gpio, newLevel, tick)
  File "dht11.py", line 69, in either_edge_callback
    handler(tick, diff)
  File "dht11.py", line 91, in _edge_RISE
    raise
RuntimeError: No active exception to reraise

temperature: 17
humidity: 68
temperature: 17
humidity: 68
temperature: 17
humidity: 68

**Comment by kizniche** [comment]
Okay. Change line 91 from:

```python
                    raise
```

to

```python
                    raise Exception
```

This should get rid of the exceptions. I'm still struggling to find any discernible differences from the test code and the Mycodo code.

**Comment by kizniche** [comment]
What pin is your DHT11 on? I'm making a test script to try.

**Comment by r1rider01** [comment]
```
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ sudo ~/Mycodo/env/bin/python dht11.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/pigpio.py", line 1134, in run
    cb.func(cb.gpio, newLevel, tick)
  File "dht11.py", line 69, in either_edge_callback
    handler(tick, diff)
  File "dht11.py", line 91, in _edge_RISE
    raise Exception
Exception

temperature: 17
humidity: 53
temperature: 17
humidity: 53
temperature: 17
humidity: 53
```

**Comment by r1rider01** [comment]
PIN 3

**Comment by kizniche** [comment]
[dht11_test01.txt](https://github.com/kizniche/Mycodo/files/1604087/dht11_test01.txt)

Rename this txt file to .py, then run with:

~/Mycodo/env/bin/python3 dht11_test01.py

**Comment by r1rider01** [comment]
```
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ sudo ~/Mycodo/env/bin/python dht11_test01.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/pigpio.py", line 1134, in run
    cb.func(cb.gpio, newLevel, tick)
  File "dht11_test01.py", line 225, in either_edge_callback
    handler(tick, diff)
  File "dht11_test01.py", line 250, in _edge_rise
    self.temp_humidity = (self.temp_humidity << 1) + val
TypeError: unsupported operand type(s) for <<: 'NoneType' and 'int'

Traceback (most recent call last):
  File "dht11_test01.py", line 287, in <module>
    print(test.next())
  File "dht11_test01.py", line 80, in next
    raise StopIteration  # required
StopIteration
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $
```

**Comment by r1rider01** [comment]
sorry didn't run with python3   here is python3

```

pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ sudo ~/Mycodo/env/bin/python3 dht11_test01.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/pigpio.py", line 1134, in run
    cb.func(cb.gpio, newLevel, tick)
  File "dht11_test01.py", line 225, in either_edge_callback
    handler(tick, diff)
  File "dht11_test01.py", line 250, in _edge_rise
    self.temp_humidity = (self.temp_humidity << 1) + val
TypeError: unsupported operand type(s) for <<: 'NoneType' and 'int'

Traceback (most recent call last):
  File "dht11_test01.py", line 287, in <module>
    print(test.next())
  File "dht11_test01.py", line 80, in next
    raise StopIteration  # required
StopIteration
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $
```

**Comment by kizniche** [comment]
They're the same executable, so it shouldn't matter, as long as it's one of the python executables in the env/bin directory.

Try this: [dht11_test02.txt](https://github.com/kizniche/Mycodo/files/1604135/dht11_test02.txt)

**Comment by kizniche** [comment]
I think we're close. I can feel it's going to work very soon.

**Comment by r1rider01** [comment]
```
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ sudo ~/Mycodo/env/bin/python3 dht11_test02.py             {'temperature': 0.0, 'humidity': 0.0, 'dewpoint': 0.0}
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $
```

**Comment by kizniche** [comment]
Try this: [dht11_test03.txt](https://github.com/kizniche/Mycodo/files/1604161/dht11_test03.txt)

**Comment by r1rider01** [comment]
```
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $ sudo ~/Mycodo/env/bin/python3 dht11_test03.py             
Exception raised when taking a reading: Bad Checksum.
{'dewpoint': 0.0, 'humidity': 60.0, 'temperature': 17.0}
pi@raspberrypi:~/Mycodo/mycodo/tests/manual_tests $
```

**Comment by kizniche** [comment]
Great! Found the issue. Let me put together the code you can replace Mycodo/mycodo/inputs/dht11.py with and see if it will work within Mycodo.

**Comment by kizniche** [comment]
Replace your Mycodo/mycodo/inputs/dht11.py with the contents of [dht11.txt](https://github.com/kizniche/Mycodo/files/1604177/dht11.txt), then restart the daemon with ```sudo service mycodo restart``` and see if measurements start coming in.

**Comment by kizniche** [comment]
You may also need to change line 263 from:

```python
                    self.logger.exception(
```

to

```python
                    self.logger.debug(
```

**Comment by r1rider01** [comment]
:-( 

```
2018-01-04 11:45:18,356 - mycodo.input_4 - ERROR - StopIteration raised. Possibly could not read input. Ensure it's connected properly and detected.
```

**Comment by r1rider01** [comment]
oh wait the GPIO thing

**Comment by r1rider01** [comment]
nope thats still running:

```
pi@raspberrypi:~/Mycodo/mycodo/inputs $ ps aux | grep gpiod
root      2561  6.2  0.1  12456  1528 ?        SLsl 09:28   8:39 pigpiod
pi        3863  0.0  0.0   4372   568 pts/0    S+   11:46   0:00 grep --color=auto gpiod
```

**Comment by kizniche** [comment]
Did you change the logger line as well?

**Comment by r1rider01** [comment]
yes

**Comment by r1rider01** [comment]
pretty sure i can't run the file like this, but just incase?


```
pi@raspberrypi:~/Mycodo/mycodo/inputs $ sudo ~/Mycodo/env/bin/python3 dht11.py
Traceback (most recent call last):
  File "dht11.py", line 5, in <module>
    from mycodo.databases.models import Output
ImportError: No module named 'mycodo'
pi@raspberrypi:~/Mycodo/mycodo/inputs $
```

**Comment by kizniche** [comment]
no, there are dependencies in the module that requires it be run from the mycodo daemon. The previous test scripts I modified to run independently. Give me a min to find any potential issues with my edits that didn't translate well from the test script to the mycodo module.

**Comment by kizniche** [comment]
Can you modify the next() function in dht11.py, line 87 and beyond, so it includes a logging line, like this:

```python
    def next(self):
        """ Get next measurement reading """
        if self.read():  # raised an error
            self.logger.error("TEST01: {}, {}, {}".format(self._dew_point, self._humidity, self._temperature))
            raise StopIteration  # required
        return dict(dewpoint=float('{0:.2f}'.format(self._dew_point)),
                    humidity=float("{0:.2f}".format(float(self._humidity))),
                    temperature=float("{0:.2f}".format(float(self._temperature))))
```

**Comment by kizniche** [comment]
Make sure you restart the mycodo daemon for it to take effect, after saving, using ```sudo service mydodo restart```

**Comment by kizniche** [comment]
Also, deactivate and reactivate the sensor after the daemon has fully restarted.

**Comment by r1rider01** [comment]
weird now getting:

```
pi@raspberrypi:~/Mycodo/mycodo/inputs $ sudo service mycodo restart
Job for mycodo.service failed because the control process exited with error code.
See "systemctl status mycodo.service" and "journalctl -xe" for details.
```

**Comment by kizniche** [comment]
You probably made an error in editing the code. If the daemon can't start, it will give that error.

**Comment by r1rider01** [comment]
2018-01-04 12:08:15,962 - mycodo.inputs.dht11_4 - ERROR - TEST01: None, None, None

**Comment by kizniche** [comment]
Try this dht11.py module: [dht11.txt](https://github.com/kizniche/Mycodo/files/1604293/dht11.txt)

**Comment by r1rider01** [comment]
```
DHT11 Input (4)
Input (DHT11), 15.0 second interval
Measurement | Timestamp
17 °C (62.60 °F) | 2018/1/4 12:14:40
45 % | 2018/1/4 12:14:40
4.97 °C (40.95 °F) DP | 2018/1/4 12:14:40
```

**Comment by r1rider01** [comment]
YOU DID IT!

**Comment by r1rider01** [comment]
now to make the graphs show in F ;-)

**Comment by kizniche** [comment]
Great! Can you paste the output from the daemon log, please?

**Comment by kizniche** [comment]
I'd also like to get it to return a float value instead of an integer, so would you mind testing one more test module?

**Comment by kizniche** [comment]
Also, the tooltips (mouse hover) should show F in addition to all C measurements.

**Comment by r1rider01** [comment]
```
2018-01-04 12:14:01,499 - mycodo.daemon - INFO - Mycodo daemon v5.5.4 starting
2018-01-04 12:14:01,723 - mycodo.daemon - INFO - Anonymous statistics enabled
2018-01-04 12:14:01,746 - mycodo.daemon - INFO - Starting rpyc server
2018-01-04 12:14:01,971 - mycodo.output - INFO - Output controller activated in 57.7 ms
2018-01-04 12:14:02,472 - mycodo.daemon - INFO - All activated Timer controllers started
2018-01-04 12:14:02,604 - mycodo.input_2 - INFO - Activated in 94.5 ms
2018-01-04 12:14:02,804 - mycodo.input_4 - INFO - Activated in 105.2 ms
2018-01-04 12:14:02,805 - mycodo.daemon - INFO - All activated Input controllers started
2018-01-04 12:14:02,806 - mycodo.daemon - INFO - All activated Math controllers started
2018-01-04 12:14:02,807 - mycodo.daemon - INFO - All activated PID controllers started
2018-01-04 12:14:02,807 - mycodo.daemon - INFO - All activated LCD controllers started
2018-01-04 12:14:03,362 - mycodo.conditional - INFO - Conditional settings refreshed
2018-01-04 12:14:03,363 - mycodo.conditional - INFO - Conditional controller activated in 54.9 ms
2018-01-04 12:14:03,364 - mycodo.daemon - INFO - Mycodo daemon v5.5.4 started in 1.864 seconds
2018-01-04 12:14:03,366 - mycodo.daemon - INFO - 35.78 MB RAM in use
2018-01-04 12:14:23,087 - mycodo.input_4 - INFO - Deactivated in 85.7 ms
2018-01-04 12:14:25,428 - mycodo.input_4 - INFO - Activated in 96.4 ms
```

**Comment by r1rider01** [comment]
of course ill help  just let me know.

**Comment by kizniche** [comment]
There should have been more log lines after the sensor activated. No big deal, though. Try this module: [dht11.txt](https://github.com/kizniche/Mycodo/files/1604317/dht11.txt)

**Comment by kizniche** [comment]
Pay attention to the timestamp to make sure it's actually updating after you replace the module with the new code and restart the mycodo daemon.

**Comment by r1rider01** [comment]
that was the full log since restart.

**Comment by kizniche** [comment]
Ah, that makes sense. If there were no log lines displayed, that meant there were no errors.

**Comment by r1rider01** [comment]
New file, got 1 reading then:

```
2018-01-04 12:27:26,143 - mycodo.daemon - INFO - Mycodo daemon v5.5.4 starting
2018-01-04 12:27:26,382 - mycodo.daemon - INFO - Anonymous statistics enabled
2018-01-04 12:27:26,406 - mycodo.daemon - INFO - Starting rpyc server
2018-01-04 12:27:26,634 - mycodo.output - INFO - Output controller activated in 58.1 ms
2018-01-04 12:27:27,135 - mycodo.daemon - INFO - All activated Timer controllers started
2018-01-04 12:27:27,316 - mycodo.input_2 - INFO - Activated in 130.6 ms
2018-01-04 12:27:27,469 - mycodo.input_4 - INFO - Activated in 92.1 ms
2018-01-04 12:27:27,469 - mycodo.daemon - INFO - All activated Input controllers started
2018-01-04 12:27:27,470 - mycodo.daemon - INFO - All activated Math controllers started
2018-01-04 12:27:27,470 - mycodo.daemon - INFO - All activated PID controllers started
2018-01-04 12:27:27,471 - mycodo.daemon - INFO - All activated LCD controllers started
2018-01-04 12:27:28,073 - mycodo.conditional - INFO - Conditional settings refreshed
2018-01-04 12:27:28,074 - mycodo.conditional - INFO - Conditional controller activated in 101.6 ms
2018-01-04 12:27:28,074 - mycodo.daemon - INFO - Mycodo daemon v5.5.4 started in 1.931 seconds
2018-01-04 12:27:28,077 - mycodo.daemon - INFO - 36.80 MB RAM in use
2018-01-04 12:28:02,031 - mycodo.input_4 - ERROR - StopIteration raised. Possibly could not read input. Ensure it's connected properly and detected.
2018-01-04 12:28:47,211 - mycodo.input_4 - ERROR - StopIteration raised. Possibly could not read input. Ensure it's connected properly and detected.
```

**Comment by kizniche** [comment]
Try this one, please: [dht11.txt](https://github.com/kizniche/Mycodo/files/1604346/dht11.txt)

**Comment by r1rider01** [comment]
same error as above, this time it didn't even give me an initial reading thou.

**Comment by kizniche** [comment]
And just to be sure, you're restarting the daemon, then deactivating, and reactivating the sensor, correct?

**Comment by kizniche** [comment]
Okay. I'm going back to the original coe that worked, because the DHT11 accuracy is +-5% and +-2C, so we don't need float values. Please try this: [dht11.txt](https://github.com/kizniche/Mycodo/files/1604364/dht11.txt)

**Comment by r1rider01** [comment]
back to working just fine :-)

**Comment by r1rider01** [comment]
can you add this to the request list:

Make F (Celceuis) default as a setting for us dumb Americans  LOL

**Comment by r1rider01** [comment]
Are you into Crypto Currency?  send me your ETH or LTC address,

**Comment by kizniche** [comment]
What do you mean by make it default? As in change the x-axis of the graphs? Unfortunately, that would be very difficult with how the graph code is designed, as all units are hard coded to be SI. If you hover over the graph, it will show you the converted F temperature. This is the compromise I came up with a long time ago that users who requested F were okay with. It also helps to get comfortable with the metric system ;)

Sure, and thanks! I have both:
LTC: LefW35ALg8ZdWQguoDS114QrY3AKC5GPCW
ETH: 0x16097be33831088346e9224eE38Fc23fA3b1d335

**Comment by r1rider01** [comment]
very good.

**Comment by kizniche** [comment]
I just pushed the fix that will be incorporated in the next release. I'll make that release soon. You'll be able to upgrade from the Config -> Upgrade menu once it's live.

**Comment by kizniche** [comment]
Okay, v5.5.5 is live. Thanks for the bug report. There are a lot of sensors Mycodo supports that may not work after moving from python 2 to python 3 (Mycodo v5.5.0+), so I appreciate people who come forward and are willing to help test fixes for them.

**Comment by r1rider01** [comment]
not sure if this is related...but just noticed that my GPIOD wasn't running after the upgrade?

**Comment by kizniche** [comment]
Hmm. It's definitely an issue that it's not starting at boot.

Try starting it with ```sudo /usr/local/bin/pigpiod -s 1 &``` and let me know if it starts running by checking ```ps aux | grep pigpiod```

If it's already running, kill it first with ```sudo killall pigpiod``` and confirm it has stopped before trying to start it.

**Comment by kizniche** [comment]
actually, that may cause an error. Try rebooting, then starting pigpiod

**Comment by kizniche** [comment]
can you verify pigpiod is in /usr/local/bin by executing whereis pigpiod

**Comment by r1rider01** [comment]
pigpiod: /usr/bin/pigpiod /usr/local/bin/pigpiod /usr/man/man1/pigpiod.1

**Comment by r1rider01** [comment]
ok well after reboot it started up, not sure what caused it to fail earlier.   will keep an eye out.

FYI sent some ETH

**Comment by kizniche** [comment]
Okay, I was going to suggest rebooting and seeing if the cron entry starts it. That's good news.

Thanks! I haven't seen the transaction it show up yet, but they can take a while. I'll look out for it.

Let me know if you have any other issues.
