### ISSUE TITLE
README.md typo fixes

### ISSUE THREAD

**Issue by pukkita** [kizniche/Mycodo#372]
Sorry if I could have submited the fixes straight to gitlab, I'm not too familiar with it. Could I?

Found a couple typos on README.md:

Mycodo is an automated monitoring and regulation system that was built to run on the []Raspberry Pi](https://en.wikipedia.org/wiki/Raspberry_Pi) (versions Zero, 1, 2, and 3). 

(extra ] prior to "Raspberry")

**Orignially** designed to cultivate edible mushrooms, Mycodo has grown to include the ability to do much more,

**Comment by kizniche** [comment]
Oh wow those are some atrocious mistakes. Thanks for pointing them out. You could have forked the repository, made the edits, committed them to your forked repository, then made a pull request, but that's a lot for just a few changes. It's probably easier to make an issue like you did, unless you wanted to proactive with pull requests.
