### ISSUE TITLE
Suggestion: Wonderful Cable Terminal Blocks (WAGO)

### ISSUE THREAD

**Issue by pukkita** [kizniche/Mycodo#374]
Just wanted to share a nice find for safe and tidy junction/project boxes and Relay wiring installs: WAGO 222 series connectors.

![WAGO Terminal Block](http://toolguyd.com/blog/wp-content/uploads/2014/03/Wago-Lever-Nuts-222.jpg)

They're single polarity terminal blocks, i.e. for a typical electricity wiring (neutral, phase, earth) three terminal blocks would be needed, with proper number of wire "bays" (all are internally connected).

E.g. If we wanted to join two devices to electricity, we will need the three cable "bay" ones.

They're tool-less, to insert a cable, its bay clamping lever is raised to 90 degrees, cable inserted, then lever is put down to original position.

They're available via Amazon for cheap, a 50 terminal box (3 cable bays) goes for about 14€ in Europe (0.28€/ea).

There are accesories for DIN rail mounting them, cable strain reliefs, you name it.

Product Video: https://www.youtube.com/watch?v=-PfN_wwkujQ

[Specs (Three bay model):](https://eshop.wago.com/JPBC/0_5StartPage.jsp;jsessionid=2C5CA86F80DBBA5F1ECD5C7D66CAB60D?zone=6)

- Suitable for solid, stranded and fine-stranded conductors.
- Suitable for  0.08 mm² – 2.5 mm² “s”/4 mm² “f-st” wire sizes (AWG 28-12)
- 32A
- IP66
- Sport a probe point (recessed, no chance to accidentally touching it while live)
- Really Tough, meeting an exceeding international safety specs (https://www.youtube.com/watch?v=pCd4F6KTw2c)
- Suitable for vibrating environments (boats, motors, trains)

![Complete Specs](https://user-images.githubusercontent.com/32773513/34611372-81706750-f225-11e7-809b-cfaa792b5e79.png)

Disclaimer: I have no relationship with WAGO nor WAGO stock, I just fell in love with after finding them. ;)

**Comment by r1rider01** [comment]
those looks nice!

**Comment by pukkita** [comment]
They are :) and moreso, really safe and versatile!

**Comment by zsole2** [comment]
Yes, they are nice, I have a few, I use them for quick a dirty prototyping with wires of almost any diameter. The only problem that they are a little bit bulky. The Wago 221 series seems the same, but smaller. Next time I go for those. 
On the other hand, if you work with solid core wires and household currents, and no need for remove the wires, try Wago 2273 series, I like those very much, though the wire cannot be removed (but never slips out, too).
