### ISSUE TITLE
Gauge refresh rate resets to 'None'

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#376]
Specific Mycodo Version: 
 **5.5.6**

Add new gauge, set basic parameters. After the gauge comes back, edit, and set color ranges. At this times, the refresh rate is shown as expected. After save, the gauge shows 0, and checking the details, the refresh rate shows 'None'.

**Comment by kizniche** [comment]
I can't reproduce this issue. Can you post a screenshot of your gauge settings?

**Comment by kizniche** [comment]
I was just able to reproduce this issue. Looking into fixing it.

**Comment by kizniche** [comment]
Thanks for the bug report. I made a fix and will make a release soon. In the meantime, you can save the value as long as you use an integer (not a float). So, just remove the period (".") and the "0" to allow it to save (e.g. "40" instead of "40.0").
