### ISSUE TITLE
EDGE conditional cannot be set

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#381]
## Mycodo Issue Report:
  - Specific Mycodo Version:
5.5.8
 
#### Problem Description
I set up the conditional as this screenshot shows:

![image](https://user-images.githubusercontent.com/11209960/34905292-ea961ef6-f855-11e7-912e-c36a3f99224e.png)

Hitting Save gives 

> Error: Mod Conditional: If the GPIO State radio button is selected, GPIO State must be set

This error did not depend on whether the edge detection was selected and configured beforehand, or not. Neither f the Rising state was deleted, contrary to what is shown on the screenshot. 

### Additional Notes
I was able to set it on a single try, when changed the period value, and the the help bubble covered the Save button. Then the first click made the bubble disappear, and the second click reached the Save button. But this phenomenon could not be repeated, though.

UPDATE: 
After adding another one of these conditionals, it could be set. The difference was that the GPIO level was intended to set for  HIGH. Also conformed with the first conditional, setting it HIGH was OK, setting it LOW gives the error.

**Comment by kizniche** [comment]
Thanks, I'll look into it.

**Comment by kizniche** [comment]
I just released v5.5.9 that incorporates a fix for this issue.

**Comment by zsole2** [comment]
Thanks for the fix, I am now able to save the LOW setting. On the other hand, activating still gives trouble:
`Error: Activate Conditional: If the GPIO State radio button is selected, a GPIO State must be set`

**Comment by kizniche** [comment]
Sorry about that. I just pushed a fix. I'm going to work on a few more issues before making a release later today.
