### ISSUE TITLE
Error adding new gauge

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#391]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.5.10
 
#### Problem Description
No new gauge can be added. I tried to add one after setting up every parameters, than one with the basic setting. Got the same error:

`Error: Unknown Dashboard Object type: None`
 
### Additional Notes
Adding graph has no problem.
I wonder if this is still related to #384.

**Comment by kizniche** [comment]
I fixed #384. This issue was probably introduced with 2c6289a. I'll release a fix later today.

**Comment by zsole2** [comment]
Thanks, it fixed this issue.
