### ISSUE TITLE
Suggestion: Add 'Difference' to options in 'Math" menu. 

### ISSUE THREAD

**Issue by Ryobidelacroix** [kizniche/Mycodo#395]
Suggestion: Add 'Difference' to options in 'Math' menu. 

For example, a user may want to know the difference between two different temperature readings, humidity readings etc.

eg: (T₁ - T₂ = 𝚫T) 
28 - 21 = 7
The output could show: '𝚫T = 7⁰C' etc.

**Comment by kizniche** [comment]
Great suggestion. I'll add it in the next release. Thanks!

**Comment by kizniche** [comment]
> commit 76905f2 

> Showing 22 changed files with 182 additions and 187 deletions.

\> When you make a commit that adds a new feature along with optimizations and the overall code size decreases 😂
