### ISSUE TITLE
Add PID Control Hysteresis

### ISSUE THREAD

**Issue by kizniche** [kizniche/Mycodo#398]
From [this comment](https://kylegabriel.com/projects/2015/04/mushroom-cultivation-revisited.html#comment-577)

Proposed is the addition of the PID option ```band``` to enable PID hysteresis.

Example: [Temperature Controllers Using Hysteresis](https://na.industrial.panasonic.com/blog/temperature-controllers-using-hysteresis)

To my understanding it should operate like this:

### If PID is set to Raise

Raise to the maximum value (setpoint + band value), then allow the condition to fall to the minimum value (setpoint - band value) before resuming regulation.

### If PID is set to Lower

Lower to the minimum value (setpoint - band value), then allow the condition to raise to the maximum value (setpoint + band value) before resuming regulation.

### If PID is set to Both

When the condition enters the band region (setpoint +/- band), do not apply the PID. When the condition falls outside (above or below), then begin applying the PID again. If it rises above the maximum value, begin lowering until it enters the band region. When it lowers below the minimum value, begin raising until it enters the band region.

Let me know your thoughts, if I'm missing a part of this concept, or if there are alternative methods that would be desirable to add.

**Comment by kizniche** [comment]
Currently untested, but I implemented the ```band``` option and the logic to determine the appropriate setpoint if raising/lowering:

https://github.com/kizniche/Mycodo/blob/e9038c9693ee30d52ffc14be04ef42853f6960cf/mycodo/controller_pid.py#L364-L389

I should get around to testing this weekend or sooner and have a release by the end of the weekend.

**Comment by zsole2** [comment]
I like this a lot, will be very useful for the health of my refrigerators!

**Comment by zsole2** [comment]
Kyle, looking at the link above on hysteresis control got me thinking that PID control and this hysteresis control are alternatives, and should not be combined  together. A little googling seems to support this. 
Do you agree? 
In that case, this needs to be added as a separate function.
At brewing forums, there are plenty of discussions that they use PID for heating and hysteresis for cooling.

**Comment by kizniche** [comment]
I added the ```band``` to the PID options with the option of using it. If set to 0, there is no band and no hysteresis. However if you set it to a non-0 value, then it will operate like I describe in the first post, still using PID control. I don't think there needs to be a separation, but being able to turn it off is essential.

**Comment by kizniche** [comment]
I can't conceptualize how the same PID can use hysteresis for just lowering and not use it for raising.

I can see two PIDs being used, one raising, and one lowering with hysteresis. This could work well, without the PIDs competing too much if tuned properly.

**Comment by zsole2** [comment]
I believe that those were two different operations, but I'm not familiar with brewing. The competition was a main topic of the discussion, though.

**Comment by zsole2** [comment]
I believe that those were two different operations, but I'm not familiar with brewing. The competition was a main topic of the discussion, though.

**Comment by kizniche** [comment]
The current iteration of Hysteresis in Mycodo's PID controllers can theoretically work very well together. Here's one heating/cooling scenario:

### PID 1: Heat, Raise to 30

Setpoint: 30, Hysteresis: 0 (disabled), the PID will raise the temperature to 30 and stop when the temperature is 30 or above.

### PID 2: Cool, Lower to 31

Setpoint: 33, Hysteresis: 2 (Min Band: 31, Max Band: 35), the PID will lower to 31, then stop until the temperature rises above 35, at which point it will begin regulating again to 31.

Leaving the gap of one degree (30 to 31, there shouldn't be any direct competition between the PID controllers. You would even make the gap 0 degrees (Rise to 30, Lower to 30) and the PIDs should still function properly (considering they're well-tuned).

**Comment by kizniche** [comment]
I just tested on a PID set to Raise (so should also work for Lower). Looks good. Next to test Both directions.

![screenshot-192 168 0 10-2018-02-03-13-34-40](https://user-images.githubusercontent.com/838427/35770345-2d818a1a-08e7-11e8-8d92-c93c1db4f6f5.png)

**Comment by kizniche** [comment]
With testing the PID with direction set to Both, I had to fix some issues related to the wrong outputs being activated, due to the integrator and/or derivator.  To do this, I reset both the integrator and derivator upon the current measurement reaching the opposite band threshold. That is, when the measurement reaches beyond either the Minimum Band or Maximum Band, the integrator and derivator are reset to 0, so the PID acts as though it were just turned on. This creates a smooth output instead of the aberrant behavior in the following graphs;

### Before Fix

![screenshot-192 168 0 10-2018-02-03-15-17-59](https://user-images.githubusercontent.com/838427/35771964-73306b00-0903-11e8-8368-bf46777d928c.png)

### After Fix

![screenshot-192 168 0 10-2018-02-03-16-57-28](https://user-images.githubusercontent.com/838427/35771965-766cbe5e-0903-11e8-823e-714c66c820d8.png)

**Comment by kizniche** [comment]
Another test that has less steep slopes so the PID deactivation is a little bit more noticeable when the measurements enter between the bands.

![screenshot-192 168 0 10-2018-02-03-17-52-14](https://user-images.githubusercontent.com/838427/35772383-4d817d92-090b-11e8-9bc7-ad40bcb978d7.png)

**Comment by zsole2** [comment]
I have a few test examples now.
First, the nice one:
![image](https://user-images.githubusercontent.com/11209960/35793225-0c22b572-0a51-11e8-8206-f71c21e34d36.png)

This is my refrigerator PID, which was on 300s periods. It is clear that the frequency of operation is decreased.
Now the less nice one:
![image](https://user-images.githubusercontent.com/11209960/35793242-1cc5f93e-0a51-11e8-803d-2c1fa7f7b1d8.png)

This is my processor fan, on 60s period. Need some tuning. 
Interestingly, without the band it looked quite OK (not the same system, but the current system looked quite similar):
![image](https://user-images.githubusercontent.com/11209960/35793346-9066c63e-0a51-11e8-84b7-868195c5ade3.png)

About 5-15s run of the fun kept the  the processor at 40C. Now it is much worse. I'll remove the band to check that indeed the fan behaved similarly in the current system.

**Comment by zsole2** [comment]
Here is the CPU fan with the previous PID settings, without the band:
![image](https://user-images.githubusercontent.com/11209960/35795735-5ebc04d8-0a5a-11e8-88b2-7358bc7f3934.png)

**Comment by frodus17** [comment]
Kyle,
When I get time this week, I'll play around with this to test.

**Comment by kizniche** [comment]
Let me know if there are any issues. I'm closing this, as I believe it's complete.

**Comment by frodus17** [comment]
Sounds good, looks OK on my end for all of the delays and hysteresis.
