### ISSUE TITLE
Async graph data are incorrect

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#399]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.5.16
 
#### Problem Description
During the investigation of my pump not pumping as directed (#387), I checked the GPIO state sensor history. Strangely, the time points were 14 minutes apart, whereas the settings are for 600s.
Looking at the Live graph, the data points are 10 mins apart.
 
### Additional Notes
I put here my wish list for the async graphs:
- ability to add more than 1 line
- I miss the relays from the selection list
- after clicking Submit, the selection box reverts to show the first item, rather the one that was selected and shown on the graph

**Comment by kizniche** [comment]
Where did you view them 14 minutes apart?

**Comment by zsole2** [comment]
Oh, I forgot to include the issue itself: in the async graph, l loaded the GPIO data to see when was the last time the pump operated.

**Comment by kizniche** [comment]
But async graphs don't have the option to display Outputs

**Comment by zsole2** [comment]
Yeah, I realized and added this item to the wish list...
But I have the two GPIO sensor, connected in series, and their interrelated behavior induces the pump to fill up the container for the humidifier. So I wanted to see where the GPIO state changes were for the two sensors.

**Comment by kizniche** [comment]
I still don't understand this:

> Strangely, the time points were 14 minutes apart, whereas the settings are for 600s.
> Looking at the Live graph, the data points are 10 mins apart.

Where did you view them 14 minutes apart and where did you view them 10 minutes apart?

**Comment by zsole2** [comment]
Looking at the GPIO points on a Live graph, they were measured at 10 mins intervals, as expected.
When loaded the same GPIO sensor's data on the Async page, the timepoints that the graphing engine shows were regularly at every 14 minutes.
I'll later try to do a few  screenshots.

**Comment by kizniche** [comment]
Yes, I'll need to see the data to understand the issue.

As for adding multiple selections and Outputs, those would be good features.

**Comment by zsole2** [comment]
Here is my little movie...

First, from live graph:

![selection_020](https://user-images.githubusercontent.com/11209960/35770660-a3ec2344-091f-11e8-8724-be1d57d0af22.jpg)
![selection_021](https://user-images.githubusercontent.com/11209960/35770662-b25458ca-091f-11e8-82e8-acf7617914b8.jpg)
![selection_022](https://user-images.githubusercontent.com/11209960/35770663-b798102e-091f-11e8-8351-11e90f7289b4.jpg)
![selection_023](https://user-images.githubusercontent.com/11209960/35770664-becc1c50-091f-11e8-97d5-2c011a70dbb5.jpg)
![selection_024](https://user-images.githubusercontent.com/11209960/35770666-c39306cc-091f-11e8-8d01-7d2281360250.jpg)
![selection_025](https://user-images.githubusercontent.com/11209960/35770668-c79b7cc2-091f-11e8-9907-24b97f7f369d.jpg)

And from the async graph:

![selection_027](https://user-images.githubusercontent.com/11209960/35770673-ced72586-091f-11e8-8089-804936a3a643.jpg)
![selection_028](https://user-images.githubusercontent.com/11209960/35770675-d3575932-091f-11e8-8d56-60dbf9fd6cba.jpg)
![selection_029](https://user-images.githubusercontent.com/11209960/35770676-d78493d0-091f-11e8-9c62-de918cf4a15e.jpg)
![selection_030](https://user-images.githubusercontent.com/11209960/35770678-dcf8b4fe-091f-11e8-9908-9985c5cf27ae.jpg)
![selection_031](https://user-images.githubusercontent.com/11209960/35770679-e099378c-091f-11e8-87f1-449aff26c5d5.jpg)
![selection_032](https://user-images.githubusercontent.com/11209960/35770681-e49b135a-091f-11e8-9267-e05e96390777.jpg)
![selection_033](https://user-images.githubusercontent.com/11209960/35770682-e85b3b28-091f-11e8-8281-5c16ba417d50.jpg)

**Comment by kizniche** [comment]
🤔

**Comment by kizniche** [comment]
Are you selecting the same Input in the async graphs? The times don't even have the same duration between points, indicating it's not just a time sync issue.

7:03:16 to 7:13:14, 10min:

![selection_023](https://user-images.githubusercontent.com/11209960/35770664-becc1c50-091f-11e8-97d5-2c011a70dbb5.jpg)
![selection_024](https://user-images.githubusercontent.com/11209960/35770666-c39306cc-091f-11e8-8d01-7d2281360250.jpg)

6:44:08 to 7:14:24, 30min:

![selection_030](https://user-images.githubusercontent.com/11209960/35770678-dcf8b4fe-091f-11e8-9908-9985c5cf27ae.jpg)
![selection_032](https://user-images.githubusercontent.com/11209960/35770681-e49b135a-091f-11e8-9267-e05e96390777.jpg)

**Comment by kizniche** [comment]
Wait, why are there more than one data set on the graphs you labeled "async". There isn't the ability to have more than one data set on async graphs.

**Comment by zsole2** [comment]
Exactly this was the reason to start this issue.
I have only two GPIO state inputs, and the other one is steadily at 0.
What is interesting now that the the time between the points on the async graph is increased from the 14min I saw  earlier to 15m08s. Can it be that  influx as a time-series-database somehow averaging the  data? But it should only be seen when the timescale is compressed.

**Comment by kizniche** [comment]
This graph confirms data grouping (averaging) is occurring:

![selection_031](https://user-images.githubusercontent.com/11209960/35770679-e099378c-091f-11e8-87f1-449aff26c5d5.jpg)

**Comment by zsole2** [comment]
Yes, but shouldn't averaging appear only when the timescale is compressed? 
I checked the xls export, and this is what appears in the relevant time-region:

2018-02-03 04:38:53 | undefined | 1
-- | -- | --
2018-02-03 04:53:53 | undefined | 1
2018-02-03 05:08:53 | undefined | 1
2018-02-03 05:23:53 | undefined | 1
2018-02-03 05:27:21 | 1 |  
2018-02-03 05:38:53 | undefined | 1
2018-02-03 05:43:28 | 1 |  
2018-02-03 05:53:53 | undefined | 1
2018-02-03 05:59:35 | 1 |  
2018-02-03 06:15:42 | 0 |  
2018-02-03 06:23:53 | undefined | 0
2018-02-03 06:31:49 | 0 |  
2018-02-03 06:38:53 | undefined | 0
2018-02-03 06:47:56 | 0 |  
2018-02-03 06:53:53 | undefined | 0
2018-02-03 07:04:03 | 1 |  
2018-02-03 07:08:53 | undefined | 1
2018-02-03 07:20:10 | 1 |  
2018-02-03 07:23:53 | undefined | 1
2018-02-03 07:38:53 | undefined | 1
2018-02-03 07:53:53 | undefined | 1
2018-02-03 08:08:53 | undefined | 1

The above was exported when the all data was selected. If I zoomed to the region in question, the data change:

2018-02-03 05:43:28 | 1 |  
-- | -- | --
2018-02-03 05:53:53 | undefined | 1
2018-02-03 05:59:35 | 1 |  
2018-02-03 06:15:42 | 0 |  
2018-02-03 06:23:53 | undefined | 0
2018-02-03 06:31:49 | 0 |  
2018-02-03 06:38:53 | undefined | 0
2018-02-03 06:47:56 | 0 |  
2018-02-03 06:53:53 | undefined | 0
2018-02-03 07:04:03 | 1 |  
2018-02-03 07:08:53 | undefined | 1
2018-02-03 07:20:10 | 1 |  
2018-02-03 07:23:53 | undefined | 1
2018-02-03 07:36:17 | 1 |  
2018-02-03 07:38:53 | undefined | 1
2018-02-03 07:52:24 | 1 |  

Here are the raw data, if you want to have a look:
[async_exports.zip.zip](https://github.com/kizniche/Mycodo/files/1692541/async_exports.zip.zip)

**Comment by kizniche** [comment]
Aha! I found the issue. Check out my change if you want to test it: https://github.com/kizniche/Mycodo/commit/fa06c68c90893e5c61fc1c58e235f7a4a805c6ea#diff-ce1b3a9ed14f31f75c496ac2fad02530

**Comment by zsole2** [comment]
Thanks, that fixed it!

**Comment by kizniche** [comment]
Don't close this just yet, I haven't added all the features yet ;)

I just had a breakthrough with multiple datasets displaying asynchronously:

![screenshot-192 168 0 10-2018-02-04-11-55-40](https://user-images.githubusercontent.com/838427/35779927-9ac6b03a-09a2-11e8-898e-531d01df6b3c.png)

**Comment by kizniche** [comment]
Although, this is more complicated than I anticipated. I may make a new branch for this work, because I may not got it fully working.

**Comment by zsole2** [comment]
OK, I see. The issue is solved and now come the wishes...

**Comment by kizniche** [comment]
I just successfully got the graph to redraw with new data for all series, after zooming. This was the hardest thing I was facing, so now it should be all easy to clean up the code and try to add minor things like appropriate y-axis titles, units, etc.

**Comment by kizniche** [comment]
I had some breakthroughs that I think makes the new async graph ready for release. It's such an improvement for looking through data to have more than one series on the async graph.

I also made selections remain after form submissions. and added Outputs. It's looking really nice now!

![screenshot-192 168 0 10-2018-02-04-18-02-48](https://user-images.githubusercontent.com/838427/35783468-a9b6adec-09d5-11e8-903e-77b6eb8144f7.png)

**Comment by kizniche** [comment]
Something was off... now it looks good

![screenshot-192 168 0 10-2018-02-04-18-15-07](https://user-images.githubusercontent.com/838427/35783563-6563bb56-09d7-11e8-9496-66af5646b3a3.png)

**Comment by kizniche** [comment]
To finish it off, I added PIDs. 

![screenshot-192 168 0 10-2018-02-04-18-45-17](https://user-images.githubusercontent.com/838427/35783812-b5eda830-09db-11e8-8d1f-1dbad352ba00.png)

**Comment by kizniche** [comment]
I have a Pi that's been running the latest versions but without any sensors connected. I loaded all the data from the internal sensors and see some interesting stuff.

Red is RAM use of the daemon, so you can see when it was running and restarting. What's interesting is the average basal CPU levels differ between restarts of Mycodo (for upgade to new version). It looks like since the last restart, it's been running with the higher load.

![screenshot-192 168 0 14-2018-02-04-19-13-27](https://user-images.githubusercontent.com/838427/35784005-bca813f0-09df-11e8-9c10-09689c5bbdf7.png)

**Comment by kizniche** [comment]
One last image before I close this issue (v5.5.18 was released). This change will be included in 5.5.19, and includes different durations of data to select as the default view, which makes using the navbar a lot nicer when you really want to move around a smaller set of data.

![screenshot-2017-9-16 tango - graph - mycodo 5 2 0](https://user-images.githubusercontent.com/838427/35785452-7963cf3a-09ee-11e8-99c6-eb2c83632667.png)

**Comment by zsole2** [comment]
Wow, this looks nice, all the work! Everything is there...
Just a further idea, that comes fro your last change: instead of pre-selecting the past /day/week/month/year, it would be much useful if a time-period from the past could be examined in higher detail. This obviously cannot be done be these buttons, but can it be done by re-zooming the window to the currently selected area? E.g. in this last picture, by a click of a button, you get the more detailed data of the current selection stretched to the full area, showing data from 12:05 to 03:05.
This could be very useful to pinpoint past behavior. Coming to mind, since youhave already  put a few buttons in this screen, an 'Undo' type button also could be useful, i.e. reverting to the the previous selection of start and end dates.

**Comment by zsole2** [comment]
Do we want to discuss CPU load here? 
Anyway, here is a screenhot of 15min CPU load from my long-running 5.0.17 system:
![image](https://user-images.githubusercontent.com/11209960/35796219-1d3474a8-0a5c-11e8-9980-ab334a923946.png)
The load-change clearly there, but it was not upgraded since last April. On the other hand, reboots seem to always result in this two-level load change. I did not realized that this system got rebooted so many times recently, in theory it is in use most of the time:
```
2017-04-01 12:50:26,802 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-04-01 13:09:49,573 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-05-02 19:47:34,036 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-05-11 16:09:27,963 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-05-11 17:28:24,023 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-06-10 08:44:15,437 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-06-10 20:11:09,375 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-06-19 14:54:48,919 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-06-22 19:52:24,089 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-07-30 17:17:59,256 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-07-30 19:05:58,071 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-07-30 19:13:12,326 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-08-20 10:05:38,868 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-08-20 10:18:53,007 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-10-20 06:46:17,312 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-11-04 12:18:10,702 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-12-17 10:13:32,728 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-12-17 16:48:05,398 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-12-17 19:37:19,104 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-12-17 20:28:50,525 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-12-18 09:07:28,531 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-12-23 12:28:25,432 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2017-12-28 15:25:47,613 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2018-01-10 10:44:23,177 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2018-01-13 20:50:43,442 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2018-01-16 20:41:41,337 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2018-01-18 19:35:00,069 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2018-01-20 20:00:58,842 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2018-01-22 19:31:35,625 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2018-01-26 15:17:57,789 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2018-01-31 06:45:55,355 - mycodo - INFO - Mycodo daemon v5.0.17 starting
2018-02-04 17:32:14,562 - mycodo - INFO - Mycodo daemon v5.0.17 starting
```

In addition, there is some very minimal upward trending over the months.
![image](https://user-images.githubusercontent.com/11209960/35796367-9ca7813a-0a5c-11e8-936b-5fea3a907d38.png)
