### ISSUE TITLE
Math humidity does not show  dry bulb input after saving

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#400]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.5.17
 
#### Problem Description
I set the two inputs, then save. Dry bulb comes back 'Select one'.
On the other hand, it appears to be working  after activating it.

**Comment by kizniche** [comment]
It saves properly for me. Not sure what's going on with yours.

**Comment by kizniche** [comment]
Okay, it won't allow me to save Math measurements. Inputs work just fine.

**Comment by kizniche** [comment]
Thanks for the bug report! #400 came and went in a flash.
