### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by The-tin-man** [kizniche/Mycodo#406]
Specific Mycodo Version:  5.5.20

During the install pigpio_low.service Fails to start leading to a failed install of the System.
Installed on a  freshly flashed Raspbian, after updates. The instructions were followed closely. 

journalctl -xe data, setup.log and system Version are attached in the .txt. file.

[mycodo.txt](https://github.com/kizniche/Mycodo/files/1720010/mycodo.txt)

**Comment by kizniche** [comment]
I just released v5.5.21 that incorporates the fix to this issue. Thanks for the bug report.
