### ISSUE TITLE
Mux initialization

### ISSUE THREAD

**Issue by The-tin-man** [kizniche/Mycodo#407]
Suggestion.

Change Mux initialization to the method discussed in this thread:

https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=141517

Way easier.

Take it ez.

The tin man

**Comment by The-tin-man** [comment]
Cool. Ive tried it out, and with ther current version works without any Problems, all 8 buses were instantly visible.

**Comment by kizniche** [comment]
I detail how to set up the overlay in the manual: https://github.com/kizniche/Mycodo/blob/master/mycodo-manual.md#i2c-multiplexers
