### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#408]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.5.21
 
#### Problem Description
I have Mycodo RAM on a gauge, but was suspicious about it increasing.
Here is the async graph:

![image](https://user-images.githubusercontent.com/11209960/36386894-a1ba1c0a-1597-11e8-8153-4dac1bac3832.png)

What should I look at for testing?

**Comment by zsole2** [comment]
And this is my test system, where only CPU temp, CPU load, RAM usage and Free memory are activated since setup, and nothing else:
![image](https://user-images.githubusercontent.com/11209960/36390749-603defb0-15a4-11e8-88ce-910d761cfae7.png)

**Comment by kizniche** [comment]
Can you deactivate all controllers and let run to see if it increases? Then activate one controller at a time to determine if a particular controller is the offender?

**Comment by zsole2** [comment]
I deactivated all inputs except the RAM:
![image](https://user-images.githubusercontent.com/11209960/36442441-1543df38-1676-11e8-9c4a-24330ec95b6e.png)

The big jump is at 16:25, which is the time when the daemon was originally started. 
I have no idea about the slow increase at about 03:25 in the night, I certainly did not do anything then.

**Comment by kizniche** [comment]
Did you run the daemon with no controllers started?

**Comment by zsole2** [comment]
How can I start the daemon without controllers?
I had  only 4 Inputs (CPU temp, CPU load, RAM usage and Free memory) activated in the first place, and nothing else, no timer, no output, nothing.

**Comment by kizniche** [comment]
Just deactivate all the controllers, let the daemon run a few days, then activate the RAM Input to see how much ram is in use.

**Comment by kizniche** [comment]
I would suggest restarting after deactivating everything to start from a clean slate.

**Comment by zsole2** [comment]
Here is my memory graph, after reboot, and then turned the RAM Input on after a few days, with the last stored data-point highlighted:
![image](https://user-images.githubusercontent.com/11209960/36643589-dfc304f2-1a4d-11e8-843f-aa1a6fa12a2e.png)
In that period, I did not check the GUI or SSHd in.

**Comment by zsole2** [comment]
Here is a quick update, before I turn off this PiZero:
![image](https://user-images.githubusercontent.com/11209960/36670013-1821e030-1af7-11e8-9453-29527634df4e.png)

Apparently the memory use is steadily increasing, and activating the RAM Input did not affect it neither positively nor negatively.

Side question: we were discussing elsewhere missing data points and null values to break the lines on the graphs. It looks that the async graph has this feature.

**Comment by kizniche** [comment]
It appears the memory leak has been fixed (see attached image)?? If you have any more info about this, feel free to reopen this issue.

![screenshot_2018-10-13_10-53-51](https://user-images.githubusercontent.com/838427/46906741-8ab15200-ced6-11e8-9797-952bda6ec1d4.png)
