### ISSUE TITLE
Conditional activation of PID

### ISSUE THREAD

**Issue by drgrumpy** [kizniche/Mycodo#415]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.6.0
 
#### Problem Description
 - Unable to use a conditional to activate a PID
 - It may be that I misunderstand how this is supposed to work...

#### Steps
 - Function -> conditional measurement or output Add
 - Activate PID add action
 - Expected then to be able to select an existing PID but there is nowhere to do this, like there is a dropdown box missing.
- Clicking on Save button by the 'Activate PID' results in: 
Error: Mod Conditional: PID must be set

Nothing shows up in the logs...

**Comment by kizniche** [comment]
Can you take a screenshot (with the settings expanded- click the plus icons to expand) so I can see how you have it configured?

**Comment by drgrumpy** [comment]
Screenshot attached

![screenshot_2018-02-27_21-26-24](https://user-images.githubusercontent.com/4687649/36755739-0897a6a4-1c05-11e8-93ff-01e30c4c3c1a.png)

**Comment by kizniche** [comment]
That appears to be a bug. Let me look into it.

**Comment by kizniche** [comment]
I just pushed a fix and made a new release that you can upgrade to.
