### ISSUE TITLE
Infinite Page refresh

### ISSUE THREAD

**Issue by RynFlutsch** [kizniche/Mycodo#417]
## Mycodo Issue Report:
  - Specific Mycodo Version:
 5.6.1
#### Problem Description
 Clean instal today without errors.
No errors @ mycodo and nginx.log 

Got my browser warning (unsave cert.) Proceeding to the admin creating result in infinite page refresh ( information at the browser adressline appears for some ms between the refresh: Looking for Page)

Older mycodo versions (5.5.22) are updated to 5.6.1 without any problems.

Any idea how to fix this?

**Comment by kizniche** [comment]
It doesn't sound like a Mycodo issue. Try a different browser. You might have cookies, session, or cert saved from a previous install that's causing the issue.

**Comment by RynFlutsch** [comment]
Yes, Safari and Firefox fail to load the Page. Opera mini is working... (iOS) But no idea why.
