### ISSUE TITLE
forgot user/pass

### ISSUE THREAD

**Issue by r1rider01** [kizniche/Mycodo#421]
Whats the quick way to reset or find the username/password for mycodo?

**Comment by kizniche** [comment]
There isn't an easy way, but you can follow these instructions: https://github.com/kizniche/Mycodo/issues/340#issuecomment-367819796

**Comment by kizniche** [comment]
Since I'm sure this will come up again, I made a wiki page for this: https://github.com/kizniche/Mycodo/wiki/How-to-Reset-Your-Admin-User-Password
