### ISSUE TITLE
install mycodo error???

### ISSUE THREAD

**Issue by bike2538** [kizniche/Mycodo#442]
what happen ?! How to install mycodo version lower to 5.6.10? I'm want to install mycodo version 5.5.24. how can i do?
![image](https://user-images.githubusercontent.com/38012416/38234397-fc1c8170-3747-11e8-855e-a4e9a40622c7.png)

**Comment by drgrumpy** [comment]
You haven't told us what you did, or your os
Are you using the Raspbian ?
Did you go to 'Releases', download the relevant zip or gz file, then extract the files and run the install script?

**Comment by bike2538** [comment]
Sorry Guys for not giving enough details.  The screen showed no sign of the process running.  So I thought it crashed.  I just found that I was not patient enough to wait until the installation finish as the internet at home was so so slow.  Now the installation was successful.  I would suggest that it could be great if there is some kind of progress bar during the installation process. 
Thank you very much.
