### ISSUE TITLE
Configure pigpiod - Reconfigure: Cannot modify pigpiod option if pigpiod is not installed

### ISSUE THREAD

**Issue by mrplow** [kizniche/Mycodo#458]
## Mycodo Issue Report:
  - Specific Mycodo Version: 6.0.6
 
#### Problem Description
Please list: 

  - what were you trying to do:
Reconfigure pigpiod to 5ms (slower)
  - specific setup details that are involved
Using a Raspberry Pi Zero W.
Fresh install of Raspbian Stetch Lite 2018-04-18, fresh install of Mycodo
 
### Errors
Main UI Shows:
Error: Pi Settings: None: Cannot modify pigpiod option if pigpiod is not installed
Daemon log doesn't show anything wrong

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. Load webui
 2. Configure
 3. Raspberry Pi
 4. Configure pigpiod: 5ms (slower)
 5. Reconfigure
 
### Additional Notes
After this error Mycodo no longer starts pigpoid on it's own. The sensors were working properly before I reconfigured but not afterwards.
I restored from a dd backup of the USB I made beforehand but I can recreate the issue easily.

**Comment by kizniche** [comment]
Thanks for the bug report. The fix will appear in the next version release.
