### ISSUE TITLE
picamera capture problem

### ISSUE THREAD

**Issue by vankomicin** [kizniche/Mycodo#466]
## Mycodo Issue Report:
version 6.1, fresh install
pi zero, picamera (old model 5M)
user pi in mycodo

#### Problem Description
When trying to capture a still image I mostly get the 504 Gateway Time-out error. When not, I get a small jpeg icon instead of full still. When I ssh in, I find stills jpegs in proper folder inside Cameras folder (permission set to 774), but the size of jpegs is 0 kB.
The issue appeared also in 5.7.3 as far as I remember.
 
Any suggestions?

**Comment by kizniche** [comment]
Can you confirm the camera is working properly with your Pi (can capture outside of Mycodo)?

>I get a small jpeg icon instead of full still

Can you elaborate on what you mean by this?

**Comment by vankomicin** [comment]
Hi,

I apologise for skipping basic troubleshooting and wasting your time. It was a faulty connection... Now everything's cool again.
Thanks.

**Comment by kizniche** [comment]
No problem. Glad to hear it's working.
