### ISSUE TITLE
Command (PWM) outputs support

### ISSUE THREAD

**Issue by lovelytwo** [kizniche/Mycodo#469]
Version: 6.1.0
 
Problem Description
  - PID controller doesn't seem to support command_pwm outputs. 
https://github.com/kizniche/Mycodo/blob/2a2baf917e4fb4845a804df8be188ea55a00dc6a/mycodo/controller_pid.py#L576

Suspect there is also an issues with the frontend, continues referring to "duration" instead of duty cycle.

  - Conditional measurement with "Output (Duty Cycle)" doesn't list command_pwm outputs.

Thanks.

**Comment by lovelytwo** [comment]
Hope you had a good holiday, and that your move isn't too painful.

The UI doesn't detect it's a "pwm" output probably due to the following:
https://github.com/kizniche/Mycodo/blob/968050eafa73be17bb2c0a8b939bbfec7c4760a5/mycodo/mycodo_flask/utils/utils_pid.py#L75

**Comment by kizniche** [comment]
You can see all the edits I made in the referenced commits, above. They will be included in the next release.

**Comment by kizniche** [comment]
I'll check out utils_pid.py

**Comment by lovelytwo** [comment]
And maybe mycodo_flask/templates/pages/function_options/pid.html is worth a look.

**Comment by lovelytwo** [comment]
I've made some screenshots, that illustrate the issues I'm seeing, as i'm not good at explaning in text.

1. Shouldn't this be min and max duty cycle?
<img width="1141" alt="pidsetupcommandpwm" src="https://user-images.githubusercontent.com/7444309/40275384-46af234c-5c31-11e8-9303-d0775a3c5afd.png">

2. duty cycle not duration.
<img width="1131" alt="pidlive" src="https://user-images.githubusercontent.com/7444309/40275386-4ca63c22-5c31-11e8-991d-321b5a521b68.png">

3. I think this widget is unhappy, with the output being null, because it's looking for duration not duty cycle.
<img width="541" alt="piddashboard" src="https://user-images.githubusercontent.com/7444309/40275393-67852d82-5c31-11e8-8373-9412bc2d0106.png">

**Comment by kizniche** [comment]
It may be from the issues displaying the proper PID options that are causing the PID widget to fail to show a value (e.g. if the min and max duty cycle were set to 0). I just fixed several references to command pwm outputs.
