### ISSUE TITLE
Can't Create Daily Point

### ISSUE THREAD

**Issue by berserktron3k** [kizniche/Mycodo#470]
## Mycodo Issue Report:
  - Specific Mycodo Version: 6.1.0
 
#### Problem Description
Please list:

  - what were you trying to do:
Trying to create a new Conditional: Timer (Daily Point). When you set the time (by using the clock that pops up, or by manually typing) an error is given when you try to save.
  - specific setup details that are involved
Hardwired Outputs
 
### Errors
  - List any errors you encountered.
Error: Mod Conditional: Start Time (HH:MM) must be a valid HH:MM time format
  - Copy and pasting crash logs, or link to any specific
code lines you've isolated (please use GitHub permalinks for this)
No crash logs.

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. Create a new function: Conditional: Timer (Daily Point)
 2. Specify the time for the daily point
 3. Click Save
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by RPi-Growbox** [comment]
I have same issue and it comes also with daily span.
