### ISSUE TITLE
6.1.0: Send Test Mail broken?

### ISSUE THREAD

**Issue by fry42** [kizniche/Mycodo#471]
So my installation has been acting up lately, so I tried to set up some alerts.

After configuring all the smtp parameters I tried to send a test mail:
Entered my eMail Address, clicked "Send Test eMail" and got the following error:
Error: Modify Alert Settings: name 'message' is not defined

Either my installation has some serious issues, or mycodo is quite buggy right now...

**Comment by kizniche** [comment]
I haven't been able to replicate this. I just tested sending a test email with gmail, and it worked.

**Comment by CriticalFlaw** [comment]
I have the same issue, so perhaps myself and @fry42 jsut have something configured incorrectly?

![ss 2018-05-18 at 10 15 54](https://user-images.githubusercontent.com/6818236/40263986-166b73dc-5ae9-11e8-92ba-53cd64799d73.png)

**Comment by kizniche** [comment]
Can you try applying the change in the commit I just pushed, then restart the frontend (Config->Restart Frontend) and see if there's a different error message?

**Comment by CriticalFlaw** [comment]
Updated and restarted, getting the same error message.

**Comment by kizniche** [comment]
If it's the ``exact`` same message, then you're not running the latest code.

**Comment by kizniche** [comment]
Just to clarify, the commit referenced in this thread with the fix for the exception-handling is not included in the 6.1.1 release. You will have to manually edit the file, save, then restart the frontend for the changes to take effect.
