### ISSUE TITLE
Question: Time dependent alerts?

### ISSUE THREAD

**Issue by fry42** [kizniche/Mycodo#473]
Hi,

Is there a way to make alerts trigger only in certain timespans?

Recently all the timed functions in my system stopped working so I started thinking about ways to set alerts.

I.e. If you have a light that should be on during the day and off in the night how would monitor it?
I can set alerts based on Output state or measurements (light sensor) but is there a way to set a timepoint or duration?

Unless I missed something and this isn't possible right now a useful way of implementing this would be to add "activate conditional" and "deactivate conditional" to the conditional functions.
This way you could activate alerts based on all the other existing conditionals..

Any thoughts?

**Comment by kizniche** [comment]
Conditionals can already be activated/deactivated by other conditionals, via the Activate/Deactivate Controller conditional action. The bigger issue is why aren't your time-based conditionals not working. Notifications for time-based activities can't be effectively used if the conditionals have issues.
