### ISSUE TITLE
Easy One - pigpiod_low.servic Executable path is not absolute

### ISSUE THREAD

**Issue by mrplow** [kizniche/Mycodo#487]
## Mycodo Issue Report:
  - Specific Mycodo Version: 6.1.2
 
### Errors
  - was reviewing dmesg output and noticed:
`[    2.928481] systemd[1]: [/home/pi/Mycodo/install/pigpiod_low.service:8] Executable path is not absolute, ignoring: killall pigpiod`

### Steps to Reproduce the issue:
dmesg
 
### Additional Notes
it'll try figure out git one day and make pull requests for simple fixes like these one day...

```
pi@raspberrypi:~ $ cat /tmp/fix.patch 
--- /home/pi/Mycodo/install/pigpiod_low.service	2018-05-23 06:26:23.000000000 -0700
+++ /home/pi/Mycodo/install/pigpiod_low.service.fix	2018-05-30 18:14:00.733356438 -0700
@@ -5,7 +5,7 @@
 [Service]
 Type=forking
 ExecStart=/usr/local/bin/pigpiod -s 1
-ExecStop=killall pigpiod
+ExecStop=/usr/bin/killall pigpiod
 ExecReload=/bin/kill -HUP $MAINPID
 Restart=always
 RestartSec=5s
```

**Comment by kizniche** [comment]
Thanks!
