### ISSUE TITLE
Ability to change Timelapse output location?

### ISSUE THREAD

**Issue by eyeconoklast** [kizniche/Mycodo#498]
Running Mycodo 6.1.3 

I'm doing timelapse but I keep filling up my SD card too quick.  Is it possible to set an external drive like a USB drive as the save location for the camera?  

As a possible future enhancement, being able to change that from the cameras page would be great.  

Thanks again for your hard work, Mycodo is amazing!

**Comment by kizniche** [comment]
I like this idea. I'll add an option to change the save location.
