### ISSUE TITLE
enhancement Add Liquid Flow Meter

### ISSUE THREAD

**Issue by leoneo** [kizniche/Mycodo#511]
Hi !
I have this Liquid Flow Meter https://www.adafruit.com/product/828 

Can you please add this sensor ? With reset option ?
Thank you so much 
Léo

**Comment by kizniche** [comment]
There is already an RPM Input that should be able to work if you connect the device properly. From this you can use an Equation Math controller to convert the RPM to a flow rate. Have you done anything in the way of attempting to connect it to your Pi?

**Comment by kizniche** [comment]
The Pi pins require 3.3 volts, so you will have to drop the voltage output from the sensor (5-24VDC in). I would think a voltage divider would suffice for this. Make sure you don't exceed the max current for the Pi's pin.

**Comment by leoneo** [comment]
Thanks for your good remark ! I have make a voltage divider with two resistors.

Now i will try with RPM input and equation math

**Comment by kizniche** [comment]
Have you had any luck with what you mentioned you were going to attempt?

**Comment by kizniche** [comment]
Any update on testing this?
