### ISSUE TITLE
PID controller not activating 

### ISSUE THREAD

**Issue by cbaymac** [kizniche/Mycodo#512]
## Mycodo Issue Report:
  - Specific Mycodo Version:
I am trying to control humidity with readings from a DHT22 (working) and a hydro mister connected to GPIO2. I can mannually turn on the mister using the output ON function, but the PID controller will not activate the mister. Example: current humidity is 60%, desired humidity in the function is 90%. All setting look good in the function and have worked before but not working now.
 
#### Problem Description
Please list:

  - what were you trying to do - turn on mister with PID controller
  - specific setup details that are involved Outputs are set up and working with DHT22 GPIO 18 and Mister on GPIO 2
 
### Errors
  - List any errors you encountered. No errore
  - Copy and pasting crash logs, or link to any specific
code lines you've isolated (please use GitHub permalinks for this)

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. step 1
 2. step 2...
 3. etc
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue? Photos attached.
![humidity](https://user-images.githubusercontent.com/20534226/43680758-87f6334e-980f-11e8-8aac-6aad8b5ef4fb.JPG)
![not on](https://user-images.githubusercontent.com/20534226/43680759-8802e90e-980f-11e8-9f64-927d9a13f488.JPG)
![function](https://user-images.githubusercontent.com/20534226/43680760-880cf28c-980f-11e8-9b4c-320e14370e14.JPG)

**Comment by kizniche** [comment]
Your graph should look like this:

![screenshot-192 168 0 9-2018-08-04-19-26-16](https://user-images.githubusercontent.com/838427/43681551-4e0bdabe-981c-11e8-9e33-0db2cf7994fb.png)
