### ISSUE TITLE
webcam problem

### ISSUE THREAD

**Issue by magichammer** [kizniche/Mycodo#519]
## Mycodo Issue Report:
  - Specific Mycodo Version:
 6.2.2
#### Problem Description
Please list: 
second webcam configuration problem, when i add the second webcam is impossible change the adress, es. /dev/video0 in /dev/video1, whem i save the change mycodo assign the always the key:/dev/video0
  - what were you trying to do
  - specific setup details that are involved
 
### Errors
  - List any errors you encountered.
  - Copy and pasting crash logs, or link to any specific
code lines you've isolated (please use GitHub permalinks for this)

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. step 1
 2. step 2...
 3. etc
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
Thanks. I'll look into this and get a fix pushed for the next release.
