### ISSUE TITLE
PWM Fan control and RPM monitoring possible?

### ISSUE THREAD

**Issue by floriske** [kizniche/Mycodo#526]
I couldn't really find a conclusive answer to this and I'm completely new to Raspberry-Pi's and Mycodo so please excuses me if I'm asking a "dumb" question here or if this is the wrong place to ask it:

I'm planning on building a curing chamber controlled with Mycodo and would like to know if the following is possible:

- Place 2 identical PWM fans in the chamber (a customized fridge)
- the first one (inlet) PWM controlled by Mycodo (preferably with RPM monitoring)
- the second one (outlet) used as a flow meter/anemometer, so just measure the RPM (the fan won't be driven electrically but by the airflow created by the inlet fan)
- control the inlet fan rpm with PWM, based on the outlet rpm

The idea behind this is that it will give me the ability to more precisely control/determine the airflow inside the chamber

**Comment by kizniche** [comment]
Mycodo has the ability to output PWM signals as well as measure RPM based on voltage pulses (you'll have to develop the proper hardware to ensure the Pi receives the proper signal). This input can be coupled with this output in a PID controller to regulate the output PWM in response to the input RPM to regulate the RPM to a desired setpoint. I've never built such a system, but the capability is there in Mycodo.

Relevant sections of the manual:

https://github.com/kizniche/Mycodo/blob/master/mycodo-manual.rst#pwm

https://github.com/kizniche/Mycodo/blob/master/mycodo-manual.rst#pid-controller

**Comment by floriske** [comment]
Thanks, I'll look into it!
