### ISSUE TITLE
Adding notes to Mycodo

### ISSUE THREAD

**Issue by Gossen1** [kizniche/Mycodo#527]
Just a thought that keeps popping up. I would love the ability to add notes to Mycodo. For example: "On the 12th of may at 13:00 I added an extra fan to room 1." So I can see the effect more easily in the graph. My 2 pennies. Thanks!

**Comment by kizniche** [comment]
This was added in #28, but had to be removed when the whole system was refactored. I'll look into adding this feature again.

**Comment by frodus17** [comment]
This is very useful (looked at #28). Right now it's in my Kegerator, but soon I'll be gutting my other temp chamber to run Mycodo. It'll be my Fermentation chamber, so adding notes to it would be super useful.

**Comment by kizniche** [comment]
Tags and Notes can now be added, and notes can be searched by tag and contents of the note. Next is to integrate the notes into graphs.

![screenshot-192 168 0 9-2018 09 11-22-13-13](https://user-images.githubusercontent.com/838427/45397995-7563b200-b610-11e8-8aae-f94ae4628955.png)

**Comment by kizniche** [comment]
More work on the filtering/sorting of notes:

![screenshot-192 168 0 9-2018 09 12-16-52-37](https://user-images.githubusercontent.com/838427/45452977-739bfc00-b6ad-11e8-8a0c-6cc0dde9151d.png)

I'll tackle making them appear in graphs next. I also still need to implement file attachments, but that should be relatively easy.

**Comment by kizniche** [comment]
After much toiling, I finally got note flags to appear on graphs!

![screenshot-192 168 0 9-2018 09 12-21-03-25](https://user-images.githubusercontent.com/838427/45461176-7d365b80-b6cf-11e8-9938-fd02f77b1cd8.png)

**Comment by kizniche** [comment]
Who ever said this was going to be easy? :rofl: 

![screenshot-192 168 0 9-2018 09 12-21-34-35](https://user-images.githubusercontent.com/838427/45461960-c1c3f600-b6d3-11e8-913d-9b61232bdec8.png)

**Comment by kizniche** [comment]
The notes feature is nearly complete. Here's the current state:

![screenshot_2018-09-13 tango - notes - mycodo 6 3 0](https://user-images.githubusercontent.com/838427/45509716-5aa35180-b766-11e8-9c0d-7359c7197082.png)

![screenshot_2018-09-13 tango - dashboard - mycodo 6 3 0](https://user-images.githubusercontent.com/838427/45509725-5d05ab80-b766-11e8-8d6a-2c90f2ec8956.png)

**Comment by kizniche** [comment]
With that last commit, I think I've accomplished everything on my feature list for a basic note system. I'll review and test all the new features (single-file input module system and the new note system), and try to get a new release out this weekend.

**Comment by kizniche** [comment]
![screenshot_2018-09-14 tango - edit note - mycodo 6 3 0](https://user-images.githubusercontent.com/838427/45523059-12e7ee80-b795-11e8-8395-a92d0d209fd2.png)
