### ISSUE TITLE
Incorrect conversion of Fahrenheit to Celsius in Async Graph

### ISSUE THREAD

**Issue by not5** [kizniche/Mycodo#533]
## Mycodo Issue Report:
  - Specific Mycodo Version: 6.2.2
 
#### Problem Description
Please list: 
  - Async graph is assuming a Celsius unit when data are in Fahrenheit
  - Because Async thinks data are in Celsius, it is performing a conversion to Fahrenheit.

![screenshot_20180913-224404_chrome](https://user-images.githubusercontent.com/43415025/45763485-8e66f700-bbfe-11e8-995a-2641d49a8b02.jpg)

**Comment by kizniche** [comment]
Does this occur in the latest version?

**Comment by not5** [comment]
Upon checking, this is fixed in the current version. Thank you.
