### ISSUE TITLE
Error reading data from sht75 sensor 

### ISSUE THREAD

**Issue by darshanmg** [kizniche/Mycodo#534]
I have been using the sht-sensor package to read data from my sht75 sensors and this error keeps popping up.

`
raceback (most recent call last):
  File "/home/pi/tests.py", line 6, in <module>
    t0=Sht(3, 22).read_t()
  File "/usr/local/lib/python2.7/dist-packages/sht_sensor/sensor.py", line 306, in read_t
    t_raw = self._get_meas_result(self.cmd.t)
  File "/usr/local/lib/python2.7/dist-packages/sht_sensor/sensor.py", line 246, in _get_meas_result
    self._send(cmd)
  File "/usr/local/lib/python2.7/dist-packages/sht_sensor/sensor.py", line 209, in _send
    raise ShtCommFailure('Command ACK failed on step-2')
ShtCommFailure: Command ACK failed on step-2
`
I tried running it from the command line, checked if they were getting the proper signals and this problem still persists. I had not been using them for a while and when i got back to it, i had this problem.

**Comment by kizniche** [comment]
Have you attempted to acquire a measurement from Mycodo? From the traceback, it appears you're not doing that.

**Comment by darshanmg** [comment]
Yes, its not from mycodo, i just ran a simple python program to read data from the sensor

**Comment by kizniche** [comment]
I'll hook up my sht75 and see if I can reproduce the issue.

**Comment by darshanmg** [comment]
okay thanks. i just used the code on python 2.7. it used to work before like in February beginning but now it doesn't.

**Comment by kizniche** [comment]
Sorry this has taken so long. I was traveling, then went on vacation, then left for a big backpacking trip. I'm now back and will attempt to get my sensor working this evening.

**Comment by kizniche** [comment]
I accidentally killed my sensor by hooking it up with revered polarity. Smoke and everything, the sensor even melted from the PCB. So, that was my only SHT75, so I'm sorry to say I won't be able to diagnose your issue. If you happen to install Mycodo to test your sensor, let me know if you have any issues.
