### ISSUE TITLE
Xiamo bluepy

### ISSUE THREAD

**Issue by RynFlutsch** [kizniche/Mycodo#540]
## Mycodo Issue Report:
  - Specific Mycodo Version:
6.3.9
 
#### Problem Description
![d620043f-c378-4fe1-aa27-7ac665625bb8](https://user-images.githubusercontent.com/29811876/46503849-68f80100-c82c-11e8-9697-78e49acd3e13.png)

what were you trying to do

  Add new Xiaomi BT Sensor.
Instal the missing dependency

**Comment by kizniche** [comment]
Strange. I'll investigate.

**Comment by kizniche** [comment]
I wasn't able to reproduce this issue. I rearranged the order of installing the dependent packages for the sensor, which ***may*** fix your issue. However, I believe there may just be an issue with your virtualenv (i.e. corrupt file, bad SD card, etc.). After I release v6.4.0 (any day now), I would recommend reinstalling Mycodo to test if the issue persists. Feel free to reopen this issue if the issue persists and we can investigate further.

**Comment by RynFlutsch** [comment]
Working
but i can only use batterie status and temperature for graphs, functions ...
Moisture, Light and Conductivity only @ LivePage for watching

**Comment by RynFlutsch** [comment]
6.4.5
