### ISSUE TITLE
Quick bug in update_command.sh

### ISSUE THREAD

**Issue by not5** [kizniche/Mycodo#544]
Looks like you've hard coded the location for python3.5 as /usr/bin/python3.5. You should probably use a variable here and look up the system location for python3.5's bin.

Eg. my python3.5 directory was in /usr/local/bin/python3.5

**Comment by kizniche** [comment]
At least with the environment I'm developing for, the binary location should be the same across all systems. Though, I agree there is a benefit to your recommendation, that being the eventual ability to operate on systems besides Raspberry Pis running Raspbian Stretch (such as banana Pi, beagle board, etc).

**Comment by not5** [comment]
Running Jessie on KivyPie.
I manually changed the location in the script for my own use, but less savy users may not have figured it out right away.
