### ISSUE TITLE
Xiaomi Miflora

### ISSUE THREAD

**Issue by RynFlutsch** [kizniche/Mycodo#557]
Mycodo 6.4.5.

 I can only use batterie status and temperature for graphs, functions ...
Moisture, Light and Conductivity are only @ LivePage for watching

**Comment by kizniche** [comment]
What do you mean by you "can only use"? Can you be more detailed?

I see every Miflora measurement showing up in my PID Measurement setting.

**Comment by RynFlutsch** [comment]
Hmm thats weird:
![bildschirmfoto-1](https://user-images.githubusercontent.com/29811876/47604462-7bfc8c00-d9fa-11e8-9069-3903de8b48f7.png)

**Comment by kizniche** [comment]
Try deleting your input and adding it again.

**Comment by kizniche** [comment]
Thanks. That detail should help me find the bug later.

**Comment by RynFlutsch** [comment]
With the second MiFlora, the problem occur without activating the Sensor.

**Comment by kizniche** [comment]
I haven't had a chance to look at this, but I'm going to incorporate the fix in the 7.0 release. Progress with 7.0 has been steady, but I've slated more framework changes than I initially anticipated, so I'm looking at making the release mid to later this month. If I push a fix to the 7.0 branch, I'll reference this issue so you can manually apply the fix if you desire.
