### ISSUE TITLE
PH Circuit no Data over i2c

### ISSUE THREAD

**Issue by HugoPenner** [kizniche/Mycodo#564]
Hi,

first of all Thanks for all your hard work on this project.

## Mycodo Issue Report:

  - Mycodo Version: 6.4.5
  - Pi3 B+
  - Atlas EZO pH Circuit
  - Atlas Electrically Isolated EZO Carrier Board
  - i2c and GPIO pins 3 ( SDA.1),5 (SCL.1)
 
#### Problem Description
Please list:

After a fresh installation of MyCodo i added the Atlas EZO Ph Circuit in the Input Tab.

![mycodo-setup](https://user-images.githubusercontent.com/16592707/48504182-6c77a280-e844-11e8-93f2-479da46a6321.PNG)

But i do net get any reading on the Live tab.
![mycodo-live](https://user-images.githubusercontent.com/16592707/48504281-a9dc3000-e844-11e8-805a-22aaa80dc163.PNG)

Then i tried the Sample Code from atlas-scientific and it works fine.

![atlas-samplecode](https://user-images.githubusercontent.com/16592707/48504373-e314a000-e844-11e8-87de-96013f2ffc44.PNG)

 
### Errors

i think i dont have any Errors in the Daemon Log.

Thanks for any intake you have on this!

Hugo

**Comment by kizniche** [comment]
The Atlas code in Mycodo is pretty difficult to debug without the sensor (I don't have the EC sensor). Could you provide me SSH access (user pi) and an admin user for the Mycodo UI? If so, I could probably find the issue fairly quickly. You can contact me at http://kylegabriel.com/contact

**Comment by HugoPenner** [comment]
I send you an PM to http://kylegabriel.com/contact
