### ISSUE TITLE
Suggestion: Adding VPD calculation to Inputs on Dashboard

### ISSUE THREAD

**Issue by BobDDole** [kizniche/Mycodo#572]
Along with the Temp, Humidity, & Dewpoint Inputs is it possible to add Vapor Pressure Deficit
as a Input as well?

**Comment by BobDDole** [comment]
Yes indoors VPD is a very useful metric and would be a welcome addition to inputs. 
I would add it myself if I knew python. Calculation values seem to be done in mycodo/inputs/sensorutils.py And the valid ones are defined in the sensors related python file (IE mine is dht22.py).
Really wish I knew python enough to whip this up but alas I suck at programming languages.
BTW Theoi, I was going to include the EXACT same link you did for calculation, LOL
Thanks for giving the info

**Comment by SAM26K** [comment]
Suggest creating a general math module input where real inputs from sensors can be parameters of a formula that generates an output that can be used for logging and triggering events.

**Comment by kizniche** [comment]
I could add VPD as a measurement for inputs that return temperature and RH, as well as a math controller that can have temperature and RH selected from one or two different inputs. In 7.0, the user can select which measurements are stored from the sensor, so you can have many potential measurements returned and storage space isn't wasted if you don't want them by disabling them. One of the easy features I implemented with the new measurement system.

**Comment by kizniche** [comment]
I implemented VPD returning for inputs that measure at least temperature and RH. I'll add the math controller later, but just wanted to give an update showing it calculating the proper VPD from the measurements (dummy data) that align with the expected result from the example in the provided link (above), using the equations for SVP and VPD.

![screenshot-192 168 0 9-2018 11 29-15-05-02](https://user-images.githubusercontent.com/838427/49248743-6f4bc900-f3e8-11e8-8bc9-cfbffa73ebed.png)

**Comment by kizniche** [comment]
Closing issue because both Input and Math VPD will be in the 7.0 release.

**Comment by BobDDole** [comment]
Thanks, you the man!
