### ISSUE TITLE
issue timeout system information

### ISSUE THREAD

**Issue by alcemyco** [kizniche/Mycodo#576]
## Mycodo Issue Report:
  - Specific Mycodo Version:6.4.5
 
#### Problem Description
Please list: 

  - trying to open system information 

 
### Errors
  -gateway timeout 504

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. step 1
 2. step 2...
 3. etc
 
### Additional Notes
no other issues hve been presented in the gui.

**Comment by kizniche** [comment]
If you don't provide steps to reproduce the error, there's little chance this can ever be resolved.

**Comment by kizniche** [comment]
I must have missed the "system information" part. I've found bugs that create perpetual processes that cause the fronted to timeout, but I've never experienced it on the system information page. @Theoi-Meteoroi makes a good point, that you should see if the issue persists with nothing connected, then add hardware one at a time until the issue reappears.
