### ISSUE TITLE
Add Math Input

### ISSUE THREAD

**Issue by shortyishere** [kizniche/Mycodo#580]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.0.0
 
#### Problem Description
Please list:
When I go to add a math block it shows only average multiple input on the drop down list but when i add it it has the right math block.

Probably just need to change the descriptor

  - what were you trying to do
  - specific setup details that are involved
 
### Errors
  - List any errors you encountered.
  - Copy and pasting crash logs, or link to any specific
code lines you've isolated (please use GitHub permalinks for this)

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. step 1
 2. step 2...
 3. etc
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
Well, I don't know how I let that slip. Thanks for the report. I fixed this in the last commit, and will be live in the 7.0.1 release.
