### ISSUE TITLE
Dashboard TH16 measurement units display wrong.

### ISSUE THREAD

**Issue by SAM26K** [kizniche/Mycodo#583]
## Mycodo Issue Report:
  - Specific Mycodo Version:7.0.2
 
#### Problem Description
Measurement display on dashboard for TH16/10 not right when default not used.
Affects deg F and KPa.  See screen shot.
![image](https://user-images.githubusercontent.com/22091149/50381418-73f84b80-063b-11e9-9955-db578a911747.png)

Attached the updated python module with url request code for Sonoff TH16/10.   Only ip address needs to be changed for specific installed device.  This requires Tasmota firmware to be flashed to the Sonoff's ESP8266.  #https://github.com/arendst/Sonoff-Tasmota
[TH16D.zip](https://github.com/kizniche/Mycodo/files/2705881/TH16D.zip)

**Comment by SAM26K** [comment]
Also  affects dew point conversion to deg F.

**Comment by kizniche** [comment]
Just added. Thanks for the testing. This will be live in v7.0.3 with the option to set the IP address.

**Comment by kizniche** [comment]
...This also happened to be the 4000th commit for Mycodo.

**Comment by SAM26K** [comment]
Great job and thanks very much!

**Comment by SAM26K** [comment]
I'm using a linux command output control to switch the relay on and off as follows:
curl http://192.168.1.34/cm?cmnd=Power%20on
curl http://192.168.1.34/cm?cmnd=Power%20off
Would be nice if you  could include that with the new Sonoff device module when you get time. Only ip address would be unique.
Thanks Again.
