### ISSUE TITLE
New Input: AM2320

### ISSUE THREAD

**Issue by pmunz75** [kizniche/Mycodo#585]
Hi Kyle,

Can you add support for the Adafruit AM2320 Digital Temperature and Humidity Sensor ?
https://www.adafruit.com/product/3721
PDF: https://akizukidenshi.com/download/ds/aosong/AM2320.pdf
****
Is it possible to use this PH sensor? Liquid PH Sensor+BNC Probe

https://www.ebay.de/itm/Liquid-PH-0-14-Value-Detect-Sensor-Module-PH-Electrode-Probe-BNC-for-Arduino/272498830730?hash=item3f72322d8a:m:m-HAbGWjCIs9OJGXTx-fYew:rk:1:pf:1&frcectupt=true

many thanks for info
pmunz75

**Comment by SAM26K** [comment]
Also interested in the above ph probe.  I notice it has a ESP8266 wireless chip. It's the same chip that Sonoff uses for its devices.  If you want the wifi to be Mycodo accessible  you will probably have to use 3rd party firmware.  I used Tasmota for my Sonoff device but not sure if Tasmota lists that ph probe.  If not you can request it to be added.  Tasmota firmware for wifi is better than the manufacturers who tend to hang their code off a central server on the internet they control.  Tasmota only depends on a local wifi signal and doesn't depend on the internet.

**Comment by kizniche** [comment]
@pmunz75 I just added an untested AM2320 Input module, but before I make the 7.0.3 release, culd you test the code? You can copy the code, below, to a new file (such as ```test_input_01.py```), then import it through the Configure -> Input menu in Mycodo. Then try to add and activate the input. Check the daemon log for errors.

```python
# coding=utf-8
import logging
from time import sleep

from struct import unpack

from mycodo.databases.models import DeviceMeasurements
from mycodo.inputs.base_input import AbstractInput
from mycodo.inputs.sensorutils import calculate_dewpoint
from mycodo.inputs.sensorutils import calculate_vapor_pressure_deficit
from mycodo.utils.database import db_retrieve_table_daemon

# Measurements
measurements_dict = {
    0: {
        'measurement': 'temperature',
        'unit': 'C'
    },
    1: {
        'measurement': 'humidity',
        'unit': 'percent'
    },
    2: {
        'measurement': 'dewpoint',
        'unit': 'C'
    },
    3: {
        'measurement': 'vapor_pressure_deficit',
        'unit': 'Pa'
    }
}

# Input information
INPUT_INFORMATION = {
    'input_name_unique': 'AM2320',
    'input_manufacturer': 'AOSONG',
    'input_name': 'AM2320',
    'measurements_name': 'Humidity/Temperature',
    'measurements_dict': measurements_dict,
    'measurements_rescale': False,

    'options_enabled': [
        'measurements_select',
        'period',
        'pre_output'
    ],
    'options_disabled': ['interface', 'i2c_location'],

    'dependencies_module': [
        ('pip-pypi', 'smbus2', 'smbus2')
    ],
    'interfaces': ['I2C'],
    'i2c_location': ['0x5c'],
    'i2c_address_editable': False
}


class InputModule(AbstractInput):
    """
    A sensor support class that measures the AM2320's humidity and temperature
    and calculates the dew point

    """
    def __init__(self, input_dev, testing=False):
        super(InputModule, self).__init__()
        self.logger = logging.getLogger('mycodo.inputs.am2320')
        self.name = INPUT_INFORMATION['input_name_unique']
        self._measurements = None
        self.powered = False
        self.sensor = None

        if not testing:
            from mycodo.mycodo_client import DaemonControl
            self.logger = logging.getLogger(
                'mycodo.am2320_{id}'.format(id=input_dev.unique_id.split('-')[0]))

            self.device_measurements = db_retrieve_table_daemon(
                DeviceMeasurements).filter(
                    DeviceMeasurements.device_id == input_dev.unique_id)

            self.i2c_bus = input_dev.i2c_bus
            self.power_output_id = input_dev.power_output_id
            self.control = DaemonControl()
            self.start_sensor()
            self.sensor = AM2320(self.i2c_bus,logger=self.logger)

    def get_measurement(self):
        """ Gets the humidity and temperature """
        return_dict = measurements_dict.copy()

        self.sensor.read()

        if self.is_enabled(0):
            return_dict[0]['value'] = self.sensor.temperature

        if self.is_enabled(1):
            return_dict[1]['value'] = self.sensor.humidity

        if (self.is_enabled(2) and
                self.is_enabled(0) and
                self.is_enabled(1)):
            return_dict[2]['value'] = calculate_dewpoint(
                return_dict[0]['value'], return_dict[1]['value'])

        if (self.is_enabled(3) and
                self.is_enabled(0) and
                self.is_enabled(1)):
            return_dict[3]['value'] = calculate_vapor_pressure_deficit(
                return_dict[0]['value'], return_dict[1]['value'])

        return return_dict


class AM2320(object):
    """
    AM2320 temperature and humidity sensor class.
    
    original source: https://github.com/8devices/IoTPy/

    :param interface:  I2C interface id.
    :type interface: :int
    :param sensor_address: AM2320 sensor I2C address. Optional, default 0x5C (92).
    :type sensor_address: int
    """

    I2C_ADDR_AM2320 = 0x5c  # 0xB8 >> 1
    PARAM_AM2320_READ = 0x03
    REG_AM2320_HUMIDITY_MSB = 0x00
    REG_AM2320_HUMIDITY_LSB = 0x01
    REG_AM2320_TEMPERATURE_MSB = 0x02
    REG_AM2320_TEMPERATURE_LSB = 0x03
    REG_AM2320_DEVICE_ID_BIT_24_31 = 0x0B

    def __init__(self, interface, sensor_address=0x5c, logger=None):
        from smbus2 import SMBus
        self.logger = logger
        self.interface = interface
        self.address = sensor_address
        self.temperature = -1000.0
        self.humidity = -1
        self.bus = SMBus(interface)

    def _read_raw(self, command, regaddr, regcount):
        try:
            self.bus.write_i2c_block_data(
                self.address, 0x00, [])
            self.bus.write_i2c_block_data(
                self.address, command, [regaddr, regcount])

            sleep(0.002)

            buf = self.bus.read_i2c_block_data(self.address, 0, 8)
        except Exception:
            self.logger.error("AM2320 Read error")
            return None

        buf_str = "".join(chr(x) for x in buf)

        crc = unpack('<H', buf_str[-2:])[0]
        if crc != self._am_crc16(buf[:-2]):
            self.logger.error("AM2320 CRC error.")
        return buf_str[2:-2]

    def _am_crc16(self, buf):
        crc = 0xFFFF
        for c in buf:
            crc ^= c
            for i in range(8):
                if crc & 0x01:
                    crc >>= 1
                    crc ^= 0xA001
                else:
                    crc >>= 1
        return crc

    def read_uid(self):
        """
        Read and return unique 32bit sensor ID.

        :return: A unique 32bit sensor ID.
        :rtype: int
        """
        resp = self._read_raw(
            self.PARAM_AM2320_READ,
            self.REG_AM2320_DEVICE_ID_BIT_24_31, 4)
        uid = unpack('>I', resp)[0]
        return uid

    def read(self):
        """
        Read and store temperature and humidity value.

        Read temperature and humidity registers from the sensor,
        then convert and store them.
        Use :func:`temperature` and :func:`humidity` to retrieve these values.
        """
        raw_data = self._read_raw(
            self.PARAM_AM2320_READ,
            self.REG_AM2320_HUMIDITY_MSB, 4)
        self.temperature = unpack('>H', raw_data[-2:])[0] / 10.0
        self.humidity = unpack('>H', raw_data[-4:2])[0] / 10.0
```

**Comment by kizniche** [comment]
Also, the probe you linked to outputs a voltage signal relative to the pH, and since the Raspberry Pi doesn't have an integrated analog-to-digital converter, you'll need to get one of these. You can see what [ADCs are supported in the manual](https://github.com/kizniche/Mycodo/blob/master/mycodo-manual.rst#analog-to-digital-converters).

**Comment by SAM26K** [comment]
@pmunz75 if you are using a raspberry pi, I used a Waveshare ADS1256 shield pcb.  Nice if you need multiple analog channels and has pass through GPIO so you can piggy back more connectors on top of it.
Been using it with Mycodo for a few weeks now and working well.
https://www.waveshare.com/wiki/High-Precision_AD/DA_Board

**Comment by kizniche** [comment]
I've also seen many people have issues getting these types of pH sensors to calculate the proper pH, due to the sparse documentation (and it being in an Asian language). If you like having a potentially difficult or impossible project, this may be it, otherwise I'd recommend a more user-friendly system like [Atlas Scientific](https://www.atlas-scientific.com/ph.html) makes.

**Comment by kizniche** [comment]
However, I could be wrong. I didn't find documentation with the links provided, but it could very well have a good set of documentation and example code provided.

**Comment by SAM26K** [comment]
Noticed that too.  Very little documentation.  Only thing I could find was this forum page that seems to have a schematic of the device.  Would have to check the hardware to see if it matches.  It looks like all     you have to do is get 7.0 and 4.0 pH cal solutions and it has a zero and gain pot. 
https://forum.arduino.cc/index.php?topic=336012.0
There are other similar probes with better docs though as Kyle said.

**Comment by kizniche** [comment]
@pmunz75 Can you paste any daemon log errors from the am2320 module?

**Comment by pmunz75** [comment]
2018-12-26 15:13:39,067 - mycodo.input_1917cc71 - INFO - Activated in 219.7 ms
2018-12-26 15:13:39,072 - mycodo.am2320_1917cc71 - ERROR - AM2320 Read error
2018-12-26 15:13:39,073 - mycodo.am2320_1917cc71 - ERROR - InputModule raised an exception when taking a reading: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/inputs/base_input.py", line 117, in read
    self._measurements = self.get_measurement()
  File "/home/pi/Mycodo/mycodo/inputs/am2320.py", line 91, in get_measurement
    self.sensor.read()
  File "/home/pi/Mycodo/mycodo/inputs/am2320.py", line 200, in read
    self.temperature = unpack('>H', raw_data[-2:])[0] / 10.0
TypeError: 'NoneType' object is not subscriptable
2018-12-26 15:13:45,865 - mycodo.inputs.atlas_ph_None_99 - ERROR - Sensor read unsuccessful: [Errno 121] Remote I/O error
2018-12-26 15:13:54,010 - mycodo.am2320_1917cc71 - ERROR - AM2320 Read error
2018-12-26 15:13:54,011 - mycodo.am2320_1917cc71 - ERROR - InputModule raised an exception when taking a reading: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/inputs/base_input.py", line 117, in read
    self._measurements = self.get_measurement()
  File "/home/pi/Mycodo/mycodo/inputs/am2320.py", line 91, in get_measurement
    self.sensor.read()
  File "/home/pi/Mycodo/mycodo/inputs/am2320.py", line 200, in read
    self.temperature = unpack('>H', raw_data[-2:])[0] / 10.0
TypeError: 'NoneType' object is not subscriptable

**Comment by pmunz75** [comment]
Hy,
Sorry the AM2320 not work.
no value in LIVE Screen ( zero output ) 
if I use the AM2315 protocol / driver for the AM2320 Sensor it works fine

**Comment by kizniche** [comment]
I just pushed a potential fix for the AM2320 input module. You can test the module by upgrading to master or copying the code to a new module and importing it through the Config/Input menu.

**Comment by pmunz75** [comment]
Thank I will test now.



© 2019 munz.co

**Comment by pmunz75** [comment]
Hello ,
Sorry AM2320 no Work / Values

Daemon Log : 
2019-01-06 13:48:55,106 - mycodo.input_f15e0773 - INFO - Deactivated in 39.7 ms
2019-01-06 13:49:04,831 - mycodo.input_f15e0773 - INFO - Activated in 440.9 ms
2019-01-06 13:49:04,832 - mycodo.am2320_f15e0773 - ERROR - [Errno 121] Remote I/O error
2019-01-06 13:49:19,584 - mycodo.am2320_f15e0773 - ERROR - [Errno 121] Remote I/O error
2019-01-06 13:49:34,633 - mycodo.am2320_f15e0773 - ERROR - [Errno 121] Remote I/O error
2019-01-06 13:49:34,655 - mycodo.input_f15e0773 - ERROR - StopIteration raised. Possibly could not read input. Ensure it's connected properly and detected.
2019-01-06 13:49:49,583 - mycodo.am2320_f15e0773 - ERROR - [Errno 121] Remote I/O error

and Screenshoots : 

![bildschirmfoto 2019-01-06 um 13 49 07](https://user-images.githubusercontent.com/41070785/50736168-4faf7980-11ba-11e9-9a51-87634d15e85b.png)

![bildschirmfoto 2019-01-06 um 13 49 38](https://user-images.githubusercontent.com/41070785/50736171-5807b480-11ba-11e9-9170-c3881f099afd.png)

**Comment by kizniche** [comment]
Can you confirm the AM2315 module works as expected (accurate values) for the AM2320?

**Comment by kizniche** [comment]
I changed the AM2320 Input code. If you have time, let me know if it works once the next release happens.
