### ISSUE TITLE
Please add PiOLED 128x64

### ISSUE THREAD

**Issue by pmunz75** [kizniche/Mycodo#589]
Hello,
can you please add this  display ( PiOLED 128x64 )
maybe it is also possible to output graphics ? or 8 lines ?

https://learn.adafruit.com/ssd1306-oled-displays-with-raspberry-pi-and-beaglebone-black/usage

Many Thanks

**Comment by kizniche** [comment]
Added the 128x64 OLED with support for 8 lines. It's possible to output graphics but I'm not sure how well this would integrate with mycodo.

**Comment by kizniche** [comment]
Will be included with the v7.1.6 release.
