### ISSUE TITLE
PID only works in Celcius?

### ISSUE THREAD

**Issue by not5** [kizniche/Mycodo#594]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.0.3
 
#### Problem Description
Trying to do a temperature PID controller with Fahrenheit measurement.
 
### Errors:
PID doesn't function. Widget has a bunch of Naan values.

### Steps to Reproduce the issue:
Have sensor converted to Fahrenheit and try to use a PID controller to manipulate.
 
### Additional Notes
PID should be able to attempt to raise/lower any value, not just even temperature. I have confirmed that an unconverted Celcius measurement from the same sensor works correctly.

**Comment by not5** [comment]
FYI, error in daemon log was "2019-01-06 08:59:41,142 - mycodo.pid_fbe54cb3 - WARNING - No data returned from influxdb"

**Comment by kizniche** [comment]
Thanks for the bug report. I'm working on a fix for this now.

**Comment by kizniche** [comment]
Fixed and will be found in the future 7.0.4 release.

**Comment by not5** [comment]
You're the man!
