### ISSUE TITLE
can not be deactivated / activated / Delete / Save ...

### ISSUE THREAD

**Issue by pmunz75** [kizniche/Mycodo#595]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.0.3
 
#### Problem Description
Function and other can not be deactivated / activated / Delete / Save ...
if no action is selected.
 
![bildschirmfoto 2019-01-06 um 20 32 01](https://user-images.githubusercontent.com/41070785/50740695-7e494680-11f2-11e9-91e6-c20d5964ae06.png)

**Comment by kizniche** [comment]
I haven't been able to replicate this issue. What browsers have you tested this with? This behavior isn't found with the latest versions of Firefox or Chrome.

**Comment by pmunz75** [comment]
i use latest versions of Firefox.

**Comment by kizniche** [comment]
Test another browser to determine if it is an issue with your browser.

**Comment by pmunz75** [comment]
i tested Safari , the same problem .

**Comment by kizniche** [comment]
Sounds like an issue with your install, since you are the only user experiencing this issue. Reinstall Mycodo and see if that fixes the issue.

**Comment by pmunz75** [comment]
ok thanks.

**Comment by kizniche** [comment]
I was finally able to replicate this issue.

**Comment by not5** [comment]
I applied the new files and it's still not quite right. Still having error on trying to add an Action.

**Comment by kizniche** [comment]
An action for what?

**Comment by kizniche** [comment]
Does "applied the new files" mean you upgraded to master?

**Comment by not5** [comment]
Sorry, should have been more specific. I overwrote the files associated with your change (the three flask forms).

Not working for a conditional. Must select an input in order to do anything, like add an action or even activate/deactivate.

**Comment by kizniche** [comment]
There were more edits than those. Best to upgrade to master if you want to test, otherwise, wait until the next version release.
