### ISSUE TITLE
Output controls disappear from "outputs" when "reorder" is selected.

### ISSUE THREAD

**Issue by SAM26K** [kizniche/Mycodo#596]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.0.3
 
#### Problem Description
Output controls disappear from "outputs" web page tab when "reorder" is selected.  No reorder options.
This happened when creating output linux controls with a fresh install of 7.0.3. Control is still available on dashboard.  Using Chrome Version 71.0.3578.98 (Official Build) (64-bit) on a Win 7 Lenova laptop.

**Comment by kizniche** [comment]
Can you provide screenshots to describe what the issue is?

**Comment by kizniche** [comment]
Also, can you provide a step-by-step list of actions in order to reproduce this issue?

**Comment by SAM26K** [comment]
Unable to duplicate problem with release 7.0.5.
