### ISSUE TITLE
Set up edge function for pH sensor not working (same for T1000 sensor)

### ISSUE THREAD

**Issue by alonrab** [kizniche/Mycodo#600]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.04
 
#### Problem Description
Please list: 
I'm trying to set up a on off output trigger of GPIO pin for pH reading. 
I have an atlas pH sensor and on/off power relay
![image](https://user-images.githubusercontent.com/29787500/50986278-6a446400-14d4-11e9-9f59-dda945d601b6.png)
![image](https://user-images.githubusercontent.com/29787500/50987044-7c270680-14d6-11e9-935a-e5bb4519a440.png)

 
### Errors

When I'm trying to set up an edge, no data input option is available

![image](https://user-images.githubusercontent.com/29787500/50987110-a4166a00-14d6-11e9-8a06-539e608728d3.png)

Also, have to fill all the inputs  to delete the function

  - List any errors you encountered.
  - Copy and pasting crash logs, or link to any specific
code lines you've isolated (please use GitHub permalinks for this)

### Steps to Reproduce the issue:

How can this issue be reproduced?
 1. step 1
 2. step 2...
 3. etc
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by alonrab** [comment]
Thank you for looking into it!
Did steps 1 -6 : 
this is the data input-
![image](https://user-images.githubusercontent.com/29787500/50994825-493b3d80-14eb-11e9-9056-72587958a402.png)

Then step 1+2
![image](https://user-images.githubusercontent.com/29787500/50995023-d8485580-14eb-11e9-8507-bbb8a66e0dd9.png)
 
In the option box, selected: "measurement" 
in lower option box, selected : "output duration"

otherwise an error note show to select for lower box pops. 

Then selected pH probe and saved
![image](https://user-images.githubusercontent.com/29787500/50995201-66bcd700-14ec-11e9-814e-43edc0ce341a.png)

added action, selected GPIO and saved

![image](https://user-images.githubusercontent.com/29787500/50995309-c1563300-14ec-11e9-916b-1b7c7e09a5ea.png)

When trying to save- need to change box #1 #2 at bottom left
![image](https://user-images.githubusercontent.com/29787500/50995587-830d4380-14ed-11e9-87df-e034fc0da90d.png)

when press save, error say 
![image](https://user-images.githubusercontent.com/29787500/50995646-a89a4d00-14ed-11e9-845e-73884e9f84fb.png)

Any suggestions? 
Many many thanks

**Comment by kizniche** [comment]
This is a bug that's been fixed in the yet-to-be-released v7.0.5. For now, just select anything in those boxes (it won't matter what you select).

As for your error, it appears you did not replace the ID with your particular measurement ID. Looking at your screenshot, your measurement ID is "b927459a".

**Comment by alonrab** [comment]
I did,
This is the text input I placed:
if {fcc15238} is not None:
    if {fcc15238} is < 9:
        print(1)
else:
    print(0)  # False (Do not trigger actions)

Then:
If I press activate, it show no error but wont save the change
If I press save, then it show error.

![image](https://user-images.githubusercontent.com/29787500/50997851-afc45980-14f3-11e9-94b5-041249961c4e.png)

![image](https://user-images.githubusercontent.com/29787500/50997893-d4b8cc80-14f3-11e9-85ea-455aa7711950.png)


Any suggestions?
Many thanks,

**Comment by kizniche** [comment]
I just updated the manual with a [Conditional Setup Guide](https://github.com/kizniche/Mycodo/blob/master/mycodo-manual.rst#conditional-setup-guide). Let me know if it helps and if there is anything that can be done to improve it.

**Comment by alonrab** [comment]
Thanks a lot! its working great.
this is what confused me:
when looking for the ID - used the sensor ID instead of ID assigned at function conditional window
Then,  input from examples:
if None not in [{bdc127e}]: 
    if {0bdc127e} > 6 :
        print(1)
worked.
