### ISSUE TITLE
Sunrise/Sunset doesn't appear to have an option to select either one.

### ISSUE THREAD

**Issue by 0x0f906** [kizniche/Mycodo#618]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.1.5
 
#### Problem Description
Please list:

Sunrise/Sunset doesn't appear to have an option to select either one. 

Sunrise/Sunset function menu does not correlate with the Mycodo Manual. 

  - what were you trying to do
Activate/deactivate output at sunrise and sunset 
  - specific setup details that are involved
 
### Errors
  - List any errors you encountered.
  - Copy and pasting crash logs, or link to any specific
code lines you've isolated (please use GitHub permalinks for this)

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. step 1
Select sunrise/sunset in function.
 2. step 2...
 3. etc
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
This bug happened to affect all Triggers (preventing them from being configured properly), which I would consider a major bug. I just pushed a fix and released v7.1.6. Thanks for the bug report!

**Comment by kizniche** [comment]
After upgrading, you will have to delete the old Trigger and add a new one.
