### ISSUE TITLE
Forum for Non-Issue Discussion

### ISSUE THREAD

**Issue by kizniche** [kizniche/Mycodo#622]
I recently set up a forum for discussing Mycodo-related topics. If what you would like to discuss is not related to a legitimate bug in the Mycodo software, the forum will be the appropriate place to discuss. If you're unsure if what you've found is a bug or issue with the software, post in the forum, and if an issue with the software is found, a GitHub issue can then be created.

Use the link below to access the forum. If you would like to post, you will first need to register and verify your email address.

### [Mycodo Forum](https://kylegabriel.com/forum/mycodo/)

If you have a Github account, to make it easier to know who's who between the Github Issue Tracker and the forum, on the forum please add your github profile link under My Profile -> Account -> Social Networks -> Github. When you view your profile, it should show your profile link (example: https://kylegabriel.com/forum/profile/kylegabriel).

**Comment by SAM26K** [comment]
Great idea with this forum thread.
Was wondering if it's possible to send emails via the mycodo daemon with a linux command and if so how?
i.e.  Would like to use it in an existing mycodo output linux command.
Thanks
