### ISSUE TITLE
LCD 20x4 option missing - 16x4 typo?

### ISSUE THREAD

**Issue by mrplow** [kizniche/Mycodo#627]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.2.2
 
#### Problem Description
Please list:

  - the 20x4 LCD option seems to be missing, the manual still references 20x4 but at some point it was changed to 16x4, perhaps during the last refactor there was a typo.

**Comment by kizniche** [comment]
I think you're correct. I'll work on a fix for this.
