### ISSUE TITLE
Add feature: Add the Atlas inputs of ORP and DO for Atlas sensor chip

### ISSUE THREAD

**Issue by alonrab** [kizniche/Mycodo#643]
Hi Kyle et. al.
Can you please help me with adding the atlas sensor inputs for O.R.P and D.O.?
https://www.atlas-scientific.com/product_pages/circuits/ezo_orp.html
https://www.atlas-scientific.com/product_pages/circuits/ezo_do.html
Best,

**Comment by kizniche** [comment]
Sure. What is your interface, UART or I2C?

**Comment by alonrab** [comment]
I'm using i2c,
Thanks!

**Comment by kizniche** [comment]
Added both sensors with FTDI, UART, and I2C support for each. I'm going to try to get this out in a release tonight.

**Comment by kizniche** [comment]
I'll keep this issue open until you get a chance to test both Input modules.

**Comment by alonrab** [comment]
Hi, tested ORP today, works great! Thanks, i am waiting to get the DO probe but its very similar code so i assume it works as well
Many thanks for your help

**Comment by kizniche** [comment]
Did you ever get the DO probe?

**Comment by alonrab** [comment]
No - was not able to afford it yet. Will update when I get it if there are issues,Many thanks!
