### ISSUE TITLE
Backup transfer to another SD Card

### ISSUE THREAD

**Issue by RynFlutsch** [kizniche/Mycodo#644]
How it is possible to transfer an backup from Card A to another SD Card B and restore it there?

I tried to copy the Backup but 1 file cant be copied.
![IMG_20190330_182431](https://user-images.githubusercontent.com/29811876/55283053-c7bcb400-5351-11e9-8890-8efaaff400b2.jpg)

**Comment by RynFlutsch** [comment]
Someone know why the thumbnail is twistet, but the origina pic.l is correct?

**Comment by kizniche** [comment]
Yes, but you will need root privileges. Using the command line, you would use ```sudo cp - R source-directory destination```

**Comment by RynFlutsch** [comment]
Ok thanks, i tried with Thunar root (+ i changed the permissions to write and read, to everyone), but i will try again via console.

**Comment by kizniche** [comment]
You can also change the permissions of the whole backup directory with:

```sudo chown -R pi.pi /var/Mycodo-Backups```

**Comment by RynFlutsch** [comment]
Console roxx ;-D
