### ISSUE TITLE
Internet not detect

### ISSUE THREAD

**Issue by pigelb** [kizniche/Mycodo#652]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.4.2
 
#### Problem Description
Please list: Internet is not detected even if internet is accessible.

![image](https://user-images.githubusercontent.com/6541280/56763621-dc357600-6770-11e9-9ab6-b10aeee222f2.png)

Eth0 connection is straight to a laptop to interface with Mycodo. 
Wlan0 connection is the one with access to the internet. 

### Errors

![image](https://user-images.githubusercontent.com/6541280/56763484-8f519f80-6770-11e9-885c-48fba1b9b0b4.png)
![image](https://user-images.githubusercontent.com/6541280/56763542-b0b28b80-6770-11e9-9160-8d8c64527a5d.png)

### Additional Notes
Routing table has Wlan0 as the main gateway.
![image](https://user-images.githubusercontent.com/6541280/56763805-3cc4b300-6771-11e9-9bc3-489acb7de630.png)

**Comment by kizniche** [comment]
Here is the code to check for internet:

https://github.com/kizniche/Mycodo/blob/b94fe06184e96320a8ad8a165009e666d319324a/mycodo/utils/system_pi.py#L202-L217

When logged into the terminal of your Pi, what is the output of the following command?

```
sudo apt install -y nmap
nmap -p 52 8.8.8.8
```

**Comment by kizniche** [comment]
Additionally, you can run the following command from the terminal to see if a traceback is yielded from the error:

```bash
cd ~/Mycodo
~/Mycodo/env/bin/python -c 'from mycodo.utils.system_pi import internet; print(internet())'
```

**Comment by kizniche** [comment]
Though, you may have to edit system_pi.py and change "error" to "exception" on the following line, save, then rerun that command, above.

https://github.com/kizniche/Mycodo/blob/b94fe06184e96320a8ad8a165009e666d319324a/mycodo/utils/system_pi.py#L215
