### ISSUE TITLE
MQTT Input Development

### ISSUE THREAD

**Issue by jlb-qi** [kizniche/Mycodo#664]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.5.7
 
#### Problem Description

I'm trying to create a new input for sensor readings coming over MQTT. I have the readings appearing in the Pi terminal from a remote device and now need to get them into Mycodo. Having previously attempted the Linux command option, I realised I would have to dive a bit deeper and fully add the input. While long term it would be good to be able to import a JSON object full of values, at the moment I'm just trying to get the single value from a mosquitto subscription.

This requires the paho-mqtt package which I have added as a dependency, while this has already been installed, Mycodo seems to have an issue with detecting it.
 
### Errors
The dependency logs show;

[2019-06-13 22:03:09] Dependency installation beginning. Installing: paho-mqtt

[2019-06-13 22:03:09] 
[2019-06-13 22:03:09] #### Installing/updating paho-mqtt (pip-pypi)
[2019-06-13 22:03:13] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2019-06-13 22:03:14] Requirement already up-to-date: paho-mqtt in ./env/lib/python3.5/site-packages (1.4.0)

[2019-06-13 22:03:17] End install of paho-mqtt

[2019-06-13 22:03:17] 
[2019-06-13 22:03:17] #### Setting permissions

[2019-06-13 22:03:18] #### All Dependencies have been installed.

And yet afterwards I still get returned to the dependencies required screen showing;

Error: Add Input: The MQTT device you're trying to add has unmet dependencies: paho-mqtt

The unmet dependencies are the following python modules:
-  paho-mqtt

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. Add the paho-mqtt module to a new input
2. Attempt to add the new input to your setup in Mycodo
 
###  Additional Notes

I have tried deleting the .dependency file already but to no avail

**Comment by kizniche** [comment]
Can you attach the input so I can review the code?

**Comment by jlb-qi** [comment]
At the moment it's just a copy of the linux input but with the dependency added as well as some descriptive changes to the Input Information

**Comment by jlb-qi** [comment]
"""
# coding=utf-8
from mycodo.inputs.base_input import AbstractInput
from mycodo.utils.system_pi import cmd_output
from mycodo.utils.system_pi import str_is_float

# Measurements
measurements_dict = {
    0: {
        'measurement': 'humidity',
        'unit': 'percent'
    }
}

# Input information
INPUT_INFORMATION = {
    'input_name_unique': 'MQTT',
    'input_manufacturer': 'ABC',
    'input_name': 'MQTT',
    'measurements_name': 'Input from MQTT subscription',
    'measurements_dict': measurements_dict,

    'options_enabled': [
        'measurements_select',
        'period',
        'cmd_command',
        'log_level_debug'
    ],
    'options_disabled': ['interface'],

    'dependencies_module': [
        ('pip-pypi', 'paho-mqtt', 'paho-mqtt'),
        ('pip-git', 'paho-mqtt','git://github.com/eclipse/paho.mqtt.python')
    ],
    'enable_channel_unit_select': True,
    'interfaces': ['pi'],
    'cmd_command': 'shuf -i 50-70 -n 1',
}


class InputModule(AbstractInput):
    """ A sensor support class that returns a value from a command """

    def __init__(self, input_dev, testing=False):
        super(InputModule, self).__init__(input_dev, testing=testing, name=__name__)

        if not testing:
            self.command = input_dev.cmd_command

    def get_measurement(self):
        """ Determine if the return value of the command is a number """
        self.return_dict = measurements_dict.copy()

        out, _, _ = cmd_output(self.command)

        if str_is_float(out):
            list_measurements = [float(out)]
        else:
            self.logger.error(
                "The command returned a non-numerical value. "
                "Ensure only one numerical value is returned "
                "by the command.")
            return

        for channel in self.device_measurements:
            if self.is_enabled(channel):
                self.return_dict[channel]['unit'] = self.device_measurements[channel].unit
                self.return_dict[channel]['measurement'] = self.device_measurements[channel].measurement
                self.return_dict[channel]['value'] = list_measurements[channel]

        return self.return_dict

**Comment by jlb-qi** [comment]
I tried both the pypi and git options but neither seem to be detected

**Comment by kizniche** [comment]
Your dependency line is the issue:

```
('pip-pypi', 'paho-mqtt', 'paho-mqtt')
```

It should read:

```
('pip-pypi', 'paho', 'paho-mqtt')
```

```paho``` is the actual module that's installed, while ```paho-mqtt``` is the name in pypi that is used to install it.

That is, you would typically install with:

```
pip install paho-mqtt
```

and use the module with:

```
import paho
```

**Comment by kizniche** [comment]
I'd like to work with you developing a built-in MQTT Input that has a variable number of keys/values that can be returned and stored in Mycodo. Let me know how your code development goes now that you can inport and add the module and I'll help with the expanding the functionality, much like I did with the TTN Input (search Inputs for "TTN Integration" to see how I implemented an Input that can return a variable number of measurements).

**Comment by jlb-qi** [comment]
Much appreciated Kyle! I will certainly let you know how the code develops and once it's in an MVP state I'll create a pull request for review. Thanks again and have a great weekend

**Comment by jlb-qi** [comment]
@kizniche managed to get some time to work on this yesterday and  so far I've managed to get the input set up and values from the sensor (over MQTT) to show in the daemon logs. I can't quite figure out how to get the measurements into the database though and I think it might be something to do with the daemon controller not setting the ID properly. Here are the messages when going through the steps of creation, activation, deactivation and deletion.

The messages; 

**When creating;** 
    Success: MQTT Input with ID 3 (32c79c3d-ea3d-4049-b8c2-6023b5229402) successfully added
    Success: Add Input

**When activating;**
    Success: Input Activate (SQL)
    Success: Activate Input
    Error: Error: result expired

**When deactivating;**
    Success: Input Deactivate (SQL)
    Error: Input controller with ID 32c79c3d-ea3d-4049-b8c2-6023b5229402 not found

**When Deleting**
    Success: Input Deactivate (SQL)
    Success: Delete device_measurements with ID: 0372f9f3-4072-44a7-9850-9871de546d14
    Success: Delete input with ID: 32c79c3d-ea3d-4049-b8c2-6023b5229402
    Success: Delete Input

    Error: Input controller with ID 32c79c3d-ea3d-4049-b8c2-6023b5229402 not found

**Comment by jlb-qi** [comment]
`# coding=utf-8
import datetime
import time

import requests
from flask_babel import lazy_gettext

import paho.mqtt.client as mqtt

from mycodo.config import SQL_DATABASE_MYCODO
from mycodo.databases.models import Conversion
from mycodo.databases.models import DeviceMeasurements
from mycodo.databases.models import Input
from mycodo.databases.utils import session_scope
from mycodo.inputs.base_input import AbstractInput
from mycodo.utils.database import db_retrieve_table_daemon
from mycodo.utils.influx import add_measurements_influxdb
from mycodo.utils.influx import parse_measurement

MYCODO_DB_PATH = 'sqlite:///' + SQL_DATABASE_MYCODO


# Measurements
measurements_dict = {
    0: {
        'measurement': 'humidity',
        'unit': 'percent'
    }
}

# Input information
INPUT_INFORMATION = {
    'input_name_unique': 'MQTT',
    'input_manufacturer': 'ABC_test',
    'input_name': 'MQTT Protocol',
    'measurements_name': 'Variable measurements',
    'measurements_dict': measurements_dict,
    'measurements_use_same_timestamp': False,

    'options_enabled': [
        'custom_options',
        'measurements_select',
        'period',
        'log_level_debug'
    ],
    'options_disabled': ['interface'],

    'interfaces': ['Mycodo'],

    'dependencies_module': [
        ('pip-pypi', 'paho', 'paho-mqtt')],

    'custom_options': [
        {
            'id': 'mqtt_hostname',
            'type': 'text',
            'default_value': 'raspberrypi',
            'required': True,
            'name': lazy_gettext('Application ID'),
            'phrase': lazy_gettext('The hostname of the MQTT server')
        },
        {
            'id': 'mqtt_channel',
            'type': 'text',
            'default_value': '/rsu/pi',
            'required': True,
            'name': lazy_gettext('MQTT channel'),
            'phrase': lazy_gettext('The MQTT channel to subscribe to')
        },
        {
            'id': 'mqtt_keepalive',
            'type': 'int',
            'default_value': 0,
            'required': False,
            'name': lazy_gettext('Keep Alive'),
            'phrase': lazy_gettext('Max time between recieved signals')
        },
        {
            'id': 'mqtt_clientid',
            'type': 'int',
            'default_value': 'mycodo_mqtt_client',
            'required': False,
            'name': lazy_gettext('MQTT Client ID'),
            'phrase': lazy_gettext('Unique client ID for connection to MQTT server')
        }

    ]
}


class InputModule(AbstractInput):
    """ A sensor support class that retrieves stored data from The Things Network """

    def __init__(self, input_dev, testing=False):
        super(InputModule, self).__init__(input_dev, testing=testing, name=__name__)

        if not testing:
            self.unique_id = input_dev.unique_id
            self.interface = input_dev.interface
            self.period = input_dev.period
            self.first_run = True
            self.latest_datetime = input_dev.datetime

            if input_dev.custom_options:
                for each_option in input_dev.custom_options.split(';'):
                    option = each_option.split(',')[0]
                    value = each_option.split(',')[1]
                    if option == 'mqtt_hostname':
                        self.host = value
                    elif option == 'mqtt_channel':
                        self.mqtt_channel = value
                    elif option == 'mqtt_keepalive':
                        self.mqtt_keepalive = value
                    elif option == 'mqtt_clientid':
                        self.mqtt_clientid = value

        ### Create a client instance
        client = mqtt.Client(self.mqtt_clientid)

        ### Connect the callback functions
        try:
            self.logger.info("Connecting mqtt callback functions...")
            client.on_connect = self.on_connect # attach function to callback
            client.on_message = self.on_message  # attach function to callback
            client.on_subscribe = self.on_subscribe  # attach function to callback
            client.on_disconnect = self.on_disconnect
            self.logger.info("mqtt callback functions connected")
        except:
            self.logger.error("Unable to connect mqtt callback functions")

        ### Set up the connection to the MQTT Server
        try:
            client.connect(self.host)
            self.logger.info("Connected to: "+self.host+" as: "+self.mqtt_clientid)
        except:
            self.logger.error("Could not connect to mqtt host: "+self.host)
        
        ### Set up the subscription to the proper MQTT channel to listen to
        try:
            client.subscribe(self.mqtt_channel)
            self.logger.info("Connected to: "+self.mqtt_channel)
        except:
            self.logger.error("Could not connect to MQTT channel"+self.mqtt_channel)

        client.loop_forever() #start the loop

    def on_connect(self, client, obj, flags, rc):
        print("rc: "+str(rc))
        '''try:
            client.subscribe(self.mqtt_channel)
            self.logger.info("(F) Connected to: "+self.mqtt_channel)
        except:
            self.logger.error("Could not connect to MQTT channel"+self.mqtt_channel)
        '''

    def on_subscribe(self, client, obj, mid, granted_qos):
        #print("Subscribing to topic: "+self.mqtt_channel+str(mid)+" "+str(granted_qos))
        print("Subscribing to topic: "+self.mqtt_channel)

    def on_message(self, client, userdata, message):
        #self.logger.info(float(message.payload.decode("utf-8")))
        if float(message.payload.decode("utf-8")) == 12345.0:
            disconnect()  
        self.get_measurement()
        #print("message topic=",message.topic)
        #print("message qos=",message.qos)
        #print("message retain flag=",message.retain)

    def on_disconnect(self, client, userdata,rc=0):
        ## TODO: trigger then when controller is deactivated controller_deactivate() in mycodo_daemon.oy
        self.logging.info("DisConnected result code "+str(rc))
        client.loop_stop()

    def get_measurement(self):
        """ Measures temperature and humidity """
        # Resetting these values ensures old measurements aren't mistaken for new measurements
        self.logger.info("Get measurements started...")
        self.return_dict = measurements_dict.copy()

        # Actual input measurement code
        try:
            humidity = self.random.randint(0, 100)
            temperature = self.random.randint(0, 50)

            self.logger.info(
                "This INFO message will always be displayed. "
                "Acquiring measurements...")

            if self.is_enabled(0):
                self.value_set(0, temperature)

            if self.is_enabled(1):
                self.value_set(1, humidity)

            if (self.is_enabled(2) and
                    self.is_enabled(0) and
                    self.is_enabled(1)):
                dewpoint = calculate_dewpoint(
                    self.value_get(0), self.value_get(1))
                self.value_set(2, dewpoint)

            self.logger.debug(
                "This DEBUG message will only be displayed if the Debug "
                "option is enabled. {}".format(self.return_dict))

            return self.return_dict
        except Exception as msg:
            self.logger.error("Exception: {}".format(msg))

    '''
    def get_measurement(self):
        self.return_dict = measurements_dict.copy()
        self.temp_humidity = None
        
        self.logger.info("Get measurements")
        #for channel in self.device_measurements:
        #    if self.is_enabled(channel):
        #        self.return_dict[channel]['unit'] = self.device_measurements[channel].unit
        #        self.return_dict[channel]['measurement'] = self.device_measurements[channel].measurement
        #        self.return_dict[channel]['value'] = list_measurements[channel]
        #print("Publishing message to topic","/rsu/pi")
        #client.publish("/rsu/pi","from chattop")
        """ Determine if the return value of the command is a number """

        out = client.on_message
        self.logger.info(out)

        if str_is_float(out):
            list_measurements = [float(out)]
            self.logger.info(list_measurements)
        else:
            self.logger.error(
                "The command returned a non-numerical value. "
                "Ensure only one numerical value is returned "
                "by the command.")
            return

        for channel in self.device_measurements:
            if self.is_enabled(channel):
                self.return_dict[channel]['unit'] = self.device_measurements[channel].unit
                self.return_dict[channel]['measurement'] = self.device_measurements[channel].measurement
                self.return_dict[channel]['value'] = list_measurements[channel]

        return self.return_dict
        '''
`

**Comment by kizniche** [comment]
Just a quick update to say I got the MQTT Input functioning. Here's a log output of the message ```1234``` being received:

```
2019-06-20 20:13:40,733 - INFO - mycodo.controller_input_2a2ce3f8 - Activated in 323.0 ms
2019-06-20 20:13:40,733 - INFO - mycodo.inputs.mqtt_2a2ce3f8 - Connecting MQTT callback functions
2019-06-20 20:13:40,734 - INFO - mycodo.inputs.mqtt_2a2ce3f8 - MQTT callback functions connected
2019-06-20 20:13:40,741 - INFO - mycodo.inputs.mqtt_2a2ce3f8 - Connected to: localhost as mycodo_mqtt_client
2019-06-20 20:13:40,742 - INFO - mycodo.inputs.mqtt_2a2ce3f8 - Subscribed to 'topic/test'
2019-06-20 20:13:40,743 - INFO - mycodo.inputs.mqtt_2a2ce3f8 - Connected to 'topic/test', rc: 0
2019-06-20 20:13:40,744 - INFO - mycodo.inputs.mqtt_2a2ce3f8 - Subscribing to topic: topic/test, 1, (0,)
2019-06-20 20:13:56,011 - INFO - mycodo.inputs.mqtt_2a2ce3f8 - TEST00
2019-06-20 20:13:56,012 - INFO - mycodo.inputs.mqtt_2a2ce3f8 - Message: 1234
```

I installed the mosquitto MQTT broker on the Pi Mycodo is installed on, with:

```
sudo apt install mosquitto
```

Then set the Input Hostname to ```localhost```, Client ID to ```mycodo_mqtt_client_01```, Channel ID to ```topic/test```, then activated the Input. I then saved the code below on the same Pi to ```~/Mycodo/test_mqtt_client.py```:

```python
import paho.mqtt.client as mqtt
client = mqtt.Client("mycodo_mqtt_client_02")
client.connect("localhost", port=1883)
client.publish("topic/test", '1234')
client.disconnect()
```

Then executed it using the Mycodo virtualenv:

```
~/Mycodo/env/bin/python ~/Mycodo/test_mqtt_client.py
```

The code is not currently committed to github so you cannot test, however I will try to make a commit tonight and give instructions how to start testing the latest code.

**Comment by kizniche** [comment]
I just pushed all the MQTT code. You can get it by [Upgrading to the master branch](https://github.com/kizniche/Mycodo/wiki/Updating-to-Github-Master-Branch).

Once you've done that, add the MQTT Input, set your ```Hostname``` and ```Port``` for the MQTT broker, and your desired ```MQTT Client ID```. Set the number of channels with the option ```Number of Measurements```. After saving you will see in the expanded Input, under Measurement Settings, that number of measurements appear. Change the ```Name``` of each to the channel name you want to subscribe to. Make sure you set a ```Measurement Unit``` for each. Activate the Input and whenever a float value with any of those channels are published, it will be written to the Mycodo database and will appear on the Dashboard and Info pages and be able to be used everywhere else throughout Mycodo.

Let me know if you experience any issues. I'll wait to make a release until you can test and respond with whether it's working or not.

Enjoy!

**Comment by jlb-qi** [comment]
got an error when navigating to the Setup > Data screen

**Comment by jlb-qi** [comment]
`Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_page.py", line 1855, in page_data
    devices_1wire_w1thermsensor=devices_1wire_w1thermsensor)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/data.html", line 3, in top-level template code
    {% set help_page = ["data", dict_translation['data']['title']] %}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/layout.html", line 262, in top-level template code
    {%- block body %}{% endblock -%}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/data.html", line 48, in block "body"
    {% include 'pages/data_options/input.html' %}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/data_options/input.html", line 141, in top-level template code
    {% include 'pages/data_options/input_options/TEMPLATE_OPTIONS_Measurements_Convert.html' %}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/data_options/input_options/TEMPLATE_OPTIONS_Measurements_Convert.html", line 92, in top-level template code
    {% if 'measurements_select_measurement_unit' in dict_inputs[each_input.device]['options_enabled'] %}
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'MQTT'`

**Comment by jlb-qi** [comment]
I will have a look to debug it myself if I can

**Comment by jlb-qi** [comment]
Hey Kyle, I managed to clear a few hours to test the code and managed to update it to be able to parse incoming JSON object with multiple measurements. I tried to create a seperate mqtt branch in the repo but to no avail. I updated the gist tho https://gist.github.com/jlb-qi/332553e6cfb2793e2b15534f129ddc30 so have a wee look and let me know what you think

**Comment by jlb-qi** [comment]
it still needs a bit of work but this should definitely get it up and running

**Comment by jlb-qi** [comment]
very satisfying 👍

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/14451186/60017523-324b6a80-9689-11e9-9acf-5ee6a6eb1309.png">

**Comment by kizniche** [comment]
I merged your edits with the module currently in the master branch. I have a few questions about what you did so I can remove extraneous code and make this more simple for anyone trying to understand what's going on. I added "TODO" notes for what I think can be removed.

1. Can you provide steps for how you set up your MQTT broker and published measurements (code/commands)?

2. Why is there an extra subscription in addition to the measurement channels? I removed this Input Option because the measurements that are added are what are subscribed to. Isn't only the channels specified in the measurements sufficient?

```python
        {
            'id': 'mqtt_channel',
            'type': 'text',
            'default_value': '/rsu/pi',
            'required': False,
            'name': lazy_gettext('Subscription Channel'),
            'phrase': lazy_gettext('The name of the thread with which to subscribe to')
        }

...

    def subscribe(self):
        """ Set up the subscriptions to the proper MQTT channels to listen to """
        try:
            for channel in self.channels_measurement:
                self.client.subscribe(self.mqtt_channel)
                #self.logger.debug("Subscribed to channel '{}'".format(self.mqtt_channel))
                self.client.subscribe(self.channels_measurement[channel].name)
                self.logger.debug("Subscribed to  measurement'{}'".format(self.channels_measurement[channel].name))
        except:
            self.logger.error("Could not subscribe to MQTT topic '{}'".format(
                self.mqtt_channel))
```

3. Isn't the payload channel irrelevant because the Mycodo channel is what's stored in the database and displayed to the user?

```python
                    payload_channel = payload_measurements.index(
                        self.channels_measurement[channel].name)
                    self.logger.debug(
                        "measurement: '{}' is mycodo channel: '{}' and "
                        "payload channel: '{}'".format(
                            self.channels_measurement[channel].name,
                            channel,
                            payload_channel))
```

**Comment by jlb-qi** [comment]
In answer to your questions;

1. Certainly! I'll work on the documentation and send it over. I assume you prefer in a Markdown format? Otherwise just let me know.

2.  You're right, there's an extra line here I forgot to remove. Just need to take out the line.

```python
self.client.subscribe(self.channels_measurement[channel].name)
```

3. The payload channel is required for matching the measurement value in the incoming JSON with the right channel in the database. It'll probably make more sense when I get the documentation together. 

In addition, the JSON format that is required at the moment is a little unrefined and I'd like to extend it in future. This was enough to get it working tho. Again, will make more sense when I get the documentation together.

**Comment by kizniche** [comment]
> You're right, there's an extra line here I forgot to remove. Just need to take out the line.

You have it backwards. This needs to stay:

```python
self.client.subscribe(self.channels_measurement[channel].name)
```

This needs to be removed:

```python
        {
            'id': 'mqtt_channel',
            'type': 'text',
            'default_value': '/rsu/pi',
            'required': False,
            'name': lazy_gettext('Subscription Channel'),
            'phrase': lazy_gettext('The name of the thread with which to subscribe to')
        }

...and...

self.client.subscribe(self.mqtt_channel)
```

```self.mqtt_channel``` is a single text string defined by the user. This means only one channel can be subscribed to with this method. However, ```self.channels_measurement``` holds the names of every measurement the user specifies (one or more measurements), which allows for several channels to be subscribed to. The use of ```self.mqtt_channel``` in addition to the variable number of measurements used as channels is redundant and will only confuse the user.

> The payload channel is required for matching the measurement value in the incoming JSON with the right channel in the database. 

I see this now, and would like to ask if this is a standard practice for MQTT transmissions. Using both a Mycodo channel and payload channel from a JSON string seems overly complex and confusing. Why not just subscribe to a channel that returns 1 value per channel?

**Comment by kizniche** [comment]
I suppose what I'm asking is: What is the benefit of subscribing to one channel with a JSON payload rather than separate channels with a single value payload?

**Comment by jlb-qi** [comment]
A very fari point. Tbh I think I had anchored my idea in the notion that a remote sensor unit (comprised of multiple sensors) would provide a single subscription. I did a bit of reading on MQTT and ESP8266 best practice and it think you're right about the seperate channel/topic per measurement. I tested your original code with a couple of sensor unit with a variety of sensors and they all work so I would say good to go with the original code you sent through.

**Comment by jlb-qi** [comment]
The only thing I found during testing was that if you try to add a measurement but don't specify the units, you get an error message that **Error: Modify Measurement: list index out of range** rather than something like **Please select unit of measurement**. A minor detail but worth mentioning

**Comment by kizniche** [comment]
How has the new Input been working for you?

**Comment by jlb-qi** [comment]
Hi Kyle, apologies for the belated reponse, back at work now and time has been greatly limited. Yes the input has been working a treat! I have a bunch of ESP8266s with various sensor configurations in a variety of environments now all feeding into Mycodo. Real smart system : )

**Comment by kizniche** [comment]
Glad to hear. I'll close this issue now that everything is working.
