### ISSUE TITLE
7.6.3 Test Email Not Sending

### ISSUE THREAD

**Issue by wllyng** [kizniche/Mycodo#678]
Mycodo Issue Report: 7.6.3

Problem Description:
While using the test email alert system I noticed that none of the emails showed up in my inbox despite saying that the email was sent successfully. I have filled in all of the SMTP account information and have enabled the POP and IMAP stuff on the gmail account.

**Comment by kizniche** [comment]
For Gmail, you must also enable "less secure apps", https://support.google.com/accounts/answer/6010255

**Comment by wllyng** [comment]
Thanks it works now

**Comment by robocode-LAB** [comment]
I know this is an old thread, but it looks like Gmail will not longer allow less secure apps since 2022. Is there a workaround for getting email notifications?

![image](https://github.com/kizniche/Mycodo/assets/82898491/8886a3b0-b13f-4def-8725-0ac761f82698)

**Comment by kizniche** [comment]
Gmail isn't the only email host.
