### ISSUE TITLE
"Error 502: Bad Gateway Error" on Raspberry Pi 3 A+

### ISSUE THREAD

**Issue by smatthews95** [kizniche/Mycodo#681]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.6.3
 
#### Problem Description
Please list:

I just downloaded and installed what I understand to be the latest build. However, when I open Chromium and attempt to navigate to "https://localhost" I get an "Error 502: Bad Gateway Error" as well as an error message telling me it's "...probably not your fault", and telling me to try refreshing, and rebooting. I have done both, as well as fully updated my Pi and I am still getting the issue.
 
### Errors
  Error 502: Bad Gateway Error
 Something bad happened but it's probably not your fault. Try 
refreshing the page to see if it will load. If that doesn't work, try 
rebooting your system, then try refreshing it again. If that still 
doesn't work, submit a new issue on GitHub with any useful information that can help determine the cause of this issue.

### Steps to Reproduce the issue:
For me it was:
1) Install via terminal
2) Try to navigate to localhost
3) Get "Bad Gateway Error"
4) Check for updates
5) Install updates
6) Reboot
7) Try to navigate to localhost
8) Get same error.

### Additional Notes

**Comment by smatthews95** [comment]
Kyle,

Thank you for getting back to me so fast. I tried running flask in terminal
as you suggested and it's giving me a command not found error in regards to
gunicorn. I've attached an image of the terminal.

Thank you.

**Comment by smatthews95** [comment]
I've already done a complete NOOBS reinstall of Raspbian and reinstall of Mycodo. The same issue persisted after the second install as well. I'm skeptical that the same exact issue would follow me through a reinstall if it was due to a connection issue.

With that said, I'm running another install using your terminal command right now and will follow up with the result.

**Comment by kizniche** [comment]
You can see the log for yourself that several packages couldn't be downloaded due to a connection issue.
A connection issue would in fact cause the same symptoms across several reflashes of the OS, if the connection issue wasn't related to the OS. This indicates it is either an issue from your Pi to your ISP, your ISP, or the pypi system. The likely culprit is your connection between your Pi and your ISP.

**Comment by smatthews95** [comment]
Sorry for the delay in getting back to you. You were right, it was the internet connection. I took it to work with me and it installed without issue.
