### ISSUE TITLE
Atlas PH Calibrate does not work

### ISSUE THREAD

**Issue by grux77** [kizniche/Mycodo#686]
Hello!
I'm trying to run Atlas PH with Mycodo 7.7.1 on the Pi 3 B with Buster, but can not calibrate the probe. 
Right in the first step I get "Error: Calibration: temperature (25.00 C): Default message"
Seems to be a problem with the code. See Demon Log:

2019-09-12 16:22:12,447 - DEBUG - mycodo.inputs.atlas_ph_ac3a6aa3 - pH sensor set to calibrate temperature
2019-09-12 16:22:12,501 - ERROR - mycodo.inputs.atlas_ph_ac3a6aa3 - InputModule raised an exception when taking a reading: 'str' object has no attribute 'unit'
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/inputs/base_input.py", line 122, in read
    self._measurements = self.get_measurement()
  File "/home/pi/Mycodo/mycodo/inputs/atlas_ph.py", line 161, in get_measurement
    measurement.unit,
AttributeError: 'str' object has no attribute 'unit'

2nd problem: 
When I activate 'Calibration Measurement' in the Setup/Data/Input I get 'No Data' in Data/Live. Is this wanted?

Sorry for english is not mine but from Google-translator

**Comment by grux77** [comment]
I sent you a message on https://kylegabriel.com/contact/ with remote data

**Comment by kizniche** [comment]
I logged in and there are measurements, so it looks like the input is working. I'll check out the calibration section.

**Comment by kizniche** [comment]
I was able to fix all the issues with the calibration system, and it's now working on your Pi. Go ahead and clear the calibration then go through all the steps with the 4, 7, and 10 pH solutions and see if it's then accurate by placing it back into each solution. I'll push the changes I made soon. Keep in mind all the edits are already on your Pi, so you don't need to do any upgrading at the moment.

**Comment by kizniche** [comment]
I have the Input currently deactivated. I can't guarantee the calibration procedure will work properly if it's done while the Input is activated. Therefore, deactivate it while calibrating, then reactivate it afterward.

**Comment by grux77** [comment]
Yes, if I disable it then the calibration works without errors.
Would it be possible to skip Ph10 point during calibration? I have only Ph4
and Ph7 here. For freshwater aquarium also a 2-point calibration is
sufficient.
I'll leave the board for a week (or even longer) for them, if they want to
try something further.
I think your software is awesome and I like to make my Atlas Ph available

Am Sa., 14. Sept. 2019 um 02:22 Uhr schrieb Kyle Gabriel <
notifications@github.com>:

**Comment by kizniche** [comment]
You're right, there should be the option of what type of calibration you want to perform.

**Comment by kizniche** [comment]
I just added the ability to perform a 1, 2, or 3 point pH calibration (with any combination of the 4.0, 7.0 or 10.0 pH solutions one may have). I successfully tested on your system to work. You will want to clear the calibration then go through the calibration steps to get your sensor calibrated. Let me know if you come across any issues.

**Comment by grux77** [comment]
This looks very good! I will test it out soon. Thanks for the very fast work!

**Comment by grux77** [comment]
Yes, the calibration works wonderfully. A trifle might change in the next release.
I would increase the time for each calibration solution to at least 60 sec. So that the probe can adjust.
Now it's only 6 sec. you can of course wait in advance if you know it. Maybe a note text is enough.
![ph7_time_red](https://user-images.githubusercontent.com/55245846/64921323-4f906080-d7c2-11e9-846b-1f31c6b36d9c.jpg)


Overall, it is well done. Respect!

**Comment by kizniche** [comment]
It's supposed to be 120 seconds. I never changed it back from 5 while I was testing. I'll change it for the next release. Thanks for testing.
