### ISSUE TITLE
"Error: Activate Conditional: Measurement must be set"

### ISSUE THREAD

**Issue by buzzfuzz2k** [kizniche/Mycodo#690]
## Mycodo Issue Report:
  - Specific Mycodo Version:7.7.3 & 7.7.4
 
#### Problem Description
Since last 2 updates (7.7.3 & 7.7.4) my functions doesn't work anymore?
When I save the code, i get the green validation but when i want to activate a function i get this error code:
"Error: Activate Conditional: Measurement must be set"
https://www.cjoint.com/doc/19_09/IIsqhLUJzMO_Capture2.PNG

I also tried to recreate my function with new measure ID, but same....
here is a part of the code (i removed the second part, not usefull now)
https://www.cjoint.com/doc/19_09/IIsqhuXwXdO_Capture.PNG

my last lines of logging
`2019-09-18 17:49:41,775 - INFO - mycodo.daemon - Mycodo daemon started in 5.417 seconds
2019-09-18 17:49:44,527 - INFO - mycodo.daemon - 40.10 MB RAM in use
2019-09-18 17:51:31,229 - INFO - mycodo.controllers.controller_conditional_8a38bf0c - Deactivated in 205.2 ms
2019-09-18 17:51:36,821 - INFO - mycodo.controllers.controller_conditional_8a38bf0c - Activated in 263.5 ms
2019-09-18 17:53:56,325 - INFO - mycodo.controllers.controller_conditional_8a38bf0c - Deactivated in 8.0 ms`

thanks

**Comment by kizniche** [comment]
> I also tried to recreate my function

Does this mean you added a completely new function, after upgrading to 7.7.4, with all the settings default, then set it up, and it still displayed this behavior?

I haven't been able to replicate this issue on 7.7.4, so that's strange.

**Comment by buzzfuzz2k** [comment]
I did on 7.7.3

I'll try now

**Comment by buzzfuzz2k** [comment]
I did on 7.7.4 and it seems to work

The other difference is that i have completely removed all old ID and conditionnal...

**Comment by kizniche** [comment]
There are some configuration changes that rarely result in strange behavior if things are deleted that other things depend on. It's difficult to account for all case-use scenarios. Glad you resolved the issue.

**Comment by buzzfuzz2k** [comment]
i may have find some new informations...
the problem is not with the version !

I did this function and it works:
`temperature_int = self.measure("{1b264478}")
if temperature_int is not None and temperature_int > 13.6:
    self.run_action("{b7eb48b4}")
if temperature_int is not None and temperature_int < 12.6:
    self.run_action("{b1130d8f}")`

I then add an "output state condition" to know if an output is already on or off. I use this code:
`temperature_int = self.measure('{1b264478}')
temps_compresseur = self.measure('{f75a5c35}')

if temperature_int is not None:
    if temperature_int > 13.6 and temps_compresseur == 'off':
        self.run_action("{b7eb48b4}") # allumer le compresseur
    elif temperature_int < 12.6 and temps_compresseur == 'on':
        self.run_action("{b1130d8f}") # eteindre le compresseur`

The "save" was ok (green), but when i want to activate, i get the message again!

I copy/paste the old code, same error but when i removed the conditional output state line, it worked!

as i said in this post 
https://kylegabriel.com/forum/general-discussion/conditional-wit-output-duration/

i would like to get this code to work
`temperature_int = self.measure('{1b264478}')
temps_compresseur = self.measure('{f75a5c35}')

if temperature_int is not None:
    if temperature_int > 13.6 and temps_compresseur == 'off':
        self.run_action("{b7eb48b4}") # allumer le compresseur
    elif temperature_int < 12.6 and temps_compresseur == 'on':
        self.run_action("{b1130d8f}") # eteindre le compresseur

if temperature_int is None or (temperature_int is not None and temperature_int > 16):
    output_on_duration = self.control.output_sec_currently_on('1b6ada50-1e69-403a-9fa6-ec748b16dc23')
    if output_on_duration > 600:
        self.run_action("{7d4fecd9}") # Turn output off
        self.run_action("{b9d216aa}") # email`

but the first part is not working

thank you for the help

**Comment by kizniche** [comment]
Okah. That info should help me track down the issue.

**Comment by kizniche** [comment]
Found the issues. Pushing a fix and releasing 7.7.5 shortly.

**Comment by buzzfuzz2k** [comment]
great!

thanks
