### ISSUE TITLE
Incorrect output duration on dashboard graph

### ISSUE THREAD

**Issue by chitters2004** [kizniche/Mycodo#697]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.7.6-8
 
![Graph](https://user-images.githubusercontent.com/55252868/65463410-95e36080-de4f-11e9-8227-86407c2557cf.png)

**Comment by kizniche** [comment]
Can you provide steps to replicate the issue?

**Comment by chitters2004** [comment]
I realise it's been this way since you fixed the outputs not appearing the other day.

Literally just set up a graph with the above inputs/outputs and this is the result.

**Comment by kizniche** [comment]
I can't replicate your issue from those instructions. Delete your current Outputs and graph, add them, and again, and see if your issue persists. If so, please provide detailed steps that can be followed to reproduce the issue.

**Comment by kizniche** [comment]
What is the correct duration?

**Comment by chitters2004** [comment]
Have just deleted outputs and graph and redone, still getting the same issue. 

At the moment it seems to be sometimes doubling the PID output duration to give the heater output time on the graph. The PID output duration is what is actually happening in real life, the Output duration is incorrect on the graphs.

I'm not really sure how I can provide more detailed instructions i'm afraid....

1. Install Mycodo
2. Configure inputs
3. Configure outputs.
4. Configure PID
5. Create graph with Outputs, Input and PID Duration/%

![Graph](https://user-images.githubusercontent.com/55252868/65465372-08563f80-de54-11e9-936e-fa1de10da38d.png)

**Comment by kizniche** [comment]
Can you turn all other controllers off, then turn daemon debug mode on in the general configuration, debug mode on for the PID. Restart the daemon, and collect the first 10 minutes of logs after restarting the daemon and attach it as a txt file (don't paste)?

**Comment by kizniche** [comment]
We're you changing PID settings while the PID controller was active?

**Comment by kizniche** [comment]
I haven't been able to replicate what you're seeing. Let me know if you can provide the above logging lines. They will be invaluable for investigating the issue.

**Comment by chitters2004** [comment]
I had in the past but seems to make no difference whether I make changes while active or not.

[log.txt](https://github.com/kizniche/Mycodo/files/3646434/log.txt)

**Comment by chitters2004** [comment]
Is it just combining multiple output times together as graph resolution isn't high enough?

**Comment by chitters2004** [comment]
I think it is. Just reduced the x axis down to 60 seconds and now appears to be displaying correctly
![Annotation 2019-09-24 112745](https://user-images.githubusercontent.com/55252868/65504270-78011480-debe-11e9-95c0-d578c7e3f061.png)
.

**Comment by kizniche** [comment]
Try a different browser. I've never seen Highcharts mess up like that before.

**Comment by kizniche** [comment]
Actually, it may be the aggregation setting. Though, I don't recall having this issue before, otherwise I would have likely provided the option to enable/disable aggregation in the graph options.

**Comment by chitters2004** [comment]
It's doing it on edge too.

**Comment by kizniche** [comment]
There will be data aggregation on long duration x-axis spans where data cannot fit. I've experienced it with edge detections/boolean values. I don't recall it happening with Outputs for PIDs as you've shown. Though, perhaps I have and just don't recall.

**Comment by kizniche** [comment]
Ref: https://www.highcharts.com/docs/advanced-chart-features/data-grouping
Outputs use the column series type.

**Comment by kizniche** [comment]
I can add an option to disable grouping. It will have to wait a few days until I return from traveling for work.

**Comment by chitters2004** [comment]
No urgency but thank you.

**Comment by kizniche** [comment]
Closed in 64e28686
