### ISSUE TITLE
LCD not working on 7.7.7

### ISSUE THREAD

**Issue by buzzfuzz2k** [kizniche/Mycodo#698]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.7.7
 
#### Problem Description
LCD is not working since 7.7.7 update

### Steps to Reproduce the issue:
update to 7.7.7 ;)

**Comment by kizniche** [comment]
[7.7.8](https://github.com/kizniche/Mycodo/releases/tag/v7.7.8) fixed this issue.
