### ISSUE TITLE
Cursor offset from mouse position

### ISSUE THREAD

**Issue by chitters2004** [kizniche/Mycodo#702]
## Mycodo Issue Report:
  - Specific Mycodo Version: 7.8.2

#### Problem Description

  When I click where the red X is, the cursor appears where it is shown (about character spaces to the right). This is on every field in mycodo.

![Untitled](https://user-images.githubusercontent.com/55252868/67126098-35490880-f1ee-11e9-936a-8666f94ade0c.png)

**Comment by kizniche** [comment]
What operating system, web browser and version?

**Comment by chitters2004** [comment]
Windows 10, Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by kizniche** [comment]
Browser and version?

**Comment by chitters2004** [comment]
Sorry, Chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by chitters2004** [comment]
OS Build 18362.418

**Comment by chitters2004** [comment]
Unfortunately the last issue fix didn't work but can't reopen the issue.

**Comment by kizniche** [comment]
I was able to replicate this, and I traced it back to bootstrap's form-control class, specifically the padding attribute. However, I could not find this issue documented anywhere. I'll dig deeper later.

**Comment by chitters2004** [comment]
Thank you.

**Comment by kizniche** [comment]
Can you please test the latest version (currently 8.2.2)? I believe updating the latest version of Bootstrap has fixed this issue. I can no longer replicate this issue on the latest version.
