### ISSUE TITLE
Feature Request - White Balance for Picam

### ISSUE THREAD

**Issue by chitters2004** [kizniche/Mycodo#703]
Option to adjust the white balance of raspberry pi camera

**Comment by kizniche** [comment]
Added but untested. If you would like to test, you can [upgrade to master](https://github.com/kizniche/Mycodo/wiki/Updating-to-Github-Master-Branch).

References for options:

https://picamera.readthedocs.io/en/release-1.13/recipes1.html#capturing-consistent-images
https://picamera.readthedocs.io/en/release-1.13/api_camera.html#picamera.PiCamera.awb_mode
https://picamera.readthedocs.io/en/release-1.13/api_camera.html#picamera.PiCamera.awb_gains

**Comment by chitters2004** [comment]
Thank you Kyle, Will give it a try.

**Comment by chitters2004** [comment]
Is there currently any way to change video resolution etc?

**Comment by kizniche** [comment]
Should be the width and height options.

**Comment by chitters2004** [comment]
It appears to be stuck at default on my end.

![Annotation 2019-10-19 000454](https://user-images.githubusercontent.com/55252868/67133327-22413300-f204-11e9-9d66-7e08b3b12eb2.png)

**Comment by kizniche** [comment]
I'll look into it. I also just realized I only applied the white balance settings to still photos, not video. I'll push an update shortly to test.

**Comment by chitters2004** [comment]
You're a legend mate.

**Comment by chitters2004** [comment]
At some point it would be great to be able to adjust ISO, Exposure mode, Shutter speed, Sharpness and Meter modes too....

**Comment by kizniche** [comment]
I've had #313 open for a while. I'll push this up the priority list since I started it today.

**Comment by chitters2004** [comment]
Oh awesome, I didn't notice that.

**Comment by kizniche** [comment]
Added shutter speed, sharpness, iso, exposure mode, meter mode, and image effect

**Comment by kizniche** [comment]
Untested, though. If you do test, please report any issues.

**Comment by chitters2004** [comment]
Upgrading now for test.

**Comment by chitters2004** [comment]
Appears to be working as intended. Will close and come back if anything odd pops up.

**Comment by kizniche** [comment]
I couldn't replicate your different photo/video resolution issue. Can you tell me what version Pi, version pi camera, and what resolution you were using?

**Comment by chitters2004** [comment]
Pi 3B+, cam with 5 Megapixels OV5647 Sensor https://www.amazon.com/d/Networking-Products/MakerFocus-Wide-angle-Automatically-Day-Vision-Night-Vision/B07DPNDP6R, 2592x1944

**Comment by kizniche** [comment]
So that is not the Pi camera?

**Comment by kizniche** [comment]
If it's not an OEM RPi camera, I'm not sure what to tell you. Have you tried a lower resultion? Can you verify 1024x768 produces the same resulting image for still and stream?

**Comment by chitters2004** [comment]
Having difficulties logging in remotely atm but will test as soon as i can. I assumed it would all work the same as it is the same sensor as on the official board.

**Comment by chitters2004** [comment]
It seems that they correspond up until 1920x1080 and then the still image resolution increases while the stream zooms in. I wonder if it is possible to have a separate video/still resolution option to provide the best of both worlds?

**Comment by kizniche** [comment]
Can you verify the same behavior persists after running the following and rebooting to ensure you have the latest firmware: ```sudo rpi-update```

1296x972 doesn't yield the same resolution with still and stream?
