### ISSUE TITLE
Ramping PWM

### ISSUE THREAD

**Issue by SAM26K** [kizniche/Mycodo#704]
## Mycodo Feature Request:Add system clock to Data inputs list.
  - Specific Mycodo Version:
Mycodo Version: 7.8.4
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
Database Version: b6e332156961
Daemon Status: Running
Frontend RAM Usage: 55.104 MB
Frontend Virtualenv: Yes
 
#### Reason:
Want to use conditional to trigger depending on time of day
eg: Ramp a light dimmer from 0-100% for on cycle and ramp  from 100-0% for off cycle.
Needs time of day input to trigger conditional.  Thanks.

Edit:  Also please add time to measurements drop down list. Time only (HH:MM:SS).

**Comment by kizniche** [comment]
Why not use a Trigger: Timer (daily point or span)?

**Comment by kizniche** [comment]
You can also use [time](https://docs.python.org/3/library/time.html) or [datetime](https://docs.python.org/2/library/datetime.html) in conditional statements.

**Comment by SAM26K** [comment]
Trigger Timer Span works but no easy way to ramp the brightness.  Would like to use a linux or python output control to slowly ramp the light  up and down with a for loop.
Tried the following:  The bash file works fine in a terminal session but generates errors with Mycodo. Having similar  problems with python input control.

 Bash file:
`#!/bin/bash
out=$(date +"%T")
echo $out
exit 0`

Daemon error:
`2019-10-22 03:08:01,739 - ERROR - mycodo.controllers.controller_input_58b94ce3 - StopIteration raised 3 times. Possibly could not read input. Ensure it's connected properly and detected.`

Input control:
![time1](https://user-images.githubusercontent.com/22091149/67276586-e4e5db00-f479-11e9-8bc3-82f00f90e48e.jpg)

**Comment by SAM26K** [comment]
Also tried this python 3 data input control.  Works ok on RPi Python 3 RPi and returns 

> 2019-10-22 03:30:05.632968

but generates errors with Mycodo:
**Save control error:**
`************* Module mycodo.user_python_code.input_python_code_d1bba7fe-8437-4bf3-a7b9-c22a33a4fea9
R: 23, 4: Method could be a function (no-self-use)

**and daemon error:**
`2019-10-22 03:37:44,495 - ERROR - mycodo.controllers.controller_input_d1bba7fe - StopIteration raised 3 times. Possibly could not read input. Ensure it's connected properly and detected.`

`
![time2py](https://user-images.githubusercontent.com/22091149/67278199-5bd0a300-f47d-11e9-82d1-0bbc96aae92b.jpg)

**Comment by SAM26K** [comment]
Cleaned up python data input but getting a daemon type error:
`2019-10-22 04:42:40,881 - ERROR - mycodo.inputs.python_code_d1bba7fe - 1
Traceback (most recent call last):
  File "/home/pi/Mycodo/mycodo/inputs/python_code.py", line 214, in get_measurement
    run.python_code_run()
  File "/home/pi/Mycodo/mycodo/user_python_code/input_python_code_d1bba7fe-8437-4bf3-a7b9-c22a33a4fea9.py", line 26, in python_code_run
    self.store_measurement(channel=0, measurement=time_channel_0)
  File "/home/pi/Mycodo/mycodo/user_python_code/input_python_code_d1bba7fe-8437-4bf3-a7b9-c22a33a4fea9.py", line 21, in store_measurement
    add_measurements_influxdb(self.input_id, measure)
  File "/var/mycodo-root/mycodo/utils/influx.py", line 53, in add_measurements_influxdb
    timestamp=timestamp))
  File "/var/mycodo-root/mycodo/utils/influx.py", line 87, in format_influxdb_data
    checked_value = float(value)
TypeError: float() argument must be a string or a number, not 'datetime.datetime'`
![time3py](https://user-images.githubusercontent.com/22091149/67282703-2f218900-f487-11e9-8f55-3af1c445e7b6.jpg)

**Comment by kizniche** [comment]
Creating an input is not the way to go, for several reasons. 1. In a time-series database, you can only store numerical values. 2. There is already a timestamp associated with the value in a time-series database (i.e. timestamping the current time with the current time is nonsensical. 3. Python has numerous ways of working with time (e.g. time, datetime).

This is the Python code for calculating the time as epoch in the future for a particular "HH:MM:SS" string given as a parameter:

https://github.com/kizniche/Mycodo/blob/31b0fa3aee66dda09e3fa91dbef445b3e8d9aec6/mycodo/utils/system_pi.py#L199-L212

To use this in your Conditional:

```python
from mycodo.utils.system_pi import epoch_of_next_time

time_str = "10:30:00"  # Desired time (string)
time_epoch = epoch_of_next_time(time_str)  # Desired future time (epoch)

if time_epoch < time.time():
    time_epoch = epoch_of_next_time(time_str)  # Update future epoch to tomorrow
    # code here to do something at 10:30 AM
```

**Comment by kizniche** [comment]
If you want to go the Trigger route, I could add a "Ramp PWM" Action that would make the whole process simpler.

**Comment by kizniche** [comment]
I just pushed code changes that add a PWM Ramp Action, among other things. You can upgrade to master to test. I would recommend using the Action with a Daily Time Point Trigger. If you do test, let me know how it goes.

**Comment by SAM26K** [comment]
Ramp PWM would be great!  Thanks for the help.

**Comment by kizniche** [comment]
The code to test has been up. You'll have to [upgrade to master](https://github.com/kizniche/Mycodo/wiki/Updating-to-Github-Master-Branch) to test.

**Comment by SAM26K** [comment]
Seems to work really well if interval is set to 600 secs or more (0-100 or 100-0 %PWM) below that number the duty cycle gets noisy and occasionally jumps up and down.  Maybe if increment could be a user  parameter that could be  set higher than 0.1% it   would smooth out the shorter ramp times?
It's no big deal though and plan on ramp times greater than 900 secs which works fine.
Using single point daily trigger functions, one to ramp up the brightness and a 2nd one to ramp it down.  
![fade2](https://user-images.githubusercontent.com/22091149/67568587-773be800-f6e1-11e9-961d-de4faccb0357.jpg)

**Comment by kizniche** [comment]
I've never experienced the duty cycle jumping up and down, but I did find that short periods cause the PWM to be updated very fast, since it operates on 0.1 % steps. I will likely add the option to select either 1 % or 0.1 % steps, but for the initial implementation to test, I went with a default of 0.1 %. For most applications, this should be sufficient.

**Comment by kizniche** [comment]
Just added the ability to select the duty cycle step size.

**Comment by kizniche** [comment]
Minor revision released for upgrade
