### ISSUE TITLE
Cannot access Mycodo through browser after most recent update

### ISSUE THREAD

**Issue by jacopienaar** [kizniche/Mycodo#707]
After running the latest Mycodo update on a Pi Model 3B+, I am unable to access Mycodo through the browswer. I still have access to the Pi through ssh. Anyone else have this issue?

When entering the IP I get a "Error 502: Bad Gateway" prompt

Rolling back to previous version now to see if that solves the problem.

**Comment by jacopienaar** [comment]
So I updated Raspbian and restored from Mycodo backup (no errors) but no joy. Don't know what to do next.

**Comment by jacopienaar** [comment]
Ok then. Feeling like a bit of a tool.  Did the ol' "switch it off and on again" and it works again.  Please close this issue and delete/burn it.

**Comment by kizniche** [comment]
Glad you got it working.
