### ISSUE TITLE
Philips Hue Smart Light Integration

### ISSUE THREAD

**Issue by smguth** [kizniche/Mycodo#722]
**Is your feature request related to a problem? Please describe.**
Light automation support/Ideas with Philips Hue

**Describe the solution you'd like**
I would like to use mycodo for light schedules with the philips hue lights.  Also, could  it send an alert - set a light bulb a notification color.  Example: temp high alarm - light turns red

I'm pretty excited about this one...
I found this URL  https://github.com/bahamas10/hueadm
So I ran:
curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g hueadm
hueadm search
hueadm "IPADDRESS_OF_HUE" register user
nano ~/.hueadm.json  
pasted my ipaddress and user string in the file **follow the url's guide**
hueadm lights
hueadm light 3 ON
hueadm light 3 green
hueadm light 3 red

smguth@raspberrypi:~ $ hueadm lights
ID  NAME       STATUS  BRIGHTNESS  REACHABLE
1   Bedroom 1  on      254         true
2   Bedroom 2  on      254         true
3   Kitchen 1  on      127         true
4   Door 1     on      254         true
5   Bathroom   on      254         false
6   Upstairs   off     126         true
8   Fish Tank  on      254         false
smguth@raspberrypi:~ $ hueadm light 3 on
    success: {/lights/3/state/on: true}
smguth@raspberrypi:~ $ hueadm light 3 off
    success: {/lights/3/state/on: false}
smguth@raspberrypi:~ $ hueadm light 3 green
    success: {/lights/3/state/on: true}
    success: {/lights/3/state/hue: 21845}
    success: {/lights/3/state/sat: 254}
    success: {/lights/3/state/bri: 64}
smguth@raspberrypi:~ $ hueadm light 3 red
    success: {/lights/3/state/on: true}
    success: {/lights/3/state/hue: 0}
    success: {/lights/3/state/sat: 254}
    success: {/lights/3/state/bri: 127}

The commands all work on my raspberry pi that is running mycodo.

https://github.com/bahamas10/hueadm
![philips Hue](https://user-images.githubusercontent.com/11531815/70494842-7e248b80-1ad2-11ea-900d-d6426788fa03.png)
This picture isn't the color lights but to get started is most cost effective

**Comment by kizniche** [comment]
Conditionals are pretty powerful and can be programmed to do all you mentioned. Conditionals are programmed in Python 3. You can use ```subsystem``` to execute ```hueadm```, unless there's a python library that would make it easier/more secure.

Found some libraries:

 -  https://github.com/studioimaginaire/phue
 -  https://github.com/quentinsf/qhue
 -  https://github.com/issackelly/python-hue
 -  https://github.com/adamcharnock/python-hue-client

**Comment by kizniche** [comment]
Looks like phue is the most feature-rich and up-to-date library that's actively maintained. I'd suggest testing this library for use in Conditionals, as it's in the native language used by Mycodo.

**Comment by kizniche** [comment]
I've been working on a new feature for the 8.5.0 release that allows custom output modules to be imported, which will allow user-created, single-file output modules to be used. This will enable rapid-prototyping and deployment of new output modules for use in Mycodo. This issue is a perfect candidate for using the new output system and I'd like to help develop an output module for these lights. There will likely be some tweaking that needs to go on behind the scenes to allow color to be passed to an output module, but the heavy lifting has mostly been done.

**Comment by ebo** [comment]
Out of curiosity, has anyone looked at the Hue's security (see: https://www.usatoday.com/story/tech/2020/02/05/how-to-avoid-smart-lights-getting-hacked/4660430002/ ).  Personally I would love to use them but am concerned about their security.

**Comment by kizniche** [comment]
This issue has been mentioned on **Radical DIY Forum**. There might be relevant details there:

https://forum.radicaldiy.com/t/trying-to-remember-how-i-got-philips-hue-lights-controlled-on-the-mycodo-r-pi-server-troubleshooting-documenting/1528/1
