### ISSUE TITLE
PID Dashboard Setpoint Incorrect

### ISSUE THREAD

**Issue by not5** [kizniche/Mycodo#744]
### Describe the problem/bug

The PID dashboard controller is showing the Setpoint as setpoint+1 for some reason.

Not critical, and I understand that the dashboard control is supplemental to everything.

**Comment by kizniche** [comment]
I can't replicate this issue. Can you take screenshots of both your PID settings and the PID dashboard widget?

**Comment by not5** [comment]
Sure thing, although I'm not sure what the screenshot tells you other than validating my issue.
![20200222_070526](https://user-images.githubusercontent.com/43415025/75092040-f7fcda80-5541-11ea-945b-b1aaa2e8a14a.jpg)
![20200222_070556](https://user-images.githubusercontent.com/43415025/75092043-fc28f800-5541-11ea-863d-a0220ee21102.jpg)

**Comment by kizniche** [comment]
Your settings indicate you have a 1 degree band set, which you didn't indicate indicate in the issue. This is the +1.

**Comment by not5** [comment]
So the Band is added to the setpoint on the PID dashboard controller. Got it. Thanks!

**Comment by kizniche** [comment]
Yes. Notice if you display the setpoint on your graph it will also be this value (at present). The setpoint will change based on the band and what stage the PID is at, either set to the higher or lower band (you can also display the setpoint with the upper and lower band on the graph). In theory this should work, but I haven't used the band feature in a while. If you think it's behaving improperly, let me know.

**Comment by kizniche** [comment]
> I'm not sure why the setpoint spans previous.

When the PID runs every period, it will calculate the new P, I, and D values along with the other values. Regardless of whether there's an actual output value that will meet the thresholds to turn on an output, the PID values will be saved to the influx database (setpoint, control variable, etc.). The widgets merely query this database and pull whatever data is there. So, the setpoint is saved every period the PID is active.

**Comment by kizniche** [comment]
I actually got the setpoint for PIDs with bands to display correctly on dashboard widgets. Now, if the band is in effect, the widget setpoint will change to that value, and once the measurement passes that min or max, it will change to the actual [unbanded] setpoint until the measurement passes a band. This is the behavior is should have had all along. Now that I've been using PIDs with bands, it started bothering me I couldn't immediately see what band was in effect. This will be out in the next release.

**Comment by not5** [comment]
Very slick implementation. Thanks!
