### ISSUE TITLE
Error setting DS18b20 resolution

### ISSUE THREAD

**Issue by drgrumpy** [kizniche/Mycodo#747]
- Mycodo Version: 8.25
 - Raspberry Pi Version: Zero W
 - Raspbian OS Version: Buster Lite

Clean install (with one mod to mycodo see #746)  first ds18b20 sensor added, attempt to set sensor resolution on configuration page:

Error: Error while setting resolution of sensor with ID 28-000006daa134: 'NoneType' object has no attribute 'device'

I can successfully set the resolution directly from the terminal by writing to the device

**Comment by kizniche** [comment]
I just pushed a potential fix for this. I haven't tested it, thought.

**Comment by kizniche** [comment]
In the meantime, you can set the resolution from the Input settings. This resolution setting from the calibration page merely makes the resolution setting persistent, whereas the Input settings is not persistent and is set every time the input is activated.

**Comment by drgrumpy** [comment]
Great thanks for sorting
