### ISSUE TITLE
Add an Hour button to the Asynchronous Graphs

### ISSUE THREAD

**Issue by dylandn** [kizniche/Mycodo#756]
On the Asynchronous Graphs page, there is the "Zoom: 1h" button above the graph, but there is no "Past: Hour" button below the graph. I think it would be convenient to add the Hour scale as a preset.

**Comment by kizniche** [comment]
There's so little data cost to loading async graphs, there's really no benefit to having redundant data range buttons on both the web form and the graph itself. Adding more form buttons only clutter the interface.
