### ISSUE TITLE
PID controller ignores Min Duty Cycle

### ISSUE THREAD

**Issue by neongrau81** [kizniche/Mycodo#757]
### Describe the problem/bug

**SETUP**
I am running a PID controller to control the temperature in my grow room.
As input I use an "_Average (Last, Multiple Channels)_" controller that uses the temperature values of several temp sensors.

![image](https://user-images.githubusercontent.com/61628487/76787382-37bd8780-67b9-11ea-8ff2-8b10c5afc4b4.png)

As output I run a _PWM Linux Command_
curl -s -m 10 http://192.168.179.29/cm?cmnd=Dimmer%20((duty_cycle))

The command tells an ESP8266 that runs Tasmota to control the fan-speed

**PROBLEM**
As I want to run my exhaust fan constantly at a very slow pace (~10%) I set a _Min duty cycle_ of 10.
And because my exhaust fan is a little oversized for my room, I as well set a _Max duty cycle_ of 80.

It seems that mycodo in my case ignores the _Min duty cycle_ setting because my ESP8266 receives a lot of calls that tell the fan to run at 0%
![image](https://user-images.githubusercontent.com/61628487/76787734-e9f54f00-67b9-11ea-8768-5e1060980503.png)

The Max duty cycle although seems to work fine
![image](https://user-images.githubusercontent.com/61628487/76787502-76ebd880-67b9-11ea-861f-4a33cae67b3f.png)

I used wireshark to verify,if either the ESP8266 misinterprets a valid call from mycodo, or if mycodo itself sends out the 0% to the ESP. According to WS the mycodo sends out calls to http://192.168.179.29/cm?cmnd=Dimmer%200 

### Versions:

 - Mycodo Version: 8.0.3
 - Raspberry Pi Version: 3B+
 - Raspbian OS Version: Buster 

### Expected behavior:

As long as PID controller generates an output =< _Min ducty cycle_, the value gets overwritten by the _Min duty cycle_

**Comment by kizniche** [comment]
This is the expected behavior. It is modeled after the duration output behavior. A minimum duration or duty cycle does not mean the output is alway outputting at least that amount every PID cycle, but rather the PID output must be at least that amount for the output to be activated for that duration or duty cycle. If it were always at least outputting the min value, it would cause interference with the alternate output if the PID was attempting to regulate in the opposite direction.

That being said, I do see a benefit for PWM Outputs to have an additional option, "Only Between Min/Max" (default: True), that will only allow the duty cycle to be set to a value between min and max.

**Comment by neongrau81** [comment]
Wow, thanks a lot for the super fast response and the clarification !

The additional option would be great, so I can be sure to always have a "negative pressure" in the room by a constantly running exhaust fan. -> less skunky flavor for the neighbors :-)

Thanks for the great work you do with mycodo, I absolutely love this system

**Comment by kizniche** [comment]
I just pushed a commit that adds this feature. If you would like to test before the release, you can [upgrade to master](https://github.com/kizniche/Mycodo/wiki/Updating-to-Github-Master-Branch).

**Comment by neongrau81** [comment]
Hey @kizniche I was a bit shy upgrading to master as my system was running smooth after a while of tweaking ;-)

I updated to 8.4.0 two weeks ago and started testing.

![image](https://user-images.githubusercontent.com/61628487/78450074-4393bf80-767c-11ea-846a-6cc5ef21e080.png)
I have checked the "Always min" checkbox, what (as far as I understood) should prevent the output to send any value below this threshold. But it seems like the checkbox is ignored, my exhaust fan still goes down to 0% every now and than.

Do you have any idea?

**Comment by kizniche** [comment]
Can you provide a graph showing the following series when the 0 duty cycle occurs: temperature input, duty cycle of the output as well as the P, I and D measurements, PID setpoint,

**Comment by neongrau81** [comment]
Here you go :-) Sorry, I had to wait for a night cycle to show a proper graph.
![image](https://user-images.githubusercontent.com/61628487/78471125-118f6580-772f-11ea-8994-7c88ef66472c.png)
The little spike of the _PWM up_ on the right is due to a second PID controller that uses the same output. As I don't have a dehumidifier, I use my exhaust fan as well to reduce the humidty as soon as it exceeds a certain threshold (56% humidity).
