### ISSUE TITLE
Graph shows PWM as >100%

### ISSUE THREAD

**Issue by drgrumpy** [kizniche/Mycodo#759]
Version 8.3

Not critical

When displaying PWM output Duty Cycle I expect the values to be displayed are in the range 0 to 100%, actual value displayed is up to 450%. Presumably some kind of scaling issue?

**Comment by kizniche** [comment]
Displayed where?

**Comment by drgrumpy** [comment]
Sorry dashboard

**Comment by kizniche** [comment]
There are numerous places on a dashboard duty cycle can be displayed. Can you be specific?

**Comment by drgrumpy** [comment]
Actually I think I am perhaps misunderstanding:
The value when I hover over it is shown as e.g. 475% but it is actually truncated to 100% for display.
I'll post a screenshot...

**Comment by drgrumpy** [comment]
![image](https://user-images.githubusercontent.com/4687649/77340993-f92e4c80-6d25-11ea-93a6-019b28ffcab0.png)

**Comment by drgrumpy** [comment]
So perhaps it is as intended?

**Comment by kizniche** [comment]
It's intended if you have data grouping enabled.

**Comment by drgrumpy** [comment]
Apologies if I missed it, but I couldn't find or figure out what data grouping is for/supposed to do? Now I understand, and indeed if turn off data grouping I get the 'old' (?) expected behaviour

**Comment by kizniche** [comment]
Data grouping has always been on by default. The option to disable it was only added this past year.
