### ISSUE TITLE
Special symbols in passwords are causing problems at log-in

### ISSUE THREAD

**Issue by AncientGate** [kizniche/Mycodo#76]
**AFFECTED:**  Log-in script / password processing script

**ERROR:** "Invalid cookie data" (generated by index.php line 211)

**PROBLEM DESCRIPTION 1:**
After setting the admin password via installation step:
`sudo /var/www/mycodo/update-database.py -i`
example of password: #pR*uDjbLK@Jb!!NElkJSpx73j
then due to special symbols are meaningful for the script itself, so it does process those wrong.
Please confirm also that database can keep this type of passwords, since it may interfere with the script which is responsible for password encryption too.
Error will appear on log-in "Invalid cookie data" 

**TEMPORARY SOLUTION:** Use passwords Alpha-Numeric only and if got this error already,
then re-run database initialization again (`sudo /var/www/mycodo/update-database.py -i`) and set new alpha-numeric password.
In case of you set in browser to memorize the password, the browser have to be reset (empty cookies, and passwords for past hours), otherwise on page load the error will appear again.

**PROBLEM DESCRIPTION 2:**
If have created initially with :
`sudo /var/www/mycodo/update-database.py -i`
user database, and then recreated it by any reason same way, while you had saved your password in browser (specifically if the browser had a cookie kept), then error will appear on log-in "Invalid cookie data" 

**TEMPORARY SOLUTION:** Delete cookies for the Mycodo website in your browser and reload the page

**Comment by kizniche** [comment]
Yes, passwords must be alphanumeric. This is not explicitly stated, but it is so.

This should be mentioned either in the readme or the script to create the password, or both.

**Comment by MountAthos** [comment]
I believe that for good security all passwords shall be always mixed case , special symbols etc. especially if server is exposed to the public. IMHO complex , mixed case passwords are standard when it's about security.

**Comment by kizniche** [comment]
I agree, but I needed an initial implementation that excluded special characters, to simplify development (and reduce risk of SQL injection). 

If you know of a solution, you're welcome to submit a pull request updating the database install and login scripts, so long as they follow standard security practices.

**Comment by MountAthos** [comment]
Dear Kyle,
please tell me , the table in DB called "HTSensorConditional"
In which cases you are using to keep data in this one?
I need to understand better the idea of your structure.
I am implementing sensor according to the way you have made for other
sensor, with exception of multiplexer, because this sensor will mostly not
work with multiplexer.

I am in programming right now , so hope to get from you soon answer, just
don't want to remake later too much :)

Since i don't know all of your thoughts :) Nor long enough this project, i
am sure i will make not that perfect implementation, but i am trying to
understand it ...

Yours Seraphim.

**Comment by kizniche** [comment]
This is specifically for a humidity and Temperature sensor (humidity and temperature on the same chip/board), that stores the variables for the conditional statements that can be created for a sensor. For instance, "Every **200** seconds, if the **temperature** is **above** **23** degrees, turn relay **2** **on** for **30** seconds"

**Comment by MountAthos** [comment]
Ahh ok , i understood :)
So its actually correct to use HT tables for new sensor , since this one is
combined one too..
Just was not sure about the purpose for the conditional tables.
But now i understood.. thank you :)
