### ISSUE TITLE
GPIO Outputs won't show in dashboard after upgrade to 8.5.1

### ISSUE THREAD

**Issue by Bart9999** [kizniche/Mycodo#779]
I also have some issues with the GPIO outputs. I've configured the system in version 8.4.0 Everything works fine. Today i have added an output: Ontvochtiger
![image](https://user-images.githubusercontent.com/66528391/83950130-89aa0280-a828-11ea-9e1e-69d610af6ce9.png)

I can refer to this output in the PID controller:
![image](https://user-images.githubusercontent.com/66528391/83950165-d55cac00-a828-11ea-8048-4f040f63a7ca.png)

Unfortunately i can not choose this output in the dashboard (not in the Output widget and also not in the Indicator widget)
![image](https://user-images.githubusercontent.com/66528391/83950201-2bc9ea80-a829-11ea-910c-8330a6d92bad.png)
![image](https://user-images.githubusercontent.com/66528391/83950223-66cc1e00-a829-11ea-9a78-383b6f7d30d5.png)

For some reason only the outputs are visible that were created before the upgrade. Any idea what i'm doing wrong?

**Comment by kizniche** [comment]
Thank you for the detailed info. I'll investigate and get back to you.

**Comment by Bart9999** [comment]
BTW, I also tried unistalling Mycodo and after that installed Mycodo completely from the beginning by the command:  curl -L https://kizniche.github.io/Mycodo/install | bash

The same issue appeared.

**Comment by kizniche** [comment]
I was able to replicate the issue. Working on a fix.

**Comment by kizniche** [comment]
Just committed a fix and released v8.5.3. Thanks for the bug report.

**Comment by Bart9999** [comment]
Thanks. Outputs are showing again in the dashboard :-)

**Comment by kizniche** [comment]
Thanks for confirming the fix works out in the wild.
