### ISSUE TITLE
unable to connect to web server

### ISSUE THREAD

**Issue by Mondster** [kizniche/Mycodo#784]

**Comment by kizniche** [comment]
Can you provide the rest of the log? It attempts 5 times because the first attempt is often not long enough to allow the server to start, especially on any Pi prior to version 4.

**Comment by Mondster** [comment]
sorry my bad, i didnt saw the part using the lite version. i reflash the os to lite and its working now.

**Comment by Mondster** [comment]
beside this i got question on the probes, if i just follow this site and get the probes listed, ec, ph, temp i should be able to get the device working without any issue correct? 

https://kylegabriel.com/projects/2020/06/automated-hydroponic-system-build.html?unapproved=652&moderation-hash=29d9dfaad4c6806d4044883e03bf6b9d#comment-652

**Comment by kizniche** [comment]
I still need to download the desktop version and see what exactly is different that might be causing install problems. Supposedly others have successfully installed on the desktop version, so there's conflicting information. Nearly all of my PIs are headless. The ones I do have a touch display for I install the lite version and then install X and a window manager so I know I have the most minimal ampunt of space used for the GUI.

**Comment by kizniche** [comment]
The sensors I list there I'm currently using with Mycodo, so they're guaranteed to work. You could likely get most sensors to work, but you may have to put some time in figuring out the hardware interfacing and setting up software to read it.

**Comment by Mondster** [comment]
I tested the desktop version like 5 times, be it full or the vanilla it wasnt able to work. hence i re-read the steps and found a line you tested on the lite version. hence i reflash and it works. like you mention if i need the gui i just need to install x and get the gui up.

**Comment by Mondster** [comment]
> 
> 
> The sensors I list there I'm currently using with Mycodo, so they're guaranteed to work. You could likely get most sensors to work, but you may have to put some time in figuring out the hardware interfacing and setting up software to read it.

i think i just follow your setup becuase i not very pro in hardware on raspi. just that these altas device is a little pricey. :)

however i have a semi automated solution making use of my smart home fibaro setup to trigger chiller base on the temp. I pipe these data to my splunk collector and perform a api call when the parameter i set meet.

**Comment by Mondster** [comment]
![image](https://user-images.githubusercontent.com/13143891/86866225-18998b80-c103-11ea-813f-fb1c362927ec.png)

**Comment by Mondster** [comment]
![image](https://user-images.githubusercontent.com/13143891/86866255-26e7a780-c103-11ea-8798-8f6ae6db10ca.png)

**Comment by Mondster** [comment]
hopefully i am able to get your device up and working so i can perform more integration.
