### ISSUE TITLE
Failed to start Mycodo server

### ISSUE THREAD

**Issue by Barnickel** [kizniche/Mycodo#787]
Please complete as many of the sections below, if applicable, to provide the most information that may help with investigating your issue.

### Describe the problem/bug

After a recent update faild the mycodo server wasnt starting.
I freshly installed mycodo and im receiving an error

pi@raspberrypi:~ $ sudo /var/mycodo-root/env/bin/python /var/mycodo-root/mycodo/mycodo_daemon.py --debug
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/mycodo_daemon.py", line 40, in <module>
    from Pyro5.api import serve
ModuleNotFoundError: No module named 'Pyro5'

### Versions:

 - Mycodo Version: 8.5.8
 - Raspberry Pi Version: Raspberry Pi 3 Model B Rev 1.2p
 - Raspbian OS Version: Raspbian 10 Buster

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

I execute the install script and it errors with the error message above

### Screenshots

![image](https://user-images.githubusercontent.com/68301023/87471769-3002d800-c61f-11ea-897f-f3399a87fea9.png)

### Additional context

Is there anything that should be added to make it easier to address this issue?

**Comment by dandyfop** [comment]
I too have had this exact issue and been trying to troubleshoot for several days now.
Also running Mycodo 8.5.8, RPi 3B+, on Buster.

**Comment by kizniche** [comment]
Lite or Desktop Raspberry Pi OS image?

**Comment by kizniche** [comment]
What version did you upgrade from?

**Comment by kizniche** [comment]
This comment has commands to rebuild your python virtualenv: https://github.com/kizniche/Mycodo/issues/776#issuecomment-636606371

After issuing those commands, restart the Pi with ```sudo shutdown now -r```

**Comment by Barnickel** [comment]
@kizniche it is the Desktop Raspberry Pi OS Image
I tried upgradeing from 8.5.4 when the Update failed.
After that i tried a fresh mycodo install.

I tried the commands to rebuild the virtualenv. After the reboot i still get the same Error :(

![image](https://user-images.githubusercontent.com/68301023/87519354-c536b880-c681-11ea-9e06-a8b5773cc8fa.png)

**Comment by Barnickel** [comment]
Here is the Error i found while rebuilding virtualenv

![image](https://user-images.githubusercontent.com/68301023/87528674-206ea800-c68e-11ea-9360-ce75c85fc078.png)

**Comment by kizniche** [comment]
The Desktop image version has an incompatible software version installed ([issue discovered yesterday](https://kylegabriel.com/forum/general-discussion/mycodo-installer-script-on-fresh-default-installation-of-raspbian-buster-fails-to-detect-failure-of-necessary-modules-mycodo-daemon-unstartable)). Uninstall the cffi packages with the following command, then rebuild your virtualenv again with the command in the above comment I linked to.

```bash
sudo apt remove python-cffi-backend python3-cffi-backend
```

**Comment by Barnickel** [comment]
Thank you Kyle this fixed the Problem :)
Server is up and running again.
Really appreciate your work, thank you for your Help
