### ISSUE TITLE
Add ADXL343-ADT7410 Sensor Module

### ISSUE THREAD

**Issue by Magnum-Pl** [kizniche/Mycodo#791]
Hey Kyle, 

Can you add the ADXL343-ADT7410 sensor module from Analog Devices/Digikey?

I attached the script I used to get it working. 

[ADXL343_ADT7410.ino.zip](https://github.com/kizniche/Mycodo/files/4941289/ADXL343_ADT7410.ino.zip)

[https://www.adafruit.com/product/4147](https://www.adafruit.com/product/4147)

![4147-04](https://user-images.githubusercontent.com/10717552/87847827-8fbbe600-c8a0-11ea-8b6a-f1b33ab9905f.jpg)

**Comment by kizniche** [comment]
Do you know of any Python code? Arduino code can't run on a Pi, so it would have to be ported if Python code doesn't exist.

**Comment by kizniche** [comment]
I'd be inclined to make two input modules, one for each sensor. For instance, the ADXL343 has the most up-to-date code at https://github.com/adafruit/Adafruit_CircuitPython_ADXL34x however I've had trouble in the past attempting to change from the default I2C bus, which is a common thing to do with I2C devices. I'll dive back into the circuitpython code and try again, but if you happen to find a solution for this, let me know.

**Comment by kizniche** [comment]
Alright, after some digging, it looks like https://github.com/adafruit/Adafruit_Python_Extended_Bus is what we need to use to be able to select the specific I2C bus the sensor is connected to. I can post a test Input module if you're willing to test.

**Comment by kizniche** [comment]
Reference to issue for the Raspberry Pi 4 and its additional I2C buses: https://github.com/adafruit/Adafruit_Blinka/issues/189

**Comment by Magnum-Pl** [comment]
Yeah, I can test it.

**Comment by kizniche** [comment]
Here's test module v01: [adxl343_test_01.py.txt](https://github.com/kizniche/Mycodo/files/4942946/adxl343_test_01.py.txt)

Rename from .txt to .py and import from the Configuration -> Input menu.

**Comment by kizniche** [comment]
And here's the ADT7410 test module v01: [adt7410_test_01.py.txt](https://github.com/kizniche/Mycodo/files/4943066/adt7410_test_01.py.txt)

**Comment by Magnum-Pl** [comment]
I was able to get the test module installed and its working great. Can you change the units from "G-Force" to "MS^2" for meters per second squared?

Live data and a graph look like this:

<img width="1431" alt="Screen Shot 2020-07-18 at 7 58 49 PM" src="https://user-images.githubusercontent.com/10717552/87864724-6ac38380-c931-11ea-85d6-fa557c1f1b83.png">

<img width="1435" alt="Screen Shot 2020-07-18 at 7 48 33 PM" src="https://user-images.githubusercontent.com/10717552/87864729-7151fb00-c931-11ea-9b3c-4a700bb6a5a3.png">

**Comment by kizniche** [comment]
The measurements are in g-force, not ms^2, correct?

**Comment by kizniche** [comment]
If you want to convert to ms^2, you can add a conversion, then select convert from the input measurement options.

**Comment by Magnum-Pl** [comment]
The sensor is supposed to measuring acceleration in units of ms^2. In the photo above, the sensor was sitting on a table. You can tell the downward direction is the Z-axis because the 10.003 value is near the 9.8ms^2 or the acceleration due to gravity. If it was measuring g-force, wouldn't the value on the Z-axis would be 1?

**Comment by Magnum-Pl** [comment]
I was able to get the ADT7410 test module installed working too.

**Comment by kizniche** [comment]
Okay. I was going off the data sheet, and that's the units it was using in the specifications. Typically they use the unit the sensor returns. Guess not in this case. I'll change the units for the modules in the release. Want me to attach them here afterbi make the edits, so you can use them before the release? I'm out of my house right now so won't be able to get to it until later. Thanks for testing!

**Comment by kizniche** [comment]
I'll look into this further. It may actually be g and needs to be calibrated. In any case, I'll add options to the input(s) for these special actions/options
Now that I know they work, I feel better about putting in extra work.

**Comment by Magnum-Pl** [comment]
I was thinking in terms of ms^2 because the Adafruit code I've been using displays ms^2 by default and I didn't see any conversion. I see in the data sheet that all the units are in g, but since one g is 9.8ms^2 and the z-axis value is within 2% of that, I'm assuming the data is in ms^2. 

I read in the data sheet on pages 28-29 about calibration. Would it be very difficult to add a method for calibration?

I'd appreciate the edited modules when you finish them. 

Thanks a lot for your help.

**Comment by kizniche** [comment]
Just verified that the Adafruit library does indeed convert from g to m/s^2. I'll change the units in the Mycodo module.

See https://github.com/adafruit/Adafruit_CircuitPython_ADXL34x/blob/35a1a1bc11407c4db3ab94755a67a58d57deca89/adafruit_adxl34x.py#L179-L185

**Comment by kizniche** [comment]
I added a conversion to/from g and m/s/s (available in next release), changed units to m/s/s, and added the option to select the range. There is no calibration in the Adafruit library. ADXL34x test module v02: [adxl34x_test_02.py.txt](https://github.com/kizniche/Mycodo/files/4943195/adxl34x_test_02.py.txt)

If you import the above input module without first making the changes to [mycodo/config_devices_units.py](https://github.com/kizniche/Mycodo/commit/058a57a2b00facecbb95834efdc9c16b0509cdb1#diff-8c6effbabae3548ad4e45fb242bf0a08), you may break your system. So, make sure you have the edits I just pushed before doing so.

There weren't any additional functions in the Adafruit ADT7410 library, so no new options were added to this input module.

**Comment by Magnum-Pl** [comment]
I'll probably use it as is until the update. I have it running on an ESP8266 with MQTT right now and that only uses the MQTT input. It's nice to be able to run the sensor directly on the Pi though. 

Thanks for all your help.
