### ISSUE TITLE
cannot turn conditionnal statements ON & OFF

### ISSUE THREAD

**Issue by Myke974** [kizniche/Mycodo#8]
To turn 1 ON or OFF, the trick is to rewrite the same info in all the boxes before using the button turn on / turn off or delete ! !
need fix ! ;)

**Comment by kizniche** [comment]
fixed in commit [6fcecfa256ace5bec7ad50850b26d622b2341cfd](https://github.com/kizniche/Mycodo/commit/6fcecfa256ace5bec7ad50850b26d622b2341cfd)
