### ISSUE TITLE
Enhancement - mycodo allow changing pi root user

### ISSUE THREAD

**Issue by stardawg** [kizniche/Mycodo#809]
Leaving default pi root user is a security risk. mycodo should support removing default root user.

**Comment by kizniche** [comment]
I'm not quite following. User "pi" is not root, although it has sudo access. And it's not possible to remove "root".

**Comment by kizniche** [comment]
If you're concerned about someone remotely accessing your system through the user pi, merely disable SSH access for pi.

**Comment by kizniche** [comment]
In any case, you should never leave the default password set for the user pi. If you have a suggestion for a change, please share. Otherwise, I'm not sure what you're asking.
