### ISSUE TITLE
Graph output duration period (Not feature request, informational)

### ISSUE THREAD

**Issue by BirdBare** [kizniche/Mycodo#815]
Hi,

I'm trying to monitor my PID heater with greater resolution. In the PID overview you show a graph with a 20sec period between output duration measurements. I can't figure out how to change the period. Can you point me in the right direction?

Below is the example you show.

<img width="850" alt="Screen Shot 2020-08-14 at 10 14 33 AM" src="https://user-images.githubusercontent.com/1051490/90264773-33a09f00-de17-11ea-96c4-49939b036e69.png">

**Comment by BirdBare** [comment]
As additional information. I have a 1440 x axis duration and I am monitoring an On/Off python command. Right now the period is every 5 minutes.

**Comment by kizniche** [comment]
The Period option determines the interval for which PID and Conditional Controllers operate.

**Comment by BirdBare** [comment]
Thanks for the reply. I think I am still missing something. If I increase the temp the number shoots past the PID period as you can see at the end of the attached graph. Additionally, I really like the bar look you had in your graph. Are you using a custom widget or is that possible with the builtin widgets?

<img width="1408" alt="Screen Shot 2020-08-14 at 4 27 39 PM" src="https://user-images.githubusercontent.com/1051490/90294059-28676680-de4b-11ea-83d8-b39b0e080ab1.png">

**Comment by BirdBare** [comment]
In the case where it shoots up I get a PID output duration of 1000 seconds.

**Comment by BirdBare** [comment]
To clarify, I know how to change the period in the PID. But not the period in the graph as you have done. If I use the PID output duration I get crazy high numbers. If I use the raw output duration the period is always set to 60 seconds.

**Comment by BirdBare** [comment]
Here is a graph with the raw output duration. I get the output time as bars which is what I want. But the period is every 60 seconds. Is there an easy way to change the period to 20 seconds like you have above?

<img width="1412" alt="Screen Shot 2020-08-14 at 4 34 47 PM" src="https://user-images.githubusercontent.com/1051490/90294478-23ef7d80-de4c-11ea-9acf-05c302f0d210.png">

**Comment by kizniche** [comment]
Yes, you change the PID Period to 20.

**Comment by kizniche** [comment]
If what you mean is to turn off data grouping, you must check "Disable Data Grouping" for the particular graph Output series.

**Comment by BirdBare** [comment]
Oh my gosh that's what it was. Thanks so much! I don't know how I missed that in the manual. Thank you for your time.

**Comment by kizniche** [comment]
Your PID output is the result of your PID tuning (gains and integrator). If the output is higher than you would like, this indicates your Kp and/or Ki and/or integrator may be too high.
