### ISSUE TITLE
Sensor AM2302 crashes

### ISSUE THREAD

**Issue by fabriciofeijo** [kizniche/Mycodo#819]
Please DO NOT OPEN AN ISSUE:

 - If your Mycodo version is not the latest release version, please update your device before submitting your issue (unless your issue is related to not being able to upgrade). Your problem might already be solved.
 - If your issue has been addressed before (i.e., duplicated issue), please ask in the original issue.

Please complete as many of the sections below, if applicable, to provide the most information that may help with investigating your issue. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help those providing assistance by reducing the time required to help you.

### Describe the problem/bug

From times to times I need to disconect power line for sensor AM2302. They work well and crashes, at some time Mycodo didn't get sensor values until I reset them disconnecting and reconecting  3.3v cable to sensor. 

### Versions:

 - Mycodo Version: 8.7.1
 - Raspberry Pi Version: Raspberry pi zero w
 - Raspbian OS Version: buster

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

errros in mycodo.log

2020-08-20 20:23:08,180 - WARNING - mycodo.controllers.controller_pid_50e002b2 - No data returned from influxdb
2020-08-20 20:23:23,165 - WARNING - mycodo.controllers.controller_pid_50e002b2 - No data returned from influxdb
2020-08-20 20:23:32,241 - ERROR - mycodo.controllers.controller_input_570828fc - StopIteration raised 3 times. Possibly could not read input. Ensure it's connected properly and detected.
2020-08-21 09:26:32,305 - ERROR - mycodo.controllers.controller_input_570828fc - StopIteration raised 3 times. Possibly could not read input. Ensure it's connected properly and detected.
2020-08-21 09:27:17,293 - ERROR - mycodo.controllers.controller_input_570828fc - StopIteration raised 3 times. Possibly could not read input. Ensure it's connected properly and detected.
2020-08-21 09:28:02,240 - ERROR - mycodo.controllers.controller_input_570828fc - StopIteration raised 3 times. Possibly could not read input. Ensure it's connected properly and detected.
2020-08-21 09:28:38,169 - WARNING - mycodo.controllers.controller_pid_50e002b2 - No data returned from influxdb

### Expected behavior

Find a way to do sensor working for long time without need to reset it removing line power.

### Screenshots

My pid config
![image](https://user-images.githubusercontent.com/54818922/90891608-5d674200-e392-11ea-9633-ba49e3b8bd3a.png)
My sensor config
![image](https://user-images.githubusercontent.com/54818922/90891654-6eb04e80-e392-11ea-9ec3-01e8579ec38d.png)

### Additional context

Thanks

**Comment by fabriciofeijo** [comment]
> relay/transistor/MOSFET

I will try a workaround using a transistor to turn down and up the 3.3v to both sensors DHT22 and AM2302 (both uses same DHT22 library).

The sensors works well until I enable a Control PID. After enable termperature control throught Control PID, the DHT22 sensors crashs and need to physicaly reset the power to them. I don't know why it crashs, but only has crash when start to use relays to control temperature. Without enable control pid and also without using relays, the sensors DHT22 works fine...

![image](https://user-images.githubusercontent.com/54818922/90991709-a4fff080-e581-11ea-9ab3-f96815be0d2e.png)

**Comment by kizniche** [comment]
It's likely due to electrical interference caused by the relay or device being powered. If they run off the same power lines, this is even more likely.

As far as which temperature sensor to trust, you would need to determine which is closest to the actual temperature. You can also use a Math controller to create an offset of the measured temperature if you want to store/use a value closer to the actual temperature.

**Comment by fabriciofeijo** [comment]
I think it is something electrical too related to relay also, I let this last night without control pid and sensors works fine.

![image](https://user-images.githubusercontent.com/54818922/91038994-1ec7c680-e5e2-11ea-8bb5-c429b0582ca6.png)

I choose this parameters to use in Terrarium and Incubator

![image](https://user-images.githubusercontent.com/54818922/91039082-4a4ab100-e5e2-11ea-92a0-c6f0aec118f8.png)

I will study about math controller and try to normalize those sensors values.

My 4 channel relay card is diretc connected to Raspiberry pi zero but do not use same pins as power source.

4channel relay uses 5v and sensors uses 3.3v

This is some photos of my mushroom project.

![image](https://user-images.githubusercontent.com/54818922/91039481-03a98680-e5e3-11ea-81f5-4c0baedaaa2d.png)
![image](https://user-images.githubusercontent.com/54818922/91039527-1ae87400-e5e3-11ea-9b34-c466417825cf.png)
![image](https://user-images.githubusercontent.com/54818922/91039560-29369000-e5e3-11ea-829f-dc4963439db6.png)
