### ISSUE TITLE
dashboard graph report

### ISSUE THREAD

**Issue by Mark0Mi** [kizniche/Mycodo#821]
![image](https://user-images.githubusercontent.com/68497208/90984998-21da9c80-e579-11ea-95aa-4a676cdc11e0.png)
a pic shows more than words - the specific time point when the pump is switched on is logged 
the pump was on for 16 000 seconds -> 4.4 hours 
the graph shows one line at a time -> can I change this so that the graph shows a "high" as long as the pump is running? 

### Versions:

 - Mycodo Version: 8.7.1
 - Raspberry Pi Version: [e.g. 4B+]

**Comment by kizniche** [comment]
You can set minimum and maximum for specific y-axes in the graph options.

**Comment by Mark0Mi** [comment]
Hi 
I have seen this but I want to scale on x-axes (time)
I have drawn into the screenshot in yellow -> this is what I'd like to see (the seconds are counted -> I want this to be on X axes not y. is this possible at all? 
![image](https://user-images.githubusercontent.com/68497208/90987174-50f90a00-e589-11ea-96c6-70b9cf137e7e.png)
thanks!

**Comment by kizniche** [comment]
Well, the "X-axis" option let's you set the x axis. You can also enable the range selector.

**Comment by kizniche** [comment]
Oh, I see what you're asking. No, it is not possible.

**Comment by kizniche** [comment]
Though, you can now create and import your own widgets, so it's possible for you to copy and modify the graph widget to do what you want.
