### ISSUE TITLE
Python 3 Data input default code causes error

### ISSUE THREAD

**Issue by anticonformist08** [kizniche/Mycodo#827]
When you create a data input "Linux: Python 3 Code: Store Value(s)" option and then just try and save the command which is generated with the random number example the following error comes up: 

"Error: Modify Input: 'str' object has no attribute 'cmd_command'"

![image](https://user-images.githubusercontent.com/6132565/91124075-07312200-e664-11ea-8609-22ecc7081bb5.png)

**Comment by kizniche** [comment]
I just pushed a fix (commit reference above this comment) that will be available in the next release. You can perform the edit manually and restart the frontend from the Configuration menu to use the fix right away.
