### ISSUE TITLE
Logitech C920 Issues

### ISSUE THREAD

**Issue by jasonlaw0213** [kizniche/Mycodo#830]
Hey there!  Love Mycodo so far!  Working on a temp/humidity controlled relay setup for outlets shortly.  :)

However, I've run into an issue with trying to optimize my Camera settings for a spare webcam I have on-site, the Logitech C920 webcam on a Raspberry Pi 4 using opencv and would greatly appreciate your help.

There are several issues I'm seeing related to camera setup--

Upon default add, the image is grayscale -- I'm working within the v412-ctl CLI command to tweak the saturation and contrast to get it to a decent color depth and focus, but upon increasing the aforementioned values to ~100-150 (out of max 255), I start running into the following error shown in debug mode followed by corrupted video stream:

Corrupt JPEG data: 304 extraneous bytes before marker 0xd7
Corrupt JPEG data: 408 extraneous bytes before marker 0xd2
Corrupt JPEG data: 973 extraneous bytes before marker 0xd5
Corrupt JPEG data: found marker 0xd6 instead of RST7
Corrupt JPEG data: 208 extraneous bytes before marker 0xd6
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: 157 extraneous bytes before marker 0xd2
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: 644 extraneous bytes before marker 0xd4
Corrupt JPEG data: 540 extraneous bytes before marker 0xd0
Corrupt JPEG data: 1169 extraneous bytes before marker 0xd6
Corrupt JPEG data: 1077 extraneous bytes before marker 0xd7
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: 1161 extraneous bytes before marker 0xd3
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: 193 extraneous bytes before marker 0xd2
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: 796 extraneous bytes before marker 0xd2
Corrupt JPEG data: 106 extraneous bytes before marker 0xd3
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: 99 extraneous bytes before marker 0xd7

This is equally weird as I've used this webcam successfully on Octoprint (raspi 3D Printing using the same tweaks) as a live print webcam.  Unfortunately, I don't know what the delta is between their webcam implementation and Mycodo's.

I also noticed that increasing the values past ~150-160 causes the frontend to crash.

Any thoughts on resolution of these issues?  Alternatively, are there any webcams that are recommended as 100% working?

**Comment by kizniche** [comment]
I can't speak for compatibility with opencv and compatibility with that library, but I would recommend trying the fswebcam option. I have a C910 and it works great. Additionally, the Pi Cameras are the most supported for the Raspberry Pi, and a new camera was recently released that has a newer sensor and the ability to attach professional lenses.
