### ISSUE TITLE
Error on new install

### ISSUE THREAD

**Issue by gaffo** [kizniche/Mycodo#839]
Fresh install on ubuntu core 20, got error from install script (which never stopped).

Internal Server Error on https://mushroom.home.gaffo.org/data after creating admin account and logging in and going to data: [ise.txt](https://github.com/kizniche/Mycodo/files/5185831/ise.txt)
Output from my install logs: [install_logs.txt](https://github.com/kizniche/Mycodo/files/5185834/install_logs.txt)

**Comment by kizniche** [comment]
Ubuntu is not a supported operating system. If you want to deviate from the install requirements, I'd experiment with [docker](https://github.com/kizniche/Mycodo/wiki/Mycodo-and-Docker).

**Comment by gaffo** [comment]
Aah I missed the os requirement, thanks!
