### ISSUE TITLE
mjpg-streamer URL (urllib) Camera Error

### ISSUE THREAD

**Issue by rdrake** [kizniche/Mycodo#850]
### Describe the problem/bug

Adding a camera of type `URL (urllib)` then pointing it at [mjpg_streamer](https://github.com/jacksonliam/mjpg-streamer) results in an error when attempting to view a still image.

The following appears in the logs:

```
2020-09-17 08:23:20,255 [Errno 21] Is a directory: '/tmp/'
Traceback (most recent call last):
  File "/home/pi/Mycodo/mycodo/devices/camera.py", line 253, in camera_record
    urlretrieve(settings.url_still, path_tmp)
  File "/usr/lib/python3.7/urllib/request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')
IsADirectoryError: [Errno 21] Is a directory: '/tmp/'
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 140) > this->size() (which is 0)
```

### Versions:

 - Mycodo Version: 8.8.3
 - Raspberry Pi Version: 4B
 - Raspbian OS Version: Buster Lite

### Reproducibility

1. Go to **More** -> **Camera**
2. Add a camera by changing the type to **URL (urllib)** then clicking **Add**
3. Leave all options blank except **Still HTTP Address** (in my case, `http://<mycodo IP>:8080/?action=snapshot`)
4. Click **Save**
5. Beside the new camera, click **Capture Still**

### Expected behaviour

Still image displayed

### Additional context

The [code](https://github.com/kizniche/Mycodo/blob/d6713a8bca934e10f6188f46a9e64d3cf01b0322/mycodo/devices/camera.py#L247-L250) tries to derive `path_tmp` from the URL but in my case the filename is `''`.  The `URL (requests)` type [doesn't do this](https://github.com/kizniche/Mycodo/blob/d6713a8bca934e10f6188f46a9e64d3cf01b0322/mycodo/devices/camera.py#L295) and it works.

I see a few possible solutions:

1. Hardcode the `path_tmp` variable like the requests type
2. Check that `filename` is valid and, if not, hardcode `path_tmp`
3. Change [the request](https://github.com/kizniche/Mycodo/blob/d6713a8bca934e10f6188f46a9e64d3cf01b0322/mycodo/devices/camera.py#L253) to something like `path_tmp, _ = urlretrieve(settings.url_still)`

I'm happy to work on a PR for this.

**Comment by kizniche** [comment]
Thanks for the bug report. I just pushed a fix that will be live in the next release.
