### ISSUE TITLE
Selectable I2C address resetting

### ISSUE THREAD

**Issue by David-OConnor** [kizniche/Mycodo#855]
### Describe the problem/bug

Setting the I2C address does not take effect, and resets upon Activation. Occurs across multiple (all) I2c modules that have selectable addresses. (editable, and drop-down) 

### Versions:

 - Mycodo Version: 8.8.4
 - Raspberry Pi Version: 4
 - Raspbian OS Version: Buster

### Reproducibility

Setup -> Data -> Input -> Anyleaf: AnyLeaf pH (Or any other input with I2C selectable address). + -> Change the Address field. Activate. The sensor will read from the default address, and the selection box will reset to that. This happens regardless of the value of the `i2c_address_editable` field.

### Expected behavior

The address stays where you set it, and the Pi reads that I2C address.

**Comment by kizniche** [comment]
Did you press the Save button?

**Comment by David-OConnor** [comment]
Oops - looks like that was it! Working on my end. Going to pass words, and confirm it's working for the initial reporter!

**Comment by David-OConnor** [comment]
Sorted. Thank you!

**Comment by kizniche** [comment]
You're welcome. My easiest issue all week 😅
