### ISSUE TITLE
Conditional for Temperature fail safe IE: heating/lighting over temp

### ISSUE THREAD

**Issue by mnz454** [kizniche/Mycodo#858]
Hello,

I'm unsure where to post this but believe this to be an issue so i hope this OK.

I'm trying to make this system safer by adding high temp shut off control in the event anything gets to hot Mycodo can turn off relay X.

The only way i see this possible is via Conditional with action(s).

The problem is the Conditional feature checks if HIGH and checks if LOW or vice versa. not 1 action only.
It's causing relay shutoff even if condition is not met, Or this will turn lighting off then on every time condition is checked IE: 60seconds.

Do you have a solution Kizniche?

Cheers,
Mike

**Comment by kizniche** [comment]
I'm understanding your issue. Could you not create a Conditional with the following pseudo code?

```
if temperature > 30:
    run action -> deactivate Temperature PID
    run action -> turn off Output Heater
    run action -> email Admin@email.com
```
