### ISSUE TITLE
Dashboard SQL error

### ISSUE THREAD

**Issue by not5** [kizniche/Mycodo#873]
### Describe the problem/bug

Flask failing to load dashboard (existing or brand new) page. Looks to have to do with widget debugging? I don't have any widgets being debugged...

### Versions:

 - Mycodo Version: 8.8.8
 - Raspberry Pi Version: 3B+
 - Raspbian OS Version: Buster Desktop

### Traceback:

> Traceback (most recent call last):
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
>     cursor, statement, parameters, context
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
>     cursor.execute(statement, parameters)
> sqlite3.OperationalError: no such column: widget.log_level_debug
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
>     return original_handler(e)
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
>     return func(*args, **kwargs)
>   File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_page.py", line 571, in page_dashboard
>     dashboard = Widget.query.all()
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3346, in all
>     return list(self)
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
>     return self._execute_and_instances(context)
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
>     result = conn.execute(querycontext.statement, self._params)
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
>     return meth(self, multiparams, params)
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
>     distilled_params,
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
>     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
>     raise exception
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
>     cursor, statement, parameters, context
>   File "/home/pi/Mycodo/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: widget.log_level_debug
> [SQL: SELECT widget.id AS widget_id, widget.unique_id AS widget_unique_id, widget.graph_type AS widget_graph_type, widget.dashboard_id AS widget_dashboard_id, widget.name AS widget_name, widget.log_level_debug AS widget_log_level_debug, widget.font_em_name AS widget_font_em_name, widget.enable_drag_handle AS widget_enable_drag_handle, widget.position_x AS widget_position_x, widget.position_y AS widget_position_y, widget.width AS widget_width, widget.height AS widget_height, widget.custom_options AS widget_custom_options, widget.enable_header_buttons AS widget_enable_header_buttons, widget.period AS widget_period, widget.refresh_duration AS widget_refresh_duration, widget.x_axis_duration AS widget_x_axis_duration, widget.custom_yaxes AS widget_custom_yaxes, widget.decimal_places AS widget_decimal_places, widget.enable_status AS widget_enable_status, widget.enable_value AS widget_enable_value, widget.enable_name AS widget_enable_name, widget.enable_unit AS widget_enable_unit, widget.enable_measurement AS widget_enable_measurement, widget.enable_channel AS widget_enable_channel, widget.enable_timestamp AS widget_enable_timestamp, widget.pid_ids AS widget_pid_ids, widget.output_ids AS widget_output_ids, widget.math_ids AS widget_math_ids, widget.note_tag_ids AS widget_note_tag_ids, widget.input_ids_measurements AS widget_input_ids_measurements, widget.enable_navbar AS widget_enable_navbar, widget.enable_rangeselect AS widget_enable_rangeselect, widget.enable_export AS widget_enable_export, widget.enable_title AS widget_enable_title, widget.enable_auto_refresh AS widget_enable_auto_refresh, widget.enable_xaxis_reset AS widget_enable_xaxis_reset, widget.enable_manual_y_axis AS widget_enable_manual_y_axis, widget.enable_start_on_tick AS widget_enable_start_on_tick, widget.enable_end_on_tick AS widget_enable_end_on_tick, widget.enable_align_ticks AS widget_enable_align_ticks, widget.use_custom_colors AS widget_use_custom_colors, widget.custom_colors AS widget_custom_colors, widget.disable_data_grouping AS widget_disable_data_grouping, widget.max_measure_age AS widget_max_measure_age, widget.stops AS widget_stops, widget.range_colors AS widget_range_colors, widget.y_axis_min AS widget_y_axis_min, widget.y_axis_max AS widget_y_axis_max, widget.option_invert AS widget_option_invert, widget.font_em_value AS widget_font_em_value, widget.font_em_timestamp AS widget_font_em_timestamp, widget.enable_output_controls AS widget_enable_output_controls, widget.show_pid_info AS widget_show_pid_info, widget.show_set_setpoint AS widget_show_set_setpoint, widget.camera_id AS widget_camera_id, widget.camera_image_type AS widget_camera_image_type, widget.camera_max_age AS widget_camera_max_age 
> FROM widget]
> (Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by kizniche** [comment]
Your database appears to not have upgraded properly. It's missing a required column. You can try restoring an older version and upgrading again.
