### ISSUE TITLE
Conditional Function - Condition Check Issue

### ISSUE THREAD

**Issue by not5** [kizniche/Mycodo#879]
# Describe the problem/bug

Running a conditional Function that checks if a gpio pin is on or off is returning an error after upgrading to 8.8.8. It was working previous to upgrade. Can't remember what I upgraded from but wasn't too old.

### Versions:

 - Mycodo Version: 8.8.8
 - Raspberry Pi Version: 3b
 - Raspbian OS Version: Buster desktop

### Debug

ERROR - mycodo.outputs.on_off_gpio_1208fb4a - Status check error: 'db4b7106-57b2-4eae-becb-6793c339bfb4'

**Comment by kizniche** [comment]
It's impossible to diagnose without your code and particular conditional configuration options.

**Comment by not5** [comment]
Here's the code and configs:
`# Check status of COLD
measurement = self.condition("{5f9d1584}")

if measurement is not None:  # If a measurement exists

    if measurement == "on":  # If the HVAC is on
        self.run_action("{868e3915}", message=self.message)  # Turn on FAN

    elif measurement == "off":  # Else If the HVAC is off
        self.run_action("{23775ace}", message=self.message)  # Turn off FAN`

![Screenshot_20201111-225910_Chrome](https://user-images.githubusercontent.com/43415025/98893918-94209600-2471-11eb-8666-4e576a81e29c.jpg)

**Comment by kizniche** [comment]
Thanks. I'll test with an output state condition tomorrow.

**Comment by not5** [comment]
Thanks. I think it has to do with adding channels to outputs that didn't have channels before.

**Comment by kizniche** [comment]
Yes. That was an enormous amount of code change. There were bound to be parts I missed refactoring.

**Comment by kizniche** [comment]
Just pushed a fix that will be available in the next release.

**Comment by kizniche** [comment]
Just pushed a fix that will be available in the next release.
