### ISSUE TITLE
Output GPIO not set as output when Pi / Mycodo restarts 

### ISSUE THREAD

**Issue by LilianV** [kizniche/Mycodo#891]
Hello,

I have 4 outputs in my Mycodo, set up as "ON/OFF GPIO" type on pin 6, 13, 19 and 26.

When I restart the Pi, the outputs are not working because the GPIO's are not set as outputs until I open each of them and click "save".

Is it a normal behavior ?

 - Mycodo Version: 8.8.8
 - Raspberry Pi Version: Pi 4B Rev 1.2
 - Raspbian OS Version: Buster

Thanks for help.
Lilian

**Comment by kizniche** [comment]
Can you provide the output configuration options?

**Comment by LilianV** [comment]
> Can you provide the output configuration options?

Hello !

All 4 outputs are configured the same:

![image](https://user-images.githubusercontent.com/14853991/100063710-e4b0cf80-2e31-11eb-9453-2d875369a818.png)

They looks ok at startup:

![image](https://user-images.githubusercontent.com/14853991/100061017-b3360500-2e2d-11eb-8403-a5df60da9d7c.png)

But except for one of them (GPIO 6), GPIO's do not switch as outputs:

![image](https://user-images.githubusercontent.com/14853991/100063938-2b9ec500-2e32-11eb-8d3b-489d76f6be1a.png)

I have to re-open the output and save it (without any change) to switch GPIO:

![image](https://user-images.githubusercontent.com/14853991/100064314-a536b300-2e32-11eb-8f68-23daeadf4007.png)

![image](https://user-images.githubusercontent.com/14853991/100064373-bda6cd80-2e32-11eb-8be8-d4b29e962832.png)

Thanks for your help,
Lilian

**Comment by LilianV** [comment]
> Can you provide the output configuration options?

Hi again,

While answering ... I have understood why... I created those GPIO's as outputs AND inputs... stupid... but GPIO 6 was the only one disabled (as input)... sorry... my bad.

Lilian

**Comment by kizniche** [comment]
Glad you figured out the issue. If you need ways of querying the state of your outputs, I can give you my recommendations. There are numerous ways so I'd have to know where you need them (Conditional, custom Function, custom Input, etc.). As you found, having GPIO inputs with outputs can cause strange behaviors.
