### ISSUE TITLE
Need procedure to execute mycodo

### ISSUE THREAD

**Issue by jazzsam** [kizniche/Mycodo#894]
HI. I am very new to this pi coding. I have installed mycodo. I want to control GPIO and project camera. Please guide me to do step by step procedure after installation.

**Comment by kizniche** [comment]
I have a very detailed [manual](https://kizniche.github.io/Mycodo/Outputs/) that should help you understand how the output system works and can be configured. Briefly, you will need to add an On/Off GPIO output and conure the pin your device is connected to (using BCM numbering). You can then control the voltage state (high/low) of that pin.
