### ISSUE TITLE
Error 502: Bad Gateway Error

### ISSUE THREAD

**Issue by electricspaceman** [kizniche/Mycodo#909]
Hi,

Receiving this error. I am using the master branch.

![Screen Shot 2020-12-17 at 14 41 21](https://user-images.githubusercontent.com/34949113/102502078-16563880-4076-11eb-8d91-9d54c170836a.png)

**Comment by kizniche** [comment]
The line number isn't what's found on the master branch, so it's probably something you did to the code.

**Comment by not5** [comment]
As @kizniche said, the error is not part of an official release-- my recommendation would be to delete the max31865_circuitpython.py input from the folder and restart. If you're messing with the github inputs, you should really be importing it as a custom input (with a unique name, of course).

**Comment by kizniche** [comment]
From https://github.com/kizniche/Mycodo/issues/570#issuecomment-747459599, it looks like you commented out the only line in ```finally```, therefore it's expecting the return to be indented to that level. You should put ```pass``` in ```finally``` or remove the try/finally block all together.
