### ISSUE TITLE
Job for mycodo.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by mm1994uestc** [kizniche/Mycodo#914]
# Mycodo service intalling mistakes with my raspberry pi 4  
## The step installed mycodo is blow:  
1. I download the mycodo code in .zip format.   
2. unzip the master.zip source code in my raspberrpi.  
3. change directory into the install folder and run command: sudo /bin/bash ./setup.sh  
4. waitting for installing finished.  

## After waitting for installation, Here the bugs information:
[setup.log](https://github.com/kizniche/Mycodo/files/5744291/setup.log)
Follow the error message i did this blow:
1. systemctl status mycodo.service
    
<img width="949" alt="systemctl-status-mycodo-service" src="https://user-images.githubusercontent.com/19512690/103167189-03a4e600-4864-11eb-8134-4fff8394b6a6.png">

2. journalctl -xe
    
<img width="960" alt="Journalctl" src="https://user-images.githubusercontent.com/19512690/103167194-0f90a800-4864-11eb-9b56-e2cf4cd10759.png">

3. I am trying to refresh the webpage but make nothings:  

<img width="918" alt="Webmessage" src="https://user-images.githubusercontent.com/19512690/103167224-57afca80-4864-11eb-867d-8ae5f8356f59.png">

## How can i fix the problems? Any suggestions？Thanks a lot！

**Comment by kizniche** [comment]
Your setup log indicates you had an issue installing virtualenv:

```
#### Virtualenv doesn't exist. Creating...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting virtualenv
  Downloading https://www.piwheels.org/simple/virtualenv/virtualenv-20.2.2-py2.py3-none-any.whl (5.7 MB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    virtualenv from https://www.piwheels.org/simple/virtualenv/virtualenv-20.2.2-py2.py3-none-any.whl#sha256=54b05fc737ea9c9ee9f8340f579e5da5b09fb64fd010ab5757eb90268616907c:
        Expected sha256 54b05fc737ea9c9ee9f8340f579e5da5b09fb64fd010ab5757eb90268616907c
             Got        9ad82547bcc2797da554e92d054e0a4c305bf135934d766cc46c35446655bbc1
```

**Comment by mm1994uestc** [comment]
Thanks for your reply，I have installed the python3-virtualenv manually, and it's worked now.
