### ISSUE TITLE
Invoke Action from Custom Function

### ISSUE THREAD

**Issue by chamroeunbm** [kizniche/Mycodo#920]
**Is your feature request related to a problem? Please describe.**
 Cannot select Action(Email,..Shutdown...) from Custom Function. Or maybe I missed this, but i can't find it in the code to do that.

**Describe the solution you'd like**
The ability to add dropdown list actions like email alert... from Custom Function. What i can see in custom function now is "Input,Output,PID,..."

**Describe alternatives you've considered**

**Additional context**

**Comment by kizniche** [comment]
Only Conditional Controllers and the Execute Actions Function are designed to use Function Actions. For Custom Functions, you must call the function that performs whichever task you desire itself. For example, in custom_function_example.py you will notice on lines 255 - 261 the selected output will be turned on for 15 seconds: https://github.com/kizniche/Mycodo/blob/85e99fabed86816e9da9da96c570c5c0e973d398/mycodo/functions/examples/custom_function_example.py#L255-L261

This same function is called by the Output On/Off/Duration Action. You can find many of these functions in [mycodo_client.py](https://github.com/kizniche/Mycodo/blob/85e99fabed86816e9da9da96c570c5c0e973d398/mycodo/mycodo_client.py) and can be called the same way as above, e.g.:

```python
from mycodo.mycodo_client import DaemonControl
control = DaemonControl()
control.function_to_execute(param1, param2)
```
