### ISSUE TITLE
Wrong Scale - Pressure Measurement in Climate Sensors (BME260, BME680, etc)

### ISSUE THREAD

**Issue by not5** [kizniche/Mycodo#923]
### Describe the problem/bug

These sensor's units should be in hPa for pressure (and vapor pressure deficit), not Pa. The conversion is 0.01 hPa to 1 PA. This causes all altitude calculations to be off.

**Comment by kizniche** [comment]
Thanks. I'll fix this for the next release.

**Comment by kizniche** [comment]
For compatibility, and to maintain SI units, I'll merely convert the returned hPa to Pa that's currently stored.
