### ISSUE TITLE
Can't rename sensor or add GPIO

### ISSUE THREAD

**Issue by berserktron3k** [kizniche/Mycodo#93]
When trying to add RPi CPU Temp or Load sensors and rename them, or add and rename/assign GPIO to DHT22, I get the following in the web interface:

Sensor settings were not able to be modified: could not convert string to float:

**Comment by kizniche** [comment]
Ah. Update your system and it should work again. I pushed a fix for that error less than an hour ago. ;)

**Comment by berserktron3k** [comment]
Weird. I just did a clean install (about the time you must have made the
change). Thought it was related to the work you were doing on the other
issue, so also just ran an update from within the web console... same
issue. Forced a reboot too, and issue resides.

Let me try re-cloning from GIT.

Brady Hummel

**Comment by kizniche** [comment]
Oh, you're right. I didn't make a full fix for that bug. Give me a minute.

**Comment by berserktron3k** [comment]
Np. Take your time.

Brady Hummel

**Comment by kizniche** [comment]
I just pushed a fix. Let me know if the bug is still there after you upgrade.
