### ISSUE TITLE
API Controller activate/deactivate (input)

### ISSUE THREAD

**Issue by tilersmyth** [kizniche/Mycodo#944]
### Describe the problem/bug

When deactivating a controller (input in my case) using the POST API the is_activated column in the input table is not updating. 

### Versions:

 - Mycodo Version: 8.9.0 (also the case for 8.8.8)
 - Raspberry Pi Version: 3B+
 - Raspbian OS Version: Raspberry Pi OS Lite

### Reproducibility

1. Send POST API request to /api/controllers/{unique_id} with body { "activate": 1 } 
2. Open the Input page in Mycodo backend and the input will reflect as activated (it works)
3. Send POST API request to /api/controllers/{unique_id} with body { "activate": 0 } 
4. Refresh the input page and the input still reflects as activated 
5. If you press the "Deactivate" button in the Mycodo backend you will receive an error message along the lines of "Error: Could not deactivate Input controller with ID {unique_id}, it's not active."

Note: it's interesting that continuing to toggle activate/deactivate via the API alone will continue to work - Even though the database has the input.is_activated=1, the POST API to activate is received with no errors.

**Comment by kizniche** [comment]
Thanks for the bug report. It's probably activating/deactivating in the daemon but not changing the database value. I'll look into it.
