### ISSUE TITLE
Cannot save MQTT input configuration changes

### ISSUE THREAD

**Issue by danielfppps** [kizniche/Mycodo#946]
I am using Mycodo 8.9.0. Whenever I add an MQTT input, click the (+) sign and then click "Save" - no changes made at all - I receive the following error :

Error: Modify Input: '<' not supported between instances of 'NoneType' and 'float'

The error happens regardless of which fields I change or attempt to modify (even when no fields are modified as I mentioned above). I'm new to mycodo so please do let me know if I'm doing something wrong. Thanks in advance for your help!

**Comment by kizniche** [comment]
I'll take a look. Thanks for the bug report.

**Comment by chamroeunbm** [comment]
Same issue here.

**Comment by OriginalOC** [comment]
Same here.

**Comment by chamroeunbm** [comment]
hi @kizniche , still bug in utils_input.py on line 484. 

it should be new_channel.channel rather than new_measurement.channel = index

**Comment by kizniche** [comment]
>it should be new_channel.channel rather than new_measurement.channel = index

Good catch. just pushed a fix. Thanks.
