### ISSUE TITLE
Hall effect flow sensor - Cant save pulses per liter value

### ISSUE THREAD

**Issue by nagol10h** [kizniche/Mycodo#952]
problem/bug

After upgrading Mycodo to version 8.9.0(and then 8.9.1) I was looking forward to using the generic hall effect flow sensor input
The input works great except the pulses per liter number will not save a new value so it stays at 1 pulse per liter after saving. 

I have tried several system restarts as well as back and front end restarts with no change in results. 
This issue is the same for Mycodo 8.9.0 and 8.9.1

The flowmeter input functions normally just with a large flow showing due to the 1 pulse per liter setting that cannot be changed.
I can do a function to recalculate to actual liters as a workaround but wanted to raise the issue because I have not seen it brought up yet. 

I really enjoy the software! 

### Versions:

 - Mycodo Version: [8.9.1]
 - Raspberry Pi Version: [ 3B+]
 - Raspbian OS Version: 
 - pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Reproducibility

Deactivate flow meter input
Change pulses per liter to appropriate conversion number (450 for my flow sensor)
Save input

### Expected behavior

Input is saved with new pulse per liter setting(450) 

Instead input remains at 1 pulse per liter (default setting)

**Comment by kizniche** [comment]
The value is actually being saved to whatever you set, but it's erroneously displaying the default 1.0 value on the frontend. I just pushed a fix to display the correct value. This issue affected both Inputs and Outputs that had Custom Actions.
