### ISSUE TITLE
Cannot activate Bang-Bang Hysteretic function

### ISSUE THREAD

**Issue by JustinCredible-** [kizniche/Mycodo#953]
Trying to Activate a Bang-Bang Hysteretic function after initial configuration and saving. Errors with "Error: Error: receiving: timeout"

 - Mycodo Version: [e.g. 8.0.3] 8.9.1
 - Raspberry Pi Version: [e.g. 3B+] a02082
 - Raspbian OS Version: [e.g. Buster Lite] Linux raspberrypi 5.10.17-v7+

1. Go to Setup -> Function
2. Click on Activate on Bang-Bang Hysteretic function
3. After a period of time, page will refresh with success messages "Success: Function Activate (SQL)
Success: Activate Controller" and error message "Error: Error: receiving: timeout"

Expect function to enable and start working.

![Untitled](https://user-images.githubusercontent.com/7981902/111249828-f4674600-85d1-11eb-9372-f62bc45939ba.png)

![Untitled](https://user-images.githubusercontent.com/7981902/111249798-e285a300-85d1-11eb-88fc-e752eb7dfdff.png)

Brand new installation using SHT31D sensor, all sensor values reporting (temp, humidity, dewpoint, VPD) and PID Controller, Conditional Controllers activate and work fine.

**Comment by kizniche** [comment]
Thanks for the bug report. I'll take a look.

**Comment by JustinCredible-** [comment]
Sure! I was kind of wondering what logs I should poke at to see where it’s
failing on my side

**Comment by kizniche** [comment]
Configure -> Mycodo Logs -> Daemon Log is where I would start. I see the issue and am figuring out a fix.

**Comment by kizniche** [comment]
Just pushed a fix that will be available in the next release.

**Comment by JustinCredible-** [comment]
Upgraded to 8.9.2 and the function activates now. Thank you!
