### ISSUE TITLE
API End point to get historical data for inputs

### ISSUE THREAD

**Issue by danielfppps** [kizniche/Mycodo#966]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to remotely get data from a MyCodo server in an automated manner (that I'm aware of). The only way is to manually export data, which can be cumbersome if this needs to be done routinely. 

**Describe the solution you'd like**
Ideally there would be an API end point that enables us to get historical data for a given sensor and datetime range.

**Comment by kizniche** [comment]
You mean like this?

https://kizniche.github.io/Mycodo/mycodo-api.html#operation/get_measurements_past

**Comment by danielfppps** [comment]
Oh sorry, hadn't seen it! Thanks for showing me.

**Comment by kizniche** [comment]
No problem. Have fun in the API!
