### ISSUE TITLE
Incorrect tooltip text

### ISSUE THREAD

**Issue by peakej** [kizniche/Mycodo#975]
Please DO NOT OPEN AN ISSUE:

 - If your Mycodo version is not the latest release version, please update your device before submitting your issue (unless your issue is related to not being able to upgrade). Your problem might already be solved.
 - If your issue has been addressed before (i.e., duplicated issue), please ask in the original issue.

Please complete as many of the sections below, if applicable, to provide the most information that may help with investigating your issue. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help those providing assistance by reducing the time required to help you.

### Describe the problem/bug

Tooltip for "Max Age (seconds)" id="max_measure_age" incorrectly displays "The maximum age of the camera image" on PID widgets.  I believe it should be "The maximum age (seconds) of the measurement"

### Versions:

 - Mycodo Version: 8.9.2
 - Raspberry Pi Version: 3B
 - Raspbian OS Version: Buster Lite

### Reproducibility

1. Add a PID controller widget to the dashboard
2. Hover over the Max age field
2. See error

### Expected behavior

Tooltip to display: "The maximum age of the camera image"

### Screenshots

![Screenshot 2021-04-07 203339](https://user-images.githubusercontent.com/4805072/113924897-4753a800-97e2-11eb-9087-aed3a4967720.png)

### Additional context

None

**Comment by kizniche** [comment]
Thanks! Indeed, I think you're correct :smile: I'll push a fix that'll be incorporated in the next release.
