### ISSUE TITLE
Can not setup VPD Function.  Getting error 'measurement/unit not set' when it is set?

### ISSUE THREAD

**Issue by LucidEye** [kizniche/Mycodo#978]
I am having trouble setting up the VPD function.

In the VPD function setup I am linking the temp and humidity to one of my BME280 sensors.

In the inputs setup, I have set that sensor to convert it's pressure and VPD readings to kPa, and set the temp to convert into F.

Back in the VPD function setup, if I only set the temp and humidity parameters and click on the save button at the top of the function window, it saves and the function works ok when I activate it...

![VPD WORKING](https://user-images.githubusercontent.com/12551280/114286274-1e195e80-9a12-11eb-8820-85900e798f39.png)

However, I want to have the reading shown in kPa instead of the default Pa....

![VPD SETTINGS BEFORE](https://user-images.githubusercontent.com/12551280/114286288-3b4e2d00-9a12-11eb-8079-4b5493f4ff6a.png)

When I try to set the "name" under "Configure Measurements" to "VPD" and set it to "convert to kPa" then click save, the "Measurements Enabled" field gets 'cleared' for some reason and the function will no longer activate without throwing the error:

"Error: Activate Controller: Measurement CH0 (VPD) measurement/unit not set. All Measurements need to have the measurement and unit set before the Function can be activated."

![VPD AFTER SAVING NAME](https://user-images.githubusercontent.com/12551280/114286294-44d79500-9a12-11eb-84e4-859ff64eb65d.png)

There is no way to make the function work again without deleting the whole function and re-adding it again.

Is this a bug, or am I doing something wrong?

Thank you,
JCL

**Comment by kizniche** [comment]
That error shouldn't be occurring. I'll look into it. Thanks for the bug report.

**Comment by LucidEye** [comment]
I also just noticed in the "Live Data" screen that the air pressure readings from both my sensors seem to be reading way too high.  I checked a local open weather station in our neighborhood and the current pressure in kPa is around 100.4.  So something is really wrong here.

![BME280 sensor readings - pressure is way too high](https://user-images.githubusercontent.com/12551280/114286854-55d6d500-9a17-11eb-972f-f38fc6c3bb28.png)

**Comment by LucidEye** [comment]
I just tried deleting both BME280 sensors from the Inputs page and reinstalling them using the RPI library instead of the Adafruit library and I am still getting bad readings...

![BME280 with RPI library still reading wrong](https://user-images.githubusercontent.com/12551280/114287704-c5e85980-9a1d-11eb-8f95-09f65cdd6d13.png)

Any ideas what is going on here?
I seem to remember I was also getting bad readings on the air pressure when using the BMP280 sensors I accidentally ordered from Adafruit.

**Comment by kizniche** [comment]
Just checking that you're aware that the BME Input calculates VPD as one of its measurements, making use of the VPD Function redundant.

**Comment by kizniche** [comment]
Fixed the issue with saving the configuration and the unit conversion. It was multiplying by 1000 instead of dividing.

**Comment by LucidEye** [comment]
So how do I get these changes upgraded on my system?  I tried running an upgrade from the web-interface and it says there is no update available.  I tried running 'sudo mycodo-commands upgrade-mycodo' and got this error:

'Unable to upgrade. You currently have the latest release installed.
#### ERROR ####
There was an error detected during the upgrade. Please review the log at /var/log/mycodo/mycodoupgrade.log'

There is no log file at '/var/log/mycodo/mycodoupgrade.log'

![no log](https://user-images.githubusercontent.com/12551280/114294186-abc86e80-9a51-11eb-85ee-08c6d0b08786.png)

**Comment by kizniche** [comment]
If you want to test pre-release code, you'll need to [upgrade to master](https://github.com/kizniche/Mycodo/wiki/Updating-to-Github-Master-Branch). Keep in mind this may be unstable. I'm currently working on some pretty big changes that I've yet to commit, so I may have some fixes that are still staged in my IDE.
