### ISSUE TITLE
Could you add this "Analog Capacitive Soil Moisture Sensor" to the default inputs?

### ISSUE THREAD

**Issue by pupuliesp** [kizniche/Mycodo#981]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
This input to be added

**Describe alternatives you've considered**
Dont know, really.

https://www.dfrobot.com/product-1385.html

**Comment by kizniche** [comment]
You should be able to hook this up to any of the supported [analog-to-digital converters](https://kizniche.github.io/Mycodo/Analog-To-Digital-Converters/).
