### ISSUE TITLE
Atlas Gravity Analog pH Sensor Calibration

### ISSUE THREAD

**Issue by cactuscrawford** [kizniche/Mycodo#982]
Hi Kyle

Huge fan.

Is it possible to calibrate or add calibration for the Atlas Analog probes? 

Regards
Todd

**Comment by kizniche** [comment]
Check out https://forum.kylegabriel.com/t/how-to-create-a-custom-input-with-associated-calibration-routine/55

**Comment by cactuscrawford** [comment]
Thank you for the **very** prompt response!
