### ISSUE TITLE
PID cannot be activated

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#99]
Apparently the method code broke this function. In flask debug mode, the error is in line 1511 of flaskutil.py. After removing the code added with the two commits on Aug 6, the PID may be activated. It seems that a check is missing if someone wants to run the PID without any special tweaks, just the simple setpoint and nothing else.

**Comment by kizniche** [comment]
That's a pretty big issue. I haven't had a moment of free time this morning, but when I do I'll push a fix.
