### ISSUE TITLE
Hall Flow Meter input throws error when "Clear Total Volume" button is clicked

### ISSUE THREAD

**Issue by dookaloosy** [kizniche/Mycodo#994]
### Describe the problem/bug

With the Hall Flow Meter input activated, click on Clear Total Volume button. The error "Error: Action, Controller: 'NoneType' object is not subscriptable" is thrown and the total volume remains uncleared.

### Versions:

 - Mycodo Version: 8.10.1
 - Raspberry Pi Version: 3B
 - Raspbian OS Version: Linux raspberrypi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux

### Reproducibility

1. Hall Flow Meter input is configured and activated, with a non-zero total volume.
2. Click on Clear Total Volume button.
3. Note the error message and that the total volume is not cleared to zero.

### Expected behavior

The total volume should clear to zero.

### Screenshots

N/A

### Additional context

N/A

**Comment by kizniche** [comment]
Just committed a fix. It was a typo.
