### ISSUE TITLE
Trigger Output on/off function not working with Duration time settings.

### ISSUE THREAD

**Issue by LucidEye** [kizniche/Mycodo#999]
Mycodo 8.10.1
RaspberryOS Buster 10
Kernel Version 5.10.17-v7+

I am trying to use a Trigger: output on/off function and it is not working if I try to use a Duration time.
The output only turns on if I set the If State to "on (no duration)".
I need to set a duration, but none of the duration settings in the If State work... the output never turns on after the duration time passes.
In the Daemon log, it never shows the output being turned on.
However when I click "test all actions" in the function setup, the output turns on immeadiately, it just doesn't work with the Duration timer.

EXPECTED BEHAVIOR:  
- Trigger: Output On/Off - Output = humidifier.  If humidifier turns on, wait for greater than X seconds, then turn Fan Speed (PWM Duty Cycle) up to 60%.
- When Humidifier turns off, PMW should return to previous state (PMW duty cycle 25%).

OBSERVED BEHAVIOR (log level: debug enabled):  
- Output (PWM Duty Cycle) ONLY turns on when "If State" is set to:
On (no duration) - debug log shows output activating
On (no or any duration) - debug log shows output activating
When humidifier turns off, the PWM stays at 60% instead of returning to previous setting (25%)
I need to create a separate Trigger on/off function to return the PWM to 25% after the humidifier turns off.
Shouldn't a single function be able to check both on and off conditions without having to create separate functions, one each for on and off?
If condition is on:
activate output - after duration time expires if time is set
If condition is off:
return output to previous state - after duration time expires if time is set

- Output (PWM Duty Cycle) NEVER turns on if the settings are any of the following:
On (any duration) - debug log shows nothing, no action being taken, output never turns on.
On (equal to duration) - debug log shows nothing, no action being taken, output never turns on.
On (greater than duration) - debug log shows nothing, no action being taken, output never turns on.
On (greater than or equal to) - debug log shows nothing, no action being taken, output never turns on.
On (less than duration) - not tested
On (less than or equal to duration) - not tested

![Screenshot at 2021-05-10 12-09-20](https://user-images.githubusercontent.com/12551280/117711950-9184cc00-b188-11eb-95c5-ab86ef5fc3e1.png)

This behavior seems like a bug.  At least one of the "On - Duration" settings should be doing something after the Duration time is expired... but they are not.

Aside from the above problem I am experiencing, I have a suggestion.  As it is, you have the Output Trigger: On/Off setup so that you can activate several outputs from a single output's condition state, which is awesome...   but it would be very useful if it could also be configured as a "cascade" trigger by adding duration timer settings to each individual Action.  For example, my humidifier turns on activating the cascade trigger, after 30 seconds my fans turn up to 60% duty cycle, 60 seconds later I activate an inline air duct heater, 120 seconds later I activate a servo that opens a fresh-air inlet vent... etc.  It would also be useful to have the "Off" states have the ability to use a duration timer as well... right now the duration time is only available for "On" states. Example... My trigger output turns off my inline air duct heater... wait 60 seconds to turn off the action output running my fans to ensure the heating element is cooled off before air in the duct goes static, 30 seconds later close the air-inlet vent.

Thank you once again for your help.

**Comment by LucidEye** [comment]
Well then I am not understanding what additional information you are asking for other than what I have already explained.  The picture I posted shows what output I added, what type it is, and how it was configured.
Not sure what other "steps" I can describe other than the ones I already have.
I have tried setting this function up multiple times, deleting and re-adding it, setting every field to a different setting, and nothing I try works... the duration timer does not work when the output trigger activates.... but it works ok if I click "test all options".

**Comment by kizniche** [comment]
1. Those are not steps (i.e. 1., 2., 3., etc.)
2. The output configuration is not listed.

**Comment by LucidEye** [comment]
You are really confusing me.  Can you please be very concise as to what it is you need me to tell you?  Are you telling me I need to number each line as a step?

**Comment by LucidEye** [comment]
There are only 2 outputs... my humidifier...

![Screenshot at 2021-05-10 14-56-35](https://user-images.githubusercontent.com/12551280/117729648-ff88bd80-b19f-11eb-86fc-ded97732b183.png)
